"""
Deep Localization Engine
========================
10-language translation matrix for all instructional text.
Supports: ar, en, de, fr, tr, ru, sv, nl, el, de-AT
"""

SUPPORTED_LOCALES = ["ar", "en", "de", "fr", "tr", "ru", "sv", "nl", "el", "de-AT"]

# All UI/instructional strings used across the curriculum
L10N = {
    # Section Titles
    "meet_the_letter": {
        "ar": "تعرّف على الحرف",
        "en": "Meet the Letter",
        "de": "Lerne den Buchstaben kennen",
        "de-AT": "Lern den Buchstaben kennen",
        "fr": "Découvre la lettre",
        "tr": "Harfi Tanı",
        "ru": "Знакомство с буквой",
        "sv": "Lär känna bokstaven",
        "nl": "Maak kennis met de letter",
        "el": "Γνώρισε το γράμμα",
    },
    "listen_repeat": {
        "ar": "استمع وردّد",
        "en": "Listen & Repeat",
        "de": "Hören & Nachsprechen",
        "de-AT": "Zuhören & Nachsprechen",
        "fr": "Écoute et répète",
        "tr": "Dinle ve Tekrarla",
        "ru": "Слушай и повторяй",
        "sv": "Lyssna och upprepa",
        "nl": "Luister en herhaal",
        "el": "Άκουσε και επανάλαβε",
    },
    "test_yourself": {
        "ar": "اختبر نفسك",
        "en": "Test Yourself",
        "de": "Teste dich selbst",
        "de-AT": "Test dich selbst",
        "fr": "Teste-toi",
        "tr": "Kendini Test Et",
        "ru": "Проверь себя",
        "sv": "Testa dig själv",
        "nl": "Test jezelf",
        "el": "Δοκίμασε τον εαυτό σου",
    },
    "practice_writing": {
        "ar": "تمرين الكتابة",
        "en": "Practice Writing",
        "de": "Schreibübung",
        "de-AT": "Schreibübung",
        "fr": "Exercice d'écriture",
        "tr": "Yazma Alıştırması",
        "ru": "Практика письма",
        "sv": "Skrivövning",
        "nl": "Schrijfoefening",
        "el": "Εξάσκηση γραφής",
    },
    "new_word": {
        "ar": "كلمة جديدة",
        "en": "New Word",
        "de": "Neues Wort",
        "de-AT": "Neues Wort",
        "fr": "Nouveau mot",
        "tr": "Yeni Kelime",
        "ru": "Новое слово",
        "sv": "Nytt ord",
        "nl": "Nieuw woord",
        "el": "Νέα λέξη",
    },
    "new_sentence": {
        "ar": "جملة جديدة",
        "en": "New Sentence",
        "de": "Neuer Satz",
        "de-AT": "Neuer Satz",
        "fr": "Nouvelle phrase",
        "tr": "Yeni Cümle",
        "ru": "Новое предложение",
        "sv": "Ny mening",
        "nl": "Nieuwe zin",
        "el": "Νέα πρόταση",
    },
    "read_word": {
        "ar": "اقرأ الكلمة",
        "en": "Read the Word",
        "de": "Lies das Wort",
        "de-AT": "Lies das Wort",
        "fr": "Lis le mot",
        "tr": "Kelimeyi Oku",
        "ru": "Прочитай слово",
        "sv": "Läs ordet",
        "nl": "Lees het woord",
        "el": "Διάβασε τη λέξη",
    },
    "learn": {
        "ar": "تعلّم",
        "en": "Learn",
        "de": "Lernen",
        "de-AT": "Lernen",
        "fr": "Apprends",
        "tr": "Öğren",
        "ru": "Учись",
        "sv": "Lär dig",
        "nl": "Leer",
        "el": "Μάθε",
    },
    "memorize": {
        "ar": "احفظ",
        "en": "Memorize",
        "de": "Auswendig lernen",
        "de-AT": "Auswendig lernen",
        "fr": "Mémorise",
        "tr": "Ezberle",
        "ru": "Запомни",
        "sv": "Memorera",
        "nl": "Onthoud",
        "el": "Απομνημόνευσε",
    },
    "listen": {
        "ar": "استمع",
        "en": "Listen",
        "de": "Zuhören",
        "de-AT": "Zuhören",
        "fr": "Écoute",
        "tr": "Dinle",
        "ru": "Слушай",
        "sv": "Lyssna",
        "nl": "Luister",
        "el": "Άκουσε",
    },
    "recite": {
        "ar": "سمّع",
        "en": "Recite",
        "de": "Aufsagen",
        "de-AT": "Aufsagen",
        "fr": "Récite",
        "tr": "Oku",
        "ru": "Произнеси",
        "sv": "Recitera",
        "nl": "Reciteren",
        "el": "Απάγγειλε",
    },
    "todays_hadith": {
        "ar": "حديث اليوم",
        "en": "Today's Hadith",
        "de": "Hadith des Tages",
        "de-AT": "Hadith des Tages",
        "fr": "Hadith du jour",
        "tr": "Günün Hadisi",
        "ru": "Хадис дня",
        "sv": "Dagens hadith",
        "nl": "Hadith van de dag",
        "el": "Χαντίθ της ημέρας",
    },
    "reflect": {
        "ar": "تأمّل",
        "en": "Reflect",
        "de": "Nachdenken",
        "de-AT": "Nachdenken",
        "fr": "Réfléchis",
        "tr": "Düşün",
        "ru": "Размышляй",
        "sv": "Reflektera",
        "nl": "Reflecteren",
        "el": "Σκέψου",
    },
    "grammar": {
        "ar": "قواعد",
        "en": "Grammar",
        "de": "Grammatik",
        "de-AT": "Grammatik",
        "fr": "Grammaire",
        "tr": "Gramer",
        "ru": "Грамматика",
        "sv": "Grammatik",
        "nl": "Grammatica",
        "el": "Γραμματική",
    },
    "comprehensive_review": {
        "ar": "مراجعة شاملة",
        "en": "Comprehensive Review",
        "de": "Umfassende Wiederholung",
        "de-AT": "Umfassende Wiederholung",
        "fr": "Révision complète",
        "tr": "Kapsamlı Tekrar",
        "ru": "Полный обзор",
        "sv": "Omfattande genomgång",
        "nl": "Uitgebreide herhaling",
        "el": "Ολοκληρωμένη επανάληψη",
    },
    "review": {
        "ar": "مراجعة",
        "en": "Review",
        "de": "Wiederholung",
        "de-AT": "Wiederholung",
        "fr": "Révision",
        "tr": "Tekrar",
        "ru": "Обзор",
        "sv": "Genomgång",
        "nl": "Herhaling",
        "el": "Επανάληψη",
    },
    "write_sentence": {
        "ar": "اكتب الجملة",
        "en": "Write the Sentence",
        "de": "Schreibe den Satz",
        "de-AT": "Schreib den Satz",
        "fr": "Écris la phrase",
        "tr": "Cümleyi Yaz",
        "ru": "Напиши предложение",
        "sv": "Skriv meningen",
        "nl": "Schrijf de zin",
        "el": "Γράψε την πρόταση",
    },
    "test": {
        "ar": "اختبر",
        "en": "Test",
        "de": "Test",
        "de-AT": "Test",
        "fr": "Test",
        "tr": "Test",
        "ru": "Тест",
        "sv": "Test",
        "nl": "Test",
        "el": "Τεστ",
    },
    "lesson": {
        "ar": "درس",
        "en": "Lesson",
        "de": "Lektion",
        "de-AT": "Lektion",
        "fr": "Leçon",
        "tr": "Ders",
        "ru": "Урок",
        "sv": "Lektion",
        "nl": "Les",
        "el": "Μάθημα",
    },
    "memorize_dua": {
        "ar": "احفظ الدعاء",
        "en": "Memorize the Dua",
        "de": "Lerne das Dua auswendig",
        "de-AT": "Lern das Dua auswendig",
        "fr": "Mémorise le Dua",
        "tr": "Duayı Ezberle",
        "ru": "Запомни дуа",
        "sv": "Memorera dua",
        "nl": "Onthoud de dua",
        "el": "Απομνημόνευσε το ντουά",
    },
    "quiz_complete_dua": {
        "ar": "أكمل الدعاء التالي",
        "en": "Complete the following dua",
        "de": "Vervollständige das folgende Dua",
        "de-AT": "Vervollständige das folgende Dua",
        "fr": "Complète le dua suivant",
        "tr": "Aşağıdaki duayı tamamla",
        "ru": "Дополни следующую дуа",
        "sv": "Komplettera följande dua",
        "nl": "Vul de volgende dua aan",
        "el": "Συμπλήρωσε το ακόλουθο ντουά",
    },
    # Tips & Instructions
    "tip_tap_letter": {
        "ar": "اضغط على الحرف للاستماع، ثم رددّه بصوتك",
        "en": "Tap the letter to listen, then repeat out loud",
        "de": "Tippe auf den Buchstaben zum Anhören, dann sprich ihn laut nach",
        "de-AT": "Tipp auf den Buchstaben zum Anhören, dann sprich ihn laut nach",
        "fr": "Appuie sur la lettre pour écouter, puis répète à voix haute",
        "tr": "Dinlemek için harfe dokun, sonra yüksek sesle tekrarla",
        "ru": "Нажми на букву, чтобы послушать, затем повтори вслух",
        "sv": "Tryck på bokstaven för att lyssna, upprepa sedan högt",
        "nl": "Tik op de letter om te luisteren, herhaal dan hardop",
        "el": "Πάτησε το γράμμα για να ακούσεις, μετά επανάλαβέ το δυνατά",
    },
    "tip_write_letter_5": {
        "ar": "اكتب الحرف ٥ مرات على الورق",
        "en": "Write the letter 5 times on paper",
        "de": "Schreibe den Buchstaben 5-mal auf Papier",
        "de-AT": "Schreib den Buchstaben 5-mal auf Papier",
        "fr": "Écris la lettre 5 fois sur du papier",
        "tr": "Harfi kağıda 5 kez yaz",
        "ru": "Напиши букву 5 раз на бумаге",
        "sv": "Skriv bokstaven 5 gånger på papper",
        "nl": "Schrijf de letter 5 keer op papier",
        "el": "Γράψε το γράμμα 5 φορές σε χαρτί",
    },
    "tip_say_word": {
        "ar": "انطق الكلمة بصوت عالٍ",
        "en": "Say the word out loud",
        "de": "Sprich das Wort laut aus",
        "de-AT": "Sprich das Wort laut aus",
        "fr": "Dis le mot à voix haute",
        "tr": "Kelimeyi yüksek sesle söyle",
        "ru": "Произнеси слово вслух",
        "sv": "Säg ordet högt",
        "nl": "Zeg het woord hardop",
        "el": "Πες τη λέξη δυνατά",
    },
    "tip_repeat_sentence": {
        "ar": "ردّد الجملة كاملة",
        "en": "Repeat the full sentence",
        "de": "Wiederhole den ganzen Satz",
        "de-AT": "Wiederhole den ganzen Satz",
        "fr": "Répète la phrase entière",
        "tr": "Cümlenin tamamını tekrarla",
        "ru": "Повтори всё предложение",
        "sv": "Upprepa hela meningen",
        "nl": "Herhaal de hele zin",
        "el": "Επανάλαβε ολόκληρη την πρόταση",
    },
    "tip_write_sentence_3": {
        "ar": "اكتب الجملة ٣ مرات",
        "en": "Write the sentence 3 times",
        "de": "Schreibe den Satz 3-mal",
        "de-AT": "Schreib den Satz 3-mal",
        "fr": "Écris la phrase 3 fois",
        "tr": "Cümleyi 3 kez yaz",
        "ru": "Напиши предложение 3 раза",
        "sv": "Skriv meningen 3 gånger",
        "nl": "Schrijf de zin 3 keer",
        "el": "Γράψε την πρόταση 3 φορές",
    },
    "tip_read_3_memory": {
        "ar": "اقرأ ٣ مرات ثم ردّد من الذاكرة",
        "en": "Read 3 times then repeat from memory",
        "de": "Lies 3-mal, dann wiederhole aus dem Gedächtnis",
        "de-AT": "Lies 3-mal, dann wiederhole auswendig",
        "fr": "Lis 3 fois puis répète de mémoire",
        "tr": "3 kez oku, sonra ezberden tekrarla",
        "ru": "Прочитай 3 раза, затем повтори по памяти",
        "sv": "Läs 3 gånger, upprepa sedan ur minnet",
        "nl": "Lees 3 keer, herhaal dan uit het geheugen",
        "el": "Διάβασε 3 φορές, μετά επανάλαβε απ' έξω",
    },
    "tip_repeat_dua_5": {
        "ar": "ردّد الدعاء ٥ مرات",
        "en": "Repeat the dua 5 times",
        "de": "Wiederhole das Dua 5-mal",
        "de-AT": "Wiederhole das Dua 5-mal",
        "fr": "Répète le dua 5 fois",
        "tr": "Duayı 5 kez tekrarla",
        "ru": "Повтори дуа 5 раз",
        "sv": "Upprepa dua 5 gånger",
        "nl": "Herhaal de dua 5 keer",
        "el": "Επανάλαβε το ντουά 5 φορές",
    },
    "tip_close_eyes_recite": {
        "ar": "أغلق عينيك وسمّع الآية",
        "en": "Close your eyes and recite the ayah",
        "de": "Schließe die Augen und sage den Vers auf",
        "de-AT": "Schließ die Augen und sag den Vers auf",
        "fr": "Ferme les yeux et récite le verset",
        "tr": "Gözlerini kapat ve ayeti oku",
        "ru": "Закрой глаза и произнеси аят",
        "sv": "Blunda och recitera versen",
        "nl": "Sluit je ogen en reciteer het vers",
        "el": "Κλείσε τα μάτια σου και απάγγειλε το εδάφιο",
    },
    "tip_apply_hadith": {
        "ar": "فكّر كيف تطبّق هذا الحديث في حياتك",
        "en": "Think about how to apply this hadith in your life",
        "de": "Denke darüber nach, wie du diesen Hadith in deinem Leben anwenden kannst",
        "de-AT": "Denk darüber nach, wie du diesen Hadith in deinem Leben anwenden kannst",
        "fr": "Réfléchis à comment appliquer ce hadith dans ta vie",
        "tr": "Bu hadisi hayatında nasıl uygulayabileceğini düşün",
        "ru": "Подумай, как применить этот хадис в своей жизни",
        "sv": "Tänk på hur du kan tillämpa denna hadith i ditt liv",
        "nl": "Denk na over hoe je deze hadith in je leven kunt toepassen",
        "el": "Σκέψου πώς να εφαρμόσεις αυτό το χαντίθ στη ζωή σου",
    },
    "tip_learn_grammar": {
        "ar": "تعلّم قواعد جديدة",
        "en": "Learn new grammar rules",
        "de": "Lerne neue Grammatikregeln",
        "de-AT": "Lern neue Grammatikregeln",
        "fr": "Apprends de nouvelles règles de grammaire",
        "tr": "Yeni gramer kurallarını öğren",
        "ru": "Изучи новые правила грамматики",
        "sv": "Lär dig nya grammatikregler",
        "nl": "Leer nieuwe grammaticaregels",
        "el": "Μάθε νέους κανόνες γραμματικής",
    },
    "tip_review_all": {
        "ar": "راجع كل ما تعلّمته!",
        "en": "Review everything you learned!",
        "de": "Wiederhole alles, was du gelernt hast!",
        "de-AT": "Wiederhole alles, was du gelernt hast!",
        "fr": "Révise tout ce que tu as appris !",
        "tr": "Öğrendiğin her şeyi tekrarla!",
        "ru": "Повтори всё, что ты выучил!",
        "sv": "Gå igenom allt du har lärt dig!",
        "nl": "Herhaal alles wat je hebt geleerd!",
        "el": "Επανάλαβε όλα όσα έμαθες!",
    },
    # Quiz Questions
    "quiz_which_letter_sounds": {
        "ar": "أي حرف صوته {sound}؟",
        "en": "Which letter sounds like {sound}?",
        "de": "Welcher Buchstabe klingt wie {sound}?",
        "de-AT": "Welcher Buchstabe klingt wie {sound}?",
        "fr": "Quelle lettre fait le son {sound} ?",
        "tr": "Hangi harf {sound} gibi ses çıkarır?",
        "ru": "Какая буква звучит как {sound}?",
        "sv": "Vilken bokstav låter som {sound}?",
        "nl": "Welke letter klinkt als {sound}?",
        "el": "Ποιο γράμμα ακούγεται σαν {sound};",
    },
    "quiz_letter_name": {
        "ar": "ما اسم هذا الحرف: {letter}؟",
        "en": "What is the name of this letter: {letter}?",
        "de": "Wie heißt dieser Buchstabe: {letter}?",
        "de-AT": "Wie heißt dieser Buchstabe: {letter}?",
        "fr": "Quel est le nom de cette lettre : {letter} ?",
        "tr": "Bu harfin adı nedir: {letter}?",
        "ru": "Как называется эта буква: {letter}?",
        "sv": "Vad heter denna bokstav: {letter}?",
        "nl": "Hoe heet deze letter: {letter}?",
        "el": "Πώς ονομάζεται αυτό το γράμμα: {letter};",
    },
    "quiz_what_number": {
        "ar": "ما هذا العدد: {number}؟",
        "en": "What number is this: {number}?",
        "de": "Welche Zahl ist das: {number}?",
        "de-AT": "Welche Zahl ist das: {number}?",
        "fr": "Quel est ce nombre : {number} ?",
        "tr": "Bu hangi sayı: {number}?",
        "ru": "Какое это число: {number}?",
        "sv": "Vilket tal är detta: {number}?",
        "nl": "Welk getal is dit: {number}?",
        "el": "Ποιος αριθμός είναι αυτός: {number};",
    },
    "quiz_what_in_arabic": {
        "ar": "ما معنى {emoji} بالعربية؟",
        "en": "What is {emoji} in Arabic?",
        "de": "Was ist {emoji} auf Arabisch?",
        "de-AT": "Was ist {emoji} auf Arabisch?",
        "fr": "Comment dit-on {emoji} en arabe ?",
        "tr": "Arapça {emoji} ne demek?",
        "ru": "Как будет {emoji} по-арабски?",
        "sv": "Vad är {emoji} på arabiska?",
        "nl": "Wat is {emoji} in het Arabisch?",
        "el": "Πώς λέγεται {emoji} στα αραβικά;",
    },
    # Category names for vocabulary
    "cat_colors": {
        "ar": "ألوان", "en": "Colors", "de": "Farben", "de-AT": "Farben",
        "fr": "Couleurs", "tr": "Renkler", "ru": "Цвета",
        "sv": "Färger", "nl": "Kleuren", "el": "Χρώματα",
    },
    "cat_animals": {
        "ar": "حيوانات", "en": "Animals", "de": "Tiere", "de-AT": "Tiere",
        "fr": "Animaux", "tr": "Hayvanlar", "ru": "Животные",
        "sv": "Djur", "nl": "Dieren", "el": "Ζώα",
    },
    "cat_family": {
        "ar": "عائلة", "en": "Family", "de": "Familie", "de-AT": "Familie",
        "fr": "Famille", "tr": "Aile", "ru": "Семья",
        "sv": "Familj", "nl": "Familie", "el": "Οικογένεια",
    },
    "cat_body": {
        "ar": "جسم", "en": "Body", "de": "Körper", "de-AT": "Körper",
        "fr": "Corps", "tr": "Vücut", "ru": "Тело",
        "sv": "Kropp", "nl": "Lichaam", "el": "Σώμα",
    },
    "cat_food": {
        "ar": "طعام", "en": "Food", "de": "Essen", "de-AT": "Essen",
        "fr": "Nourriture", "tr": "Yiyecek", "ru": "Еда",
        "sv": "Mat", "nl": "Eten", "el": "Φαγητό",
    },
    "cat_home": {
        "ar": "بيت", "en": "Home", "de": "Haus", "de-AT": "Haus",
        "fr": "Maison", "tr": "Ev", "ru": "Дом",
        "sv": "Hem", "nl": "Huis", "el": "Σπίτι",
    },
    "cat_nature": {
        "ar": "طبيعة", "en": "Nature", "de": "Natur", "de-AT": "Natur",
        "fr": "Nature", "tr": "Doğa", "ru": "Природа",
        "sv": "Natur", "nl": "Natuur", "el": "Φύση",
    },
    "cat_school": {
        "ar": "مدرسة", "en": "School", "de": "Schule", "de-AT": "Schule",
        "fr": "École", "tr": "Okul", "ru": "Школа",
        "sv": "Skola", "nl": "School", "el": "Σχολείο",
    },
    "cat_greetings": {
        "ar": "تحيات", "en": "Greetings", "de": "Begrüßungen", "de-AT": "Begrüßungen",
        "fr": "Salutations", "tr": "Selamlaşma", "ru": "Приветствия",
        "sv": "Hälsningar", "nl": "Begroetingen", "el": "Χαιρετισμοί",
    },
    # Lesson & Memorize prefixes
    "memorize_prefix": {
        "ar": "حفظ: {name}",
        "en": "Memorize: {name}",
        "de": "Auswendig lernen: {name}",
        "de-AT": "Auswendig lernen: {name}",
        "fr": "Mémorise : {name}",
        "tr": "Ezberle: {name}",
        "ru": "Запомни: {name}",
        "sv": "Memorera: {name}",
        "nl": "Onthoud: {name}",
        "el": "Απομνημόνευσε: {name}",
    },
    "lesson_prefix": {
        "ar": "درس {num}",
        "en": "Lesson {num}",
        "de": "Lektion {num}",
        "de-AT": "Lektion {num}",
        "fr": "Leçon {num}",
        "tr": "Ders {num}",
        "ru": "Урок {num}",
        "sv": "Lektion {num}",
        "nl": "Les {num}",
        "el": "Μάθημα {num}",
    },
    "letter_prefix": {
        "ar": "حرف {name}",
        "en": "Letter {name}",
        "de": "Buchstabe {name}",
        "de-AT": "Buchstabe {name}",
        "fr": "Lettre {name}",
        "tr": "Harf {name}",
        "ru": "Буква {name}",
        "sv": "Bokstav {name}",
        "nl": "Letter {name}",
        "el": "Γράμμα {name}",
    },
    # ==================== GAMIFICATION STRINGS ====================
    # Mosque Building Stages (Kids)
    "mosque_foundation": {
        "ar": "الأساس", "en": "Foundation", "de": "Fundament", "de-AT": "Fundament",
        "fr": "Fondation", "tr": "Temel", "ru": "Фундамент",
        "sv": "Grund", "nl": "Fundament", "el": "Θεμέλιο",
    },
    "mosque_walls": {
        "ar": "الجدران", "en": "Walls", "de": "Mauern", "de-AT": "Mauern",
        "fr": "Murs", "tr": "Duvarlar", "ru": "Стены",
        "sv": "Väggar", "nl": "Muren", "el": "Τοίχοι",
    },
    "mosque_pillars": {
        "ar": "الأعمدة", "en": "Pillars", "de": "Säulen", "de-AT": "Säulen",
        "fr": "Piliers", "tr": "Sütunlar", "ru": "Колонны",
        "sv": "Pelare", "nl": "Pilaren", "el": "Κολόνες",
    },
    "mosque_dome_base": {
        "ar": "قاعدة القبة", "en": "Dome Base", "de": "Kuppelbasis", "de-AT": "Kuppelbasis",
        "fr": "Base du dôme", "tr": "Kubbe Tabanı", "ru": "Основание купола",
        "sv": "Kupolbas", "nl": "Koepelbasis", "el": "Βάση τρούλου",
    },
    "mosque_dome": {
        "ar": "القبة", "en": "Dome", "de": "Kuppel", "de-AT": "Kuppel",
        "fr": "Dôme", "tr": "Kubbe", "ru": "Купол",
        "sv": "Kupol", "nl": "Koepel", "el": "Τρούλος",
    },
    "mosque_minaret": {
        "ar": "المئذنة", "en": "Minaret", "de": "Minarett", "de-AT": "Minarett",
        "fr": "Minaret", "tr": "Minare", "ru": "Минарет",
        "sv": "Minaret", "nl": "Minaret", "el": "Μιναρές",
    },
    "mosque_garden": {
        "ar": "الحديقة", "en": "Garden", "de": "Garten", "de-AT": "Garten",
        "fr": "Jardin", "tr": "Bahçe", "ru": "Сад",
        "sv": "Trädgård", "nl": "Tuin", "el": "Κήπος",
    },
    "mosque_golden_dome": {
        "ar": "القبة الذهبية", "en": "Golden Dome", "de": "Goldene Kuppel", "de-AT": "Goldene Kuppel",
        "fr": "Dôme doré", "tr": "Altın Kubbe", "ru": "Золотой купол",
        "sv": "Gyllene kupol", "nl": "Gouden koepel", "el": "Χρυσός τρούλος",
    },
    "mosque_complete": {
        "ar": "المسجد المكتمل", "en": "Complete Mosque", "de": "Vollständige Moschee", "de-AT": "Vollständige Moschee",
        "fr": "Mosquée complète", "tr": "Tamamlanmış Cami", "ru": "Готовая мечеть",
        "sv": "Komplett moské", "nl": "Complete moskee", "el": "Ολοκληρωμένο τζαμί",
    },
    # Spiritual Ranks (Adults - Blessing Points)
    "rank_seeker": {
        "ar": "باحث", "en": "Seeker", "de": "Suchender", "de-AT": "Suchender",
        "fr": "Chercheur", "tr": "Arayan", "ru": "Искатель",
        "sv": "Sökare", "nl": "Zoeker", "el": "Αναζητητής",
    },
    "rank_learner": {
        "ar": "متعلم", "en": "Learner", "de": "Lernender", "de-AT": "Lernender",
        "fr": "Apprenant", "tr": "Öğrenci", "ru": "Ученик",
        "sv": "Elev", "nl": "Leerling", "el": "Μαθητής",
    },
    "rank_devoted": {
        "ar": "متفانٍ", "en": "Devoted", "de": "Hingebungsvoll", "de-AT": "Hingebungsvoll",
        "fr": "Dévoué", "tr": "Adanmış", "ru": "Преданный",
        "sv": "Hängiven", "nl": "Toegewijd", "el": "Αφοσιωμένος",
    },
    "rank_steadfast": {
        "ar": "ثابت", "en": "Steadfast", "de": "Standhaft", "de-AT": "Standhaft",
        "fr": "Constant", "tr": "Kararlı", "ru": "Стойкий",
        "sv": "Ståndaktig", "nl": "Standvastig", "el": "Σταθερός",
    },
    "rank_knowledgeable": {
        "ar": "عالِم", "en": "Knowledgeable", "de": "Wissend", "de-AT": "Wissend",
        "fr": "Savant", "tr": "Bilgili", "ru": "Знающий",
        "sv": "Kunnig", "nl": "Geleerd", "el": "Γνώστης",
    },
    "rank_hafiz": {
        "ar": "حافظ", "en": "Hafiz", "de": "Hafiz", "de-AT": "Hafiz",
        "fr": "Hafiz", "tr": "Hafız", "ru": "Хафиз",
        "sv": "Hafiz", "nl": "Hafiz", "el": "Χαφίζ",
    },
    "rank_mumin": {
        "ar": "مؤمن", "en": "Mumin", "de": "Mumin", "de-AT": "Mumin",
        "fr": "Moumin", "tr": "Mümin", "ru": "Мумин",
        "sv": "Mumin", "nl": "Mumin", "el": "Μουμίν",
    },
    "rank_muhsin": {
        "ar": "محسن", "en": "Muhsin", "de": "Muhsin", "de-AT": "Muhsin",
        "fr": "Mouhsin", "tr": "Muhsin", "ru": "Мухсин",
        "sv": "Muhsin", "nl": "Muhsin", "el": "Μουχσίν",
    },
    "rank_muttaqin": {
        "ar": "متقي", "en": "Muttaqin", "de": "Muttaqin", "de-AT": "Muttaqin",
        "fr": "Mouttaqin", "tr": "Müttaki", "ru": "Муттакин",
        "sv": "Muttaqin", "nl": "Muttaqin", "el": "Μουττακίν",
    },
    # Points & Rewards UI
    "golden_bricks": {
        "ar": "الطوب الذهبي", "en": "Golden Bricks", "de": "Goldene Ziegel", "de-AT": "Goldene Ziegel",
        "fr": "Briques dorées", "tr": "Altın Tuğlalar", "ru": "Золотые кирпичи",
        "sv": "Gyllene tegelstenar", "nl": "Gouden bakstenen", "el": "Χρυσά τούβλα",
    },
    "blessing_points": {
        "ar": "نقاط البركة", "en": "Blessing Points", "de": "Segenspunkte", "de-AT": "Segenspunkte",
        "fr": "Points de bénédiction", "tr": "Bereket Puanları", "ru": "Очки благословения",
        "sv": "Välsignelsepoäng", "nl": "Zegenpunten", "el": "Πόντοι ευλογίας",
    },
    "watch_ad_earn": {
        "ar": "شاهد إعلاناً واكسب {points} نقطة",
        "en": "Watch an ad and earn {points} points",
        "de": "Sieh dir eine Anzeige an und verdiene {points} Punkte",
        "de-AT": "Schau dir eine Anzeige an und verdien {points} Punkte",
        "fr": "Regarde une pub et gagne {points} points",
        "tr": "Reklam izle ve {points} puan kazan",
        "ru": "Посмотри рекламу и получи {points} очков",
        "sv": "Titta på en annons och tjäna {points} poäng",
        "nl": "Bekijk een advertentie en verdien {points} punten",
        "el": "Δες μια διαφήμιση και κέρδισε {points} πόντους",
    },
    "parental_gate_title": {
        "ar": "بوابة الأمان الأبوية",
        "en": "Parental Safety Gate",
        "de": "Elterliche Sicherheitssperre",
        "de-AT": "Elterliche Sicherheitssperre",
        "fr": "Portail de sécurité parentale",
        "tr": "Ebeveyn Güvenlik Kapısı",
        "ru": "Родительский шлюз безопасности",
        "sv": "Föräldrasäkerhetsgrind",
        "nl": "Ouderlijke veiligheidspoort",
        "el": "Πύλη γονικής ασφάλειας",
    },
    "parental_gate_hint": {
        "ar": "اطلب من والديك حل هذه المسألة",
        "en": "Ask your parents to solve this",
        "de": "Bitte deine Eltern, dies zu lösen",
        "de-AT": "Bitt deine Eltern, das zu lösen",
        "fr": "Demande à tes parents de résoudre ceci",
        "tr": "Ebeveynlerinden bunu çözmelerini iste",
        "ru": "Попроси родителей решить эту задачу",
        "sv": "Be dina föräldrar lösa detta",
        "nl": "Vraag je ouders om dit op te lossen",
        "el": "Ζήτησε από τους γονείς σου να το λύσουν",
    },
    "daily_streak": {
        "ar": "سلسلة يومية: {days} يوم",
        "en": "Daily streak: {days} days",
        "de": "Tägliche Serie: {days} Tage",
        "de-AT": "Tägliche Serie: {days} Tage",
        "fr": "Série quotidienne : {days} jours",
        "tr": "Günlük seri: {days} gün",
        "ru": "Ежедневная серия: {days} дней",
        "sv": "Daglig serie: {days} dagar",
        "nl": "Dagelijkse reeks: {days} dagen",
        "el": "Ημερήσιο σερί: {days} ημέρες",
    },
    "leaderboard": {
        "ar": "لوحة المتصدرين", "en": "Leaderboard", "de": "Bestenliste", "de-AT": "Bestenliste",
        "fr": "Classement", "tr": "Liderlik Tablosu", "ru": "Таблица лидеров",
        "sv": "Topplista", "nl": "Ranglijst", "el": "Πίνακας κατάταξης",
    },
    "premium_content": {
        "ar": "محتوى متميز", "en": "Premium Content", "de": "Premium-Inhalt", "de-AT": "Premium-Inhalt",
        "fr": "Contenu premium", "tr": "Premium İçerik", "ru": "Премиум-контент",
        "sv": "Premiuminnehåll", "nl": "Premium-inhoud", "el": "Premium περιεχόμενο",
    },
    "unlock_with_bricks": {
        "ar": "افتح بـ {cost} طوبة ذهبية",
        "en": "Unlock with {cost} golden bricks",
        "de": "Freischalten mit {cost} goldenen Ziegeln",
        "de-AT": "Freischalten mit {cost} goldenen Ziegeln",
        "fr": "Débloquer avec {cost} briques dorées",
        "tr": "{cost} altın tuğla ile aç",
        "ru": "Открыть за {cost} золотых кирпичей",
        "sv": "Lås upp med {cost} gyllene tegelstenar",
        "nl": "Ontgrendel met {cost} gouden bakstenen",
        "el": "Ξεκλείδωσε με {cost} χρυσά τούβλα",
    },
    "unlock_with_ad": {
        "ar": "افتح بمشاهدة إعلان",
        "en": "Unlock by watching an ad",
        "de": "Freischalten durch Ansehen einer Anzeige",
        "de-AT": "Freischalten durch Anschauen einer Anzeige",
        "fr": "Débloquer en regardant une pub",
        "tr": "Reklam izleyerek aç",
        "ru": "Открыть просмотром рекламы",
        "sv": "Lås upp genom att titta på en annons",
        "nl": "Ontgrendel door een advertentie te bekijken",
        "el": "Ξεκλείδωσε βλέποντας μια διαφήμιση",
    },
    "ad_limit_reached": {
        "ar": "وصلت للحد الأقصى من الإعلانات اليوم",
        "en": "You reached today's ad limit",
        "de": "Du hast das Anzeigenlimit für heute erreicht",
        "de-AT": "Du hast das Anzeigenlimit für heute erreicht",
        "fr": "Tu as atteint la limite de pubs d'aujourd'hui",
        "tr": "Bugünkü reklam limitine ulaştın",
        "ru": "Ты достиг лимита рекламы на сегодня",
        "sv": "Du har nått dagens annonsgräns",
        "nl": "Je hebt de advertentielimiet van vandaag bereikt",
        "el": "Έφτασες το όριο διαφημίσεων για σήμερα",
    },
}


def t(key: str, lang: str, **kwargs) -> str:
    """
    Get translated string for the given key and locale.
    Falls back: de-AT -> de -> ar (NO English fallback).
    Supports {placeholder} substitution via kwargs.
    """
    entry = L10N.get(key)
    if not entry:
        return key

    # Locale fallback chain: exact -> base -> ar -> key (NO English fallback)
    text = entry.get(lang)
    if text is None and "-" in lang:
        text = entry.get(lang.split("-")[0])
    if text is None:
        text = entry.get("ar", key)

    # Substitute placeholders
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, IndexError):
            pass
    return text


def get_cat_name(cat: str, lang: str) -> str:
    """Get localized category name."""
    return t(f"cat_{cat}", lang)
