#!/usr/bin/env python3
"""Greek (el) translations for Azan & Hikaya app"""
import json, os

EL = {
  "calendar": "Ημερολόγιο", "tracker": "Παρακολούθηση προσευχής",
  "timeRemaining": "Υπολειπόμενος χρόνος", "today": "Σήμερα",
  "hijriDate": "Ημερομηνία Χίτζρα", "detectLocation": "Εντοπισμός τοποθεσίας",
  "quickAccess": "Γρήγορη πρόσβαση", "distanceToMakkah": "Απόσταση από τη Μέκκα",
  "bookmarks": "Σελιδοδείκτες", "count": "Αριθμός", "total": "Σύνολο",
  "morningAdhkar": "Πρωινά Adhkar", "eveningAdhkar": "Βραδινά Adhkar",
  "completed": "Ολοκληρώθηκε", "days": "Ημέρες",
  "zakatCalculator": "Υπολογιστής Ζακάτ", "noResults": "Κανένα αποτέλεσμα",
  "loginPrompt": "Συνδεθείτε για να αποθηκεύσετε την πρόοδό σας",
  "loginSignup": "Σύνδεση / Εγγραφή", "loginWithGoogle": "Σύνδεση με Google",
  "name": "Όνομα", "email": "Email", "password": "Κωδικός",
  "signup": "Εγγραφή", "noAccount": "Δεν έχετε λογαριασμό;",
  "hasAccount": "Έχετε ήδη λογαριασμό;",
  "yourIslamicApp": "Η ολοκληρωμένη ισλαμική σας εφαρμογή",
  "loginSuccess": "Επιτυχής σύνδεση",
  "signupSuccess": "Λογαριασμός δημιουργήθηκε! Ελέγξτε το email σας",
  "addedToFavorites": "Προστέθηκε στα αγαπημένα",
  "removedFromFavorites": "Αφαιρέθηκε από τα αγαπημένα",
  "loginToSave": "Συνδεθείτε για αποθήκευση αγαπημένων",
  "languageChanged": "Η γλώσσα άλλαξε", "ayahs": "Αγιάτ",
  "ramadanCountdown": "Αντίστροφη μέτρηση Ραμαζανιού",
  "daysRemaining": "Υπολειπόμενες ημέρες",
  "upcomingEvents": "Επερχόμενα γεγονότα",
  "newYear": "Ισλαμική Πρωτοχρονιά", "ashura": "Ημέρα Ασούρα",
  "israMiraj": "Ισρά και Μιράτζ", "shaabanMid": "Νύχτα μέσου Σα'μπάν",
  "ramadanStart": "Αρχή Ραμαζανιού", "hajjStart": "Αρχή Χατζ",
  "dayArafah": "Ημέρα Αραφάτ",
  "cashBalance": "Μετρητά και τραπεζικό υπόλοιπο",
  "goldValue": "Αξία χρυσού", "silverValue": "Αξία ασημιού",
  "stocksInvestments": "Μετοχές και επενδύσεις",
  "debtsOwed": "Χρέη προς εσάς", "calculateZakat": "Υπολογισμός Ζακάτ",
  "yourZakat": "Η Ζακάτ σας (2,5%)",
  "belowNisab": "Η περιουσία σας είναι κάτω από το Νισάμπ",
  "revelationMeccan": "Μεκκανικό", "revelationMedinan": "Μεδινικό",
  "notificationsEnabled": "Ειδοποιήσεις Αζάν ενεργοποιήθηκαν 🔔",
  "notificationsDisabled": "Ειδοποιήσεις Αζάν απενεργοποιήθηκαν",
  "notificationsDenied": "Δεν επιτράπηκαν ειδοποιήσεις",
  "loginToSaveBookmarks": "Συνδεθείτε για αποθήκευση σελιδοδεικτών",
  "surahAddedToFav": "Σούρα προστέθηκε στα αγαπημένα",
  "surahRemovedFromFav": "Σούρα αφαιρέθηκε από τα αγαπημένα",
  "loginToSaveProgress": "Συνδεθείτε για αποθήκευση προόδου",
  "sunday": "Κυρ", "monday": "Δευ", "tuesday": "Τρί", "wednesday": "Τετ",
  "thursday": "Πέμ", "friday": "Παρ", "saturday": "Σάβ",
  "qiblaFromNorth": "από βορρά", "qiblaFromEast": "από ανατολή",
  "qiblaFromSouth": "από νότο", "qiblaFromWest": "από δύση",
  "duasAndDhikr": "Ντουά και Dhikr", "daily": "Καθημερινά",
  "otherDuas": "Λοιπά", "occasional": "Περιστασιακά",
  "subCategories": "ενότητες", "totalDuas": "ντουά",
  "duaSubBeforeSleep": "Πριν τον ύπνο", "duaSubAfterWakeUp": "Μετά το ξύπνημα",
  "duaSubNightmare": "Σε εφιάλτες", "duaSubBeforeWudu": "Πριν το Ουντού",
  "duaSubAfterWudu": "Μετά το Ουντού", "duaSubEnteringMosque": "Είσοδος στο τζαμί",
  "duaSubLeavingMosque": "Αποχώρηση από τζαμί",
  "duaSubOpeningSalah": "Άνοιγμα προσευχής", "duaSubDuringSalah": "Κατά την προσευχή",
  "duaSubAfterSalah": "Μετά την προσευχή", "duaSubEnteringHome": "Είσοδος στο σπίτι",
  "duaSubLeavingHome": "Αποχώρηση από σπίτι", "duaSubWearingNew": "Νέα ρούχα",
  "duaSubRemovingClothes": "Αφαίρεση ρούχων",
  "duaSubSeeingSomeoneNew": "Βλέποντας κάποιον με νέα ρούχα",
  "duaSubStartTravel": "Αρχή ταξιδιού", "duaSubReturnTravel": "Επιστροφή από ταξίδι",
  "duaSubRidingVehicle": "Σε όχημα",
  "duaSubBeforeEating": "Πριν το φαγητό", "duaSubAfterEating": "Μετά το φαγητό",
  "duaSubDrinking": "Κατά το πιοτό", "duaSubGuestFood": "Ως φιλοξενούμενος",
  "duaSubMorningAdhkar": "Πρωινά Adhkar", "duaSubEveningAdhkar": "Βραδινά Adhkar",
  "duaSubGeneralDhikr": "Γενικό Dhikr", "duaSubProtectionAdhkar": "Adhkar Προστασίας",
  "duaSubSalawat": "Σαλαγουάτ στον Προφήτη",
  "duaSubImmediateAfter": "Αμέσως μετά την προσευχή",
  "duaSubTasbeehAfter": "Τασμπίχ μετά την προσευχή",
  "duaSubAskingRizq": "Αίτηση προνοίας", "duaSubSeekingKnowledge": "Αναζήτηση γνώσης",
  "duaSubBeforeExam": "Πριν τις εξετάσεις",
  "duaSubStrengtheningFaith": "Ενδυνάμωση πίστης",
  "duaSubProtectionHereafter": "Προστασία στη μετέπειτα ζωή",
  "duaSubSeekingForgiveness": "Αναζήτηση συγχώρεσης",
  "duaSubPraisingAllah": "Δοξολογία Αλλάχ",
  "duaSubForChildren": "Για παιδιά", "duaSubForParents": "Για γονείς",
  "duaSubForSpouse": "Για σύζυγο", "duaSubWhenSick": "Κατά την ασθένεια",
  "duaSubVisitingSick": "Επίσκεψη ασθενών",
  "duaSubWhenAfflicted": "Σε δοκιμασία", "duaSubAnxietyRelief": "Ανακούφιση άγχους",
  "duaSubHappiness": "Ευτυχία", "duaSubAskingPatience": "Αίτηση υπομονής",
  "duaSubPayingDebt": "Εξόφληση χρέους",
  "duaSubDhikrDuringPeriod": "Dhikr κατά την έμμηνο",
  "duaSubFuneralPrayer": "Κηδειοπροσευχή", "duaSubCondolences": "Συλλυπητήρια",
  "duaSubVisitingGrave": "Επίσκεψη τάφων",
  "duaSubSaiBetween": "Σα'ι μεταξύ Σαφά και Μαρουά",
  "duaSubArafat": "Ημέρα Αραφάτ",
  "duaSubWhenRaining": "Κατά τη βροχή", "duaSubThunderStorm": "Καταιγίδα",
  "duaSubWhenWindy": "Κατά τον άνεμο", "duaSubGoodCharacter": "Καλός χαρακτήρας",
  "duaSubMakingDecision": "Λήψη αποφάσεων",
  "quickQuran": "Κοράνι", "quickDuas": "Ντουά", "quickStories": "Ιστορίες",
  "nextPrayerLabel": "Επόμενη προσευχή", "prayerTracking": "Παρακολούθηση προσευχής",
  "athanLabel": "Αζάν", "enableLocation": "Ενεργοποίηση τοποθεσίας",
  "mosqueTimes": "Ώρες τζαμιού", "chooseNearbyMosque": "Επιλογή κοντινού τζαμιού",
  "moreLabel": "Περισσότερα", "liveLabel": "Ζωντανά",
  "unlinkMosque": "Αποσύνδεση", "mosqueUnlinked": "Τζαμί αποσυνδέθηκε",
  "ramadanChallenge": "Πρόκληση Ραμαζανιού", "duaOfDay": "Ντουά της ημέρας",
  "readWithTranslation": "Διαβάστε με μετάφραση",
  "quranCompletion": "📖 Ολοκλήρωση Κορανίου",
  "startDailyRecitation": "Ξεκινήστε καθημερινή ανάγνωση",
  "setYourPace": "Ορίστε τον ρυθμό σας και λάβετε καθημερινές υπενθυμίσεις",
  "setQuranGoal": "Ορίστε στόχο Κορανίου →",
  "hijriCalendarTitle": "Ημερολόγιο Χίτζρα", "quickAccessLabel": "Γρήγορη πρόσβαση",
  "catSleep": "Ύπνος", "catWudu": "Ουντού", "catMosque": "Τζαμί",
  "catSalah": "Προσευχή", "catHome": "Σπίτι", "catClothes": "Ρούχα",
  "catTravel": "Ταξίδι", "catFood": "Φαγητό", "catDailyDhikr": "Καθημερινό Dhikr",
  "catDailyRevival": "Καθημερινή ανανέωση", "catAfterPrayer": "Μετά την προσευχή",
  "catRizq": "Πρόνοια", "catKnowledge": "Γνώση", "catFaith": "Πίστη",
  "catJudgment": "Ημέρα Κρίσης", "catForgiveness": "Συγχώρεση",
  "catPraising": "Δοξολογία Αλλάχ", "catFamily": "Οικογένεια",
  "catHealth": "Υγεία / Ασθένεια", "catLoss": "Απώλεια / Αποτυχία",
  "catSadness": "Θλίψη / Χαρά", "catPatience": "Υπομονή",
  "catDebt": "Χρέος", "catMenstruation": "Κατά την περίοδο",
  "catDeceased": "Αποθανόντες", "catHajj": "Χατζ / Ούμρα",
  "catNature": "Φύση", "catGoodManners": "Καλοί τρόποι",
  "catGuidance": "Καθοδήγηση και αποφάσεις",
  "duasSubtitle": "Ντουά και Adhkar από το Κοράνι και τη Σούννα",
  "searchDua": "Αναζήτηση ντουά...", "resultCount": "αποτέλεσμα",
  "noResultsFound": "Δεν βρέθηκαν αποτελέσματα",
  "favoritesLabel": "Αγαπημένα", "noFavoriteDuas": "Κανένα αγαπημένο ντουά ακόμα",
  "sectionsLabel": "Ενότητες",
  "storiesTitle": "📖 Αληθινές ιστορίες",
  "storiesSubtitle": "Μοιραστείτε την ιστορία σας και εμπνεύστε άλλους",
  "yourStoryMayGuide": "Η ιστορία σας μπορεί να καθοδηγήσει κάποιον",
  "shareYourExperience": "Μοιραστείτε την αληθινή σας εμπειρία — κείμενο, βίντεο ή ήχο.\nΟι ιστορίες ελέγχονται πριν τη δημοσίευση.",
  "publishYourStory": "Δημοσιεύστε την ιστορία σας τώρα",
  "loginToPublish": "Συνδεθείτε για δημοσίευση",
  "chooseCategory": "Επιλέξτε κατηγορία", "publishStory": "Δημοσίευση ιστορίας",
  "noStoriesYet": "Δεν υπάρχουν ιστορίες ακόμα",
  "beFirstToShare": "Γίνετε ο πρώτος!",
  "publishFirstStory": "Δημοσιεύστε πρώτη ιστορία",
  "catIstighfar": "Ιστορίες Ιστιγκφάρ", "catSahaba": "Ιστορίες Σαχάμπα",
  "catRuqyahStory": "Ιστορίες Ρουκγιά", "catHawqala": "Ιστορίες Χαουκάλα",
  "catRizqStory": "Ιστορίες Προνοίας",
  "mediaText": "Κείμενο", "mediaVideo": "Βίντεο", "mediaAudio": "Ήχος",
  "ruqyahSubtitle": "Ισλαμική θεραπεία από το Κοράνι και τη Σούννα",
  "ruqyahDisclaimer": "⚠️ Η Ρουκγιά προέρχεται από το Ιερό Κοράνι και την Προφητική Σούννα.\nΑυτή η ενότητα είναι για ακρόαση και προστασία, όχι υποκατάστατο ιατρικής θεραπείας.",
  "ruqyahCount": "ρουκγιά", "noRuqyahYet": "Δεν υπάρχει ρουκγιά σε αυτή την ενότητα",
  "quranSubtitle": "Το Ιερό Κοράνι", "noBookmarksYet": "Δεν υπάρχουν σελιδοδείκτες",
  "loginToSaveBookmarksQuran": "Συνδεθείτε για αποθήκευση σελιδοδεικτών",
  "removedFromBookmarks": "Αφαιρέθηκε από σελιδοδείκτες",
  "addedToBookmarks": "Προστέθηκε στους σελιδοδείκτες",
  "gregorianCalendar": "Γρηγοριανό", "hijriCalendar2": "Χίτζρα",
  "nextMonth": "Επόμενος μήνας", "prevMonth": "Προηγούμενος μήνας",
  "meaningTranslation": "Μετάφραση", "newStory": "Νέο", "allStories": "Όλα",
  "general": "Γενικά", "videos": "Βίντεο", "images": "Εικόνες",
  "textOnly": "Κείμενο", "postStory": "Δημοσίευση",
  "storyTitle": "Τίτλος ιστορίας...", "storyContent": "Γράψτε την ιστορία σας...",
  "selectCategory": "Κατηγορία:", "smartCategory": "Έξυπνη κατηγορία",
  "addImage": "Εικόνα", "addVideo": "Βίντεο", "uploading": "Μεταφόρτωση...",
  "published": "Δημοσιεύτηκε! ✨", "writeTitle": "Γράψτε τίτλο και ιστορία",
  "comments": "Σχόλια", "noComments": "Κανένα σχόλιο",
  "addComment": "Σχολιάστε...", "storyNotFound": "Ιστορία δεν βρέθηκε",
  "saved": "Αποθηκεύτηκε", "unsaved": "Μη αποθηκευμένο",
  "linkCopied": "Σύνδεσμος αντιγράφηκε",
  "noStories": "Καμία ιστορία", "createStory": "Δημιουργία ιστορίας ✨",
  "viewAll": "Προβολή όλων", "morePage": "Περισσότερα",
  "viewProfile": "Προβολή προφίλ", "quickFeatures": "Γρήγορες λειτουργίες",
  "rewards": "Ανταμοιβές", "collectPoints": "Συλλογή πόντων",
  "aiAssistant": "Βοηθός AI", "askAboutReligion": "Ρωτήστε για τη θρησκεία",
  "shop": "Κατάστημα", "featuredItems": "Επιλεγμένα", "marketplace": "Αγορά",
  "islamicProducts": "Ισλαμικά προϊόντα", "helpSupport": "Βοήθεια και υποστήριξη",
  "contactUs": "Επικοινωνία", "rateApp": "Βαθμολόγηση εφαρμογής",
  "inviteFriend": "Πρόσκληση φίλου", "donations": "Δωρεές και βοήθεια",
  "helpNeedy": "Βοηθήστε τους φτωχούς — Προσευχηθείτε για τους γονείς μου",
  "loggedOut": "Αποσυνδεθήκατε", "auto": "Αυτόματο",
  "reminders": "Υπενθυμίσεις", "enabled": "Ενεργοποιημένο",
  "disabled": "Απενεργοποιημένο", "notificationSettings": "Ρυθμίσεις ειδοποιήσεων",
  "fontSize": "Μέγεθος γραμματοσειράς", "athanSound": "Ήχος Αζάν",
  "ruqyahSection": "Ενότητα Ρουκγιά", "explore": "Εξερεύνηση",
  "prayer": "Προσευχή", "gift": "Δώρο", "followUp": "Παρακολούθηση",
  "autoLanguage": "Αυτόματο (Συσκευή)", "manualLanguage": "Χειροκίνητη επιλογή",
  "languageAutoDetected": "Γλώσσα εντοπίστηκε αυτόματα",
  "languageManuallySet": "Γλώσσα ορίστηκε χειροκίνητα",
  "resetToAuto": "Επαναφορά σε αυτόματο",
  "acceptCookies": "Αποδοχή", "rejectCookies": "Απόρριψη",
  "manageCookies": "Διαχείριση cookies", "necessaryCookies": "Απαραίτητα cookies",
  "analyticsCookies": "Cookies ανάλυσης", "savePreferences": "Αποθήκευση προτιμήσεων",
  "welcome": "Καλωσορίσατε", "loginFailed": "Αποτυχία σύνδεσης",
  "connectionError": "Σφάλμα σύνδεσης", "loggingIn": "Σύνδεση...",
  "fillAllFields": "Συμπληρώστε όλα τα πεδία",
  "passwordMinLength": "Ο κωδικός πρέπει να είναι τουλάχιστον 6 χαρακτήρες",
  "wrongCredentials": "Λάθος email ή κωδικός",
  "accountCreated": "Λογαριασμός δημιουργήθηκε",
  "accountCreateError": "Σφάλμα δημιουργίας λογαριασμού",
  "enterEmail": "Εισάγετε email", "resetLinkSent": "Σύνδεσμος επαναφοράς στάλθηκε",
  "forgotPassword": "Ξεχάσατε τον κωδικό",
  "enterEmailToRecover": "Εισάγετε email για ανάκτηση λογαριασμού",
  "sendResetLink": "Αποστολή συνδέσμου", "backToLogin": "Πίσω στη σύνδεση",
  "companionApp": "Ο πνευματικός σας σύντροφος", "newAccount": "Νέος λογαριασμός",
  "continueWith": "Συνέχεια με", "fullName": "Πλήρες όνομα",
  "passwordHint": "Κωδικός (min 6 χαρ.)", "enter": "Σύνδεση",
  "createAccount": "Δημιουργία λογαριασμού", "forgotPasswordQ": "Ξεχάσατε κωδικό;",
  "dontHaveAccount": "Δεν έχετε λογαριασμό;", "haveAccount": "Έχετε ήδη λογαριασμό;",
  "registerNow": "Εγγραφή τώρα", "loginNow": "Σύνδεση τώρα",
  "prayerTimesSource": "Ώρες προσευχής", "prayerTimesCopied": "Ώρες αντιγράφηκαν",
  "mosqueTimes2": "Ώρες τζαμιού", "mosqueUnlinked2": "Τζαμί αποσυνδέθηκε",
  "unlinkLabel": "Αποσύνδεση", "todayPrayerTimes": "Σημερινές ώρες προσευχής",
  "nextPrayerIs": "Επόμενη προσευχή", "timeLeft": "υπολειπόμενο",
  "changeMosque": "Αλλαγή τζαμιού", "chooseYourMosque": "Επιλέξτε τζαμί",
  "searchNearbyMosque": "Αναζήτηση κοντινού τζαμιού",
  "now": "τώρα", "loginFirst": "Συνδεθείτε πρώτα",
  "story": "ιστορία", "shared": "Κοινοποιήθηκε", "pullDown": "Σύρετε κάτω",
  "comment": "Σχόλιο", "uploaded": "Μεταφορτώθηκε",
  "uploadFailed": "Αποτυχία μεταφόρτωσης",
  "aiCategorized": "AI κατηγοριοποίηση", "moreStories": "Περισσότερες ιστορίες",
  "noVideos": "Κανένα βίντεο", "section": "Ενότητα", "storyView": "Ιστορία",
  "views": "προβολές",
  "voiceNotSupported": "Ο browser σας δεν υποστηρίζει φωνητική αναζήτηση",
  "speakNow": "Μιλήστε τώρα... αναζήτηση ιστορίας",
  "voiceNotRecognized": "Φωνή δεν αναγνωρίστηκε, δοκιμάστε ξανά",
  "searchStoryOrAuthor": "Αναζήτηση ιστορίας ή συγγραφέα",
  "saySomethingLike": "Πείτε κάτι σαν",
  "istighfarStoryExample": "Θέλω μια ιστορία για ιστιγκφάρ",
  "mostViewed": "Δημοφιλέστερα", "storiesEveryoneReads": "Ιστορίες που διαβάζουν όλοι",
  "showLess": "Λιγότερα", "showMore": "Περισσότερα",
  "mostInteracted": "Περισσότερη αλληλεπίδραση",
  "touchedHearts": "Ιστορίες που άγγιξαν καρδιές",
  "noContentYet": "Δεν υπάρχει περιεχόμενο ακόμα",
  "publishFirstStoryInspire": "Δημοσιεύστε και γίνετε ο πρώτος που θα εμπνεύσει",
  "publishFirst": "Δημοσιεύστε πρώτα", "goBack": "Πίσω",
  "noCommentsYet": "Κανένα σχόλιο ακόμα", "writeComment": "Γράψτε σχόλιο...",
  "result": "αποτέλεσμα", "welcomeUser": "Καλωσορίσατε",
  "loginForProfile": "Συνδεθείτε για το προφίλ σας",
  "user": "Χρήστης", "prophets": "Προφήτες", "companions": "Σαχάμπα",
  "rizq": "Πρόνοια", "repentance": "Μετάνοια", "miracles": "Θαύματα",
  "editProfile": "Επεξεργασία προφίλ", "help": "Βοήθεια",
  "supportHelp": "Υποστήριξη", "thankYouRating": "Ευχαριστούμε!",
  "aboutApp": "Σχετικά", "followers": "ακόλουθοι", "likes": "μου αρέσει",
  "follow": "Ακολούθηση", "myStories": "Οι ιστορίες μου",
  "savedStories": "Αποθηκευμένα", "likedStories": "Αγαπημένα",
  "noStoriesYetProfile": "Δεν υπάρχουν ιστορίες", "assistant": "Βοηθός",
  "rememberAllah": "Μνημονεύστε τον Αλλάχ",
  "resetCounter": "Επαναφορά μετρητή;", "chooseDhikr": "Επιλέξτε dhikr",
  "chooseFromAdhkar": "Επιλέξτε από αυθεντικά adhkar",
  "howToUseCompass": "Πώς χρησιμοποιείτε την πυξίδα",
  "placePhoneFlat": "Τοποθετήστε το τηλέφωνο οριζόντια",
  "onYourPalm": "στην παλάμη σας",
  "awayFromMetals": "Μακριά από μέταλλα και ηλεκτρονικά",
  "headphonesLaptop": "ακουστικά, laptop",
  "calibrateCompass": "Βαθμονόμηση: κινήστε σε σχήμα 8",
  "severalTimes": "αρκετές φορές",
  "turnBodyUntil": "Γυρίστε μέχρι να εμφανιστεί στην κορυφή",
  "turnsGreen": "και γίνει πράσινο", "understood": "Κατάλαβα",
  "tapToActivate": "Πατήστε εδώ για ενεργοποίηση πυξίδας",
  "compassNotAvailable": "Πυξίδα μη διαθέσιμη",
  "compassNotSupported": "Η συσκευή σας δεν υποστηρίζει ψηφιακή πυξίδα. Χρησιμοποιήστε τη γωνία με εξωτερική πυξίδα.",
  "calibrate": "Βαθμονόμηση",
  "lowAccuracy": "Χαμηλή ακρίβεια - βαθμονομήστε κινώντας σε σχήμα 8",
  "locationNotDetected": "Τοποθεσία δεν εντοπίστηκε",
  "thisIsQiblaDirection": "Αυτή είναι η κατεύθυνση της Κίμπλα",
  "highAccuracy": "Υψηλή ακρίβεια", "mediumAccuracy": "Μέτρια ακρίβεια",
  "lowAccuracyCalibrate": "Χαμηλή ακρίβεια - βαθμονομήστε",
  "realEstateCommercial": "Ακίνητα και εμπορική ιδιοκτησία",
  "smartMultiCurrencyCalc": "Έξυπνος πολυνομισματικός υπολογιστής",
  "currency": "Νόμισμα",
  "chooseCurrency": "Επιλέξτε νόμισμα χώρας για υπολογισμό Νισάμπ",
  "detecting": "Εντοπισμός...", "chooseCurrencyBtn": "Επιλέξτε νόμισμα",
  "nisabIn": "Νισάμπ σε", "goldGrams": "Χρυσός (85 γραμμάρια)",
  "silverGrams": "Ασήμι (595 γραμμάρια)", "approvedNisab": "Εγκεκριμένο Νισάμπ",
  "yourAssets": "Περιουσιακά σας στοιχεία",
  "enterAssetValues": "Εισάγετε αξία κάθε τύπου στο επιλεγμένο νόμισμα",
  "calculationDetails": "Λεπτομέρειες υπολογισμού", "totalAssets": "Συνολικά περιουσιακά",
  "zakatRate": "Ποσοστό Ζακάτ", "zakatDue": "Οφειλόμενη Ζακάτ",
  "noZakatDue": "Δεν οφείλεται Ζακάτ",
  "belowNisabMsg": "Η περιουσία σας είναι κάτω από το Νισάμπ",
  "shariaNote": "Ισλαμική σημείωση",
  "zakatNoteText": "Αυτός ο υπολογιστής χρησιμοποιεί το Νισάμπ ασημιού (595g). Το σταθερό ποσοστό Ζακάτ είναι 2,5%.",
  "photoUploaded": "Φωτογραφία μεταφορτώθηκε",
  "photoUploadFailed": "Αποτυχία μεταφόρτωσης φωτογραφίας",
  "uploadError": "Σφάλμα μεταφόρτωσης", "nameRequired": "Απαιτείται όνομα",
  "changesSaved": "Αλλαγές αποθηκεύτηκαν", "saveFailed": "Αποτυχία αποθήκευσης",
  "editProfileTitle": "Επεξεργασία προφίλ",
  "tapCameraToChange": "Πατήστε κάμερα για αλλαγή φωτογραφίας",
  "enterFullName": "Εισάγετε πλήρες όνομα",
  "emailCannotChange": "Το email δεν μπορεί να αλλάξει",
  "newPasswordOptional": "Νέος κωδικός (προαιρετικό)",
  "leaveEmptyNoChange": "Αφήστε κενό αν δεν αλλάζει",
  "minSixChars": "Τουλάχιστον 6 χαρακτήρες", "saveChanges": "Αποθήκευση αλλαγών",
  "islamicAssistant": "Ισλαμικός βοηθός",
  "aiAssistantDesc": "Έξυπνος βοηθός με GPT-5.2 εξειδικευμένος σε ισλαμικά θέματα",
  "poweredBy": "Με τεχνολογία", "free": "Δωρεάν",
  "question": "ερώτηση", "questionsLeft": "υπολειπόμενες",
  "askMeAnything": "Κάντε μια ισλαμική ερώτηση",
  "taraweehRuling": "Ποιος είναι ο κανόνας για το Ταραουίχ;",
  "zakatCalcQuestion": "Πώς υπολογίζω τη Ζακάτ;",
  "pillarsOfIslam": "Ποιοι είναι οι πυλώνες του Ισλάμ;",
  "mosqueEntryDua": "Ντουά εισόδου στο τζαμί",
  "watchVideosForPoints": "Δείτε βίντεο για δωρεάν πόντους",
  "writeYourQuestion": "Γράψτε την ισλαμική σας ερώτηση",
  "dailyCheckIn": "Καθημερινό check-in",
  "dailyCheckInDesc": "Κάντε check-in και κερδίστε ανταμοιβές",
  "complete100Tasbeeh": "Ολοκληρώστε 100 τασμπίχ",
  "quranPage": "Σελίδα Κορανίου", "readQuranPage": "Διαβάστε μια σελίδα Κορανίου",
  "mustLogin": "Πρέπει να συνδεθείτε", "yourBalance": "Υπόλοιπό σας",
  "dayStreak": "Σερί ημερών", "totalEarned": "Σύνολο κερδών",
  "collectRewards": "Συλλέξτε ανταμοιβές", "collect": "Συλλογή",
  "storeSection": "Κατάστημα", "buyWithGold": "Αγοράστε premium με χρυσό",
  "history": "Ιστορικό", "noTransactionsYet": "Καμία συναλλαγή ακόμα",
  "installApp": "Εγκατάσταση εφαρμογής", "athanNotifications": "Ειδοποιήσεις Αζάν",
  "pageNotFound": "Σελίδα δεν βρέθηκε", "backToHome": "Πίσω στην αρχική",
  "messages": "Μηνύματα", "noMessages": "Κανένα μήνυμα ακόμα",
  "navHome": "Αρχική", "navStories": "Ιστορίες μου",
  "navMessages": "Μηνύματα", "navMore": "Περισσότερα",
  "holyMosqueAlt": "Το Ιερό Τζαμί",
  "disableNotifications": "Απενεργοποίηση ειδοποιήσεων",
  "enableNotificationsLabel": "Ενεργοποίηση ειδοποιήσεων",
  "mosqueLabel": "Τζαμί", "fajrLabel": "Φατζρ",
  "ramadanCalendarTitle": "Ημερολόγιο Ραμαζανιού 1447",
  "ramadanCalendarDesc": "Καθημερινά ντουά • Λαϊλάτ αλ-Κάντρ • Σουχούρ και Ιφτάρ",
  "ruqyahAyatKursiDesc": "Για προστασία",
  "ruqyahBaqaraDesc": "Διώχνει δαίμονες",
  "ruqyahMorningDesc": "Προστασία από κάθε κακό",
  "closeBanner": "Κλείσιμο", "islamicOccasion": "Ισλαμική γιορτή",
  "hideDua": "Απόκρυψη Ντουά", "readDuaBtn": "Διαβάστε το Ντουά ✨",
  "hadithOfDay": "Χαντίθ ημέρας", "prophetSaid": "Ο Προφήτης ﷺ είπε:",
  "narratorLabel": "Αφηγητής:", "hadithShareTitle": "📖 Χαντίθ ημέρας",
  "dailyGoalsTitle": "Καθημερινοί στόχοι", "completedLabel": "ολοκληρώθηκαν",
  "goalFasting": "Νηστεία Ραμαζανιού", "goalFastingDesc": "Νηστεύω σήμερα",
  "goalStrengthenFaith": "Ενδυναμώστε την πίστη σας",
  "goalQuranReward": "Ανταμοιβή 1/3 Κορανίου",
  "goalRepentance": "Για μετάνοια και συγχώρεση",
  "goalListenQuran": "Ακούστε το Κοράνι",
  "goalListenQuranDesc": "Τουλάχιστον 15 λεπτά",
  "goalShareIslam": "Πείτε σε κάποιον για το Ισλάμ",
  "goalShareIslamDesc": "Διαδώστε το καλό",
  "suggestedGoalsTitle": "Προτεινόμενοι στόχοι",
  "goalAdded": "Στόχος προστέθηκε!",
  "goalSurahMulk": "Διαβάστε Σούρα Αλ-Μουλκ πριν τον ύπνο",
  "goalNafilah": "Κάντε Ναφίλα προσευχή",
  "goalSadaqah": "Δώστε Σαντάκα",
  "goalMondayFast": "Νηστέψτε Δευτέρα ή Πέμπτη",
  "goalSurahKahf": "Διαβάστε Σούρα Αλ-Κάχφ την Παρασκευή",
  "dontMissPrayer": "Μην χάσετε καμία προσευχή",
  "enableNotifDesc": "Ενεργοποιήστε ειδοποιήσεις για Αζάν",
  "notifSettingsBtn": "Ρυθμίσεις ειδοποιήσεων",
  "quranPlayerTitle": "Αναπαραγωγή Ιερού Κορανίου",
  "quranPlayerLabel": "🎧 Αναπαραγωγή Κορανίου",
  "listenWhileSleep": "🎧 Ακούστε ενώ κοιμάστε",
  "quranPlayerDesc": "Παίξτε οποιαδήποτε Σούρα με επανάληψη",
  "reciterCount": "αναγνώστες", "reciterLabel": "Αναγνώστης",
  "chooseSurah": "Επιλέξτε Σούρα", "searchSurah": "Αναζήτηση Σούρα...",
  "versesCount": "εδάφια", "changeRepeatMode": "Αλλαγή λειτουργίας επανάληψης",
  "nextSurah": "Επόμενη Σούρα", "prevSurah": "Προηγούμενη Σούρα",
  "pauseBtn": "Παύση", "playBtn": "Αναπαραγωγή",
  "repeatCurrentSurah": "🔂 Επανάληψη τρέχουσας Σούρα",
  "repeatAllSurahs": "🔁 Αυτόματη αναπαραγωγή όλων",
  "autoNextSurah": "➡️ Αυτόματη μετάβαση στην επόμενη",
  "audioErrorReciter": "Αδυναμία αναπαραγωγής — δοκιμάστε άλλον αναγνώστη",
  "audioNotAvailable": "Ήχος μη διαθέσιμος — δοκιμάστε άλλον",
  "audioPlayError": "Αδυναμία αναπαραγωγής",
  "locationErrorMsg": "Ενεργοποιήστε τοποθεσία για ώρες προσευχής",
  "gdprTitle": "Συγκατάθεση διαφημίσεων",
  "gdprDesc": "Χρησιμοποιούμε διαφημίσεις για υποστήριξη της εφαρμογής. Βάσει GDPR χρειαζόμαστε τη συγκατάθεσή σας.",
  "gdprCollect": "Τι συλλέγουμε:",
  "gdprCollect1": "Ανώνυμο αναγνωριστικό διαφημίσεων",
  "gdprCollect2": "Τύπος περιεχομένου αλληλεπίδρασης",
  "gdprCollect3": "Βασικά δεδομένα συσκευής",
  "gdprAccept": "Αποδοχή εξατομικευμένων διαφημίσεων",
  "gdprReject": "Μόνο γενικές διαφημίσεις",
  "gdprChangeNote": "Μπορείτε να αλλάξετε ανά πάσα στιγμή στις ρυθμίσεις",
  "permLocationTitle": "Τοποθεσία",
  "permLocationSubtitle": "Για ακριβείς ώρες προσευχής",
  "permLocationBenefit1": "Ακριβείς ώρες για την περιοχή σας",
  "permLocationBenefit2": "Σωστή κατεύθυνση Κίμπλα",
  "permLocationBenefit3": "Βρείτε κοντινά τζαμιά",
  "permLocationBenefit4": "Κατάλληλη μέθοδος υπολογισμού",
  "permNotifTitle": "Ειδοποιήσεις",
  "permNotifSubtitle": "Για ειδοποιήσεις προσευχής και Adhkar",
  "permNotifBenefit1": "Ήχος Αζάν στην ώρα προσευχής",
  "permNotifBenefit2": "Πρωινά και βραδινά Adhkar",
  "permNotifBenefit3": "Υπενθυμίσεις Φατζρ και Κιγιάμ",
  "permNotifBenefit4": "Ειδοποιήσεις ισλαμικών γεγονότων",
  "permAllowBtn": "Επιτρέψτε", "permSkipBtn": "Όχι τώρα", "permLaterBtn": "Αργότερα",
  "permStep": "Βήμα", "shareStory": "Κοινοποίηση ιστορίας",
  "readTime": "λεπτά ανάγνωσης", "featuredContent": "Επιλεγμένο περιεχόμενο",
  "videosCount": "βίντεο", "watchNow": "Δείτε τώρα",
  "verseOfDay": "Εδάφιο ημέρας", "commentsTitle": "Σχόλια",
  "commentFailed": "Αποτυχία αποστολής σχολίου", "deleted": "Διαγράφηκε",
  "cannotDeleteComment": "Δεν μπορεί να διαγραφεί",
  "beFirstToComment": "Σχολιάστε πρώτοι 💬",
  "replyTo": "Απάντηση σε", "replyToPlaceholder": "Απάντηση σε",
  "loginToComment": "Συνδεθείτε για σχολιασμό", "reply": "Απάντηση",
  "deleteBtn": "Διαγραφή",
  "minutesAgo": "{n}λ πριν", "hoursAgo": "{n}ω πριν", "daysAgo": "{n}η πριν",
  "newPost": "Νέα δημοσίευση",
  "writeYourStory": "Μοιραστείτε την ιστορία σας...",
  "addTitle": "Τίτλος (προαιρετικό)",
  "textOption": "Κείμενο", "imageOption": "Εικόνα", "videoOption": "Βίντεο",
  "linkOption": "Σύνδεσμος", "publish": "Δημοσίευση", "publishing": "Δημοσίευση...",
  "addContent": "Προσθήκη περιεχομένου",
  "pasteVideoLink": "Επικολλήστε σύνδεσμο YouTube",
  "loginRequired": "Απαιτείται σύνδεση",
  "publishSuccess": "Δημοσιεύτηκε ✨", "publishFailed": "Αποτυχία δημοσίευσης",
  "myStoriesTab": "Ιστορίες μου", "trendsTab": "Τάσεις", "videosTab": "Βίντεο",
  "allCategory": "Όλα", "generalCategory": "Γενικά 📋",
  "videosCategory": "Βίντεο 🎬", "duaCategory": "Ντουά 🤲",
  "questionCategory": "Ερώτηση ❓", "storyCategory": "Ιστορία 📖",
  "adviceCategory": "Συμβουλή 💡", "reminderCategory": "Υπενθύμιση 🕌",
  "gratitudeCategory": "Ευγνωμοσύνη ❤️", "ruqyahCategory": "Ρουκγιά 🕋",
  "rizqCategory": "Πρόνοια 🤲",
  "noContent": "Κανένα περιεχόμενο, ακολουθήστε χρήστες!",
  "loadMore": "Φόρτωση περισσότερων", "following": "Ακολουθείτε",
  "unfollow": "Ακύρωση", "shares": "Κοινοποιήσεις",
  "savePost": "Αποθήκευση", "savedPost": "Αποθηκεύτηκε",
  "sharePost": "Κοινοποίηση", "deletePost": "Διαγραφή",
  "postDeleted": "Διαγράφηκε", "loginToLike": "Συνδεθείτε για like",
  "trending": "Τάσεις 🔥", "searchPlaceholder": "Αναζήτηση ιστοριών...",
  "messagesTitle": "Μηνύματα", "notificationsTab": "Ειδοποιήσεις",
  "messagesTab": "Μηνύματα", "activityTab": "Δραστηριότητα",
  "noNotifications": "Καμία ειδοποίηση",
  "conversationsTitle": "Συνομιλίες", "noConversations": "Καμία συνομιλία",
  "athanSoundTitle": "Ήχος Αζάν", "volumeLevel": "Ένταση",
  "testSound": "Δοκιμή ήχου", "athanSoundDesc": "Επιλέξτε ήχο Αζάν",
  "notifSettingsTitle": "Ρυθμίσεις ειδοποιήσεων",
  "prayerReminders": "Υπενθυμίσεις προσευχής",
  "prayerRemindersDesc": "Ειδοποίηση πριν την προσευχή",
  "athanAlert": "Ήχος Αζάν", "athanAlertDesc": "Παίξτε Αζάν στην ώρα προσευχής",
  "morningAdhkarDesc": "Πρωινά Adhkar υπενθύμιση",
  "eveningAdhkarDesc": "Βραδινά Adhkar υπενθύμιση",
  "fridayReminder": "Υπενθύμιση Παρασκευής",
  "fridayReminderDesc": "Υπενθύμιση για Σούρα Αλ-Κάχφ",
  "generalNotifs": "Γενικές ειδοποιήσεις",
  "generalNotifsDesc": "Νέα και ενημερώσεις εφαρμογής",
  "notifEnabled": "Ενεργοποιημένο", "notifDisabled": "Απενεργοποιημένο",
  "profileTitle": "Προφίλ", "loginBtn": "Σύνδεση", "logoutBtn": "Αποσύνδεση",
  "username": "Όνομα χρήστη", "points": "Πόντοι",
  "welcomeAppNotif": "Καλωσορίσατε στο Azan & Hikaya",
  "discoverStories": "Ανακαλύψτε ιστορίες — μοιραστείτε τη στιγμές πίστης σας",
  "eveningAdhkarReminder": "Μην ξεχάσετε τα βραδινά Adhkar",
  "every_day": "Κάθε μέρα",
  "startConversation": "Ξεκινήστε συνομιλία με φίλους",
  "findFriends": "Βρείτε φίλους", "noActivity": "Καμία δραστηριότητα",
  "activityWillAppear": "Θα εμφανιστεί εδώ όταν κάποιος αλληλεπιδράσει",
  "loginPromptTitle": "Σύνδεση",
  "loginPromptDesc": "Για ειδοποιήσεις και μηνύματα από φίλους",
  "loginAction": "Σύνδεση",
  "remindersStopped": "Υπενθυμίσεις σταμάτησαν",
  "remindersActivated": "Υπενθυμίσεις ενεργοποιήθηκαν",
  "allowNotificationsPlease": "Επιτρέψτε ειδοποιήσεις",
  "userDefault": "Χρήστης", "rateAppThanks": "Ευχαριστούμε!",
  "prayerTimesShareTitle": "Ώρες προσευχής",
  "prayerTimesCopiedToast": "Αντιγράφηκαν",
  "mosqueTimesLabel": "Ώρες τζαμιού",
  "cancelMosqueLink": "Τζαμί αποσυνδέθηκε", "cancelLabel": "Ακύρωση",
  "remainingLabel": "Υπολειπόμενο",
  "searchNearbyMosqueDesc": "Αναζητήστε κοντινό τζαμί",
  "tapToMarkComplete": "Πατήστε για ολοκλήρωση",
  "duaCategory_morning": "Πρωινά Adhkar", "duaCategory_evening": "Βραδινά Adhkar",
  "duaCategory_sleep": "Adhkar ύπνου", "duaCategory_prayer": "Adhkar μετά προσευχής",
  "duaCategory_food": "Adhkar φαγητού", "duaCategory_travel": "Adhkar ταξιδιού",
  "duaCategory_quran": "Κορανικά Ντουά", "duaCategory_prophetic": "Προφητικά Ντουά",
  "repetitions": "φορές", "source": "Πηγή", "virtue": "Ανταμοιβή",
  "dhikrStrengthenFaith": "Ενδυναμώστε την πίστη σας",
  "dhikrQuranReward": "Ανταμοιβή ενός τρίτου του Κορανίου",
  "dhikrRepentance": "Για μετάνοια και συγχώρεση",
  "duaTitleAyatKursi": "Αγιάτ αλ-Κούρσι (Ο Εδάφιο του Θρόνου)",
  "duaSubtitleProtection": "Για προστασία και ασφάλεια",
  "duaTitleAnxiety": "Ντουά για άγχος και θλίψη",
  "duaSubtitleRemoveWorry": "Για αφαίρεση ανησυχίας",
  "duaTitleSayyidIstighfar": "Κύριο της αναζήτησης συγχώρεσης",
  "duaTitleRizq": "Ντουά για πρόνοια",
  "duaSubtitleRizqBlessing": "Για πρόνοια και ευλογίες",
  "duaTitleEnterMosque": "Ντουά εισόδου στο τζαμί",
  "duaSubtitleGoToPrayer": "Κατά τη μετάβαση στην προσευχή",
  "duaTitleTawakkul": "Εμπιστοσύνη στον Αλλάχ",
  "duaSubtitleLeavingHome": "Κατά την αναχώρηση από το σπίτι",
  "duaTitleHealing": "Ντουά θεραπείας",
  "duaSubtitleForSick": "Για τους ασθενείς",
  "automatic": "Αυτόματο", "currentMode": "Τρέχουσα λειτουργία",
  "darkMode": "Σκοτεινό", "lightMode": "Φωτεινό",
  "otherAlerts": "Άλλες ειδοποιήσεις",
  "pwaNotifTip": "Ειδοποιήσεις λειτουργούν ακόμα και με κλειστή εφαρμογή!",
  "noCommentsYetShort": "Κανένα σχόλιο ακόμα", "trySaying": "Δοκιμάστε να πείτε",
  "ruqyahPageTitle": "Θεραπεία Ρουκγιά Σαρία",
  "ruqyahPageSubtitle": "Ρουκγιά από το Κοράνι και τη Σούννα",
  "ruqyahCatAll": "Όλα", "ruqyahCatGeneral": "Γενικά",
  "ruqyahCatEye": "Κακό μάτι", "ruqyahCatEnvy": "Φθόνος",
  "ruqyahCatMagic": "Μαγεία", "ruqyahCatTouch": "Επαφή Τζιν",
  "ruqyahCatInsomnia": "Αϋπνία", "ruqyahCatWhispers": "Ψιθυρισμοί",
  "ruqyahCatProtection": "Προστασία",
  "ruqyahAyatKursiTitle": "Αγιάτ αλ-Κούρσι",
  "ruqyahAyatKursiSubtitle": "Για διαφύλαξη και προστασία",
  "ruqyahFalaqTitle": "Σούρα Αλ-Φαλάκ",
  "ruqyahFalaqSubtitle": "Από το κακό της δημιουργίας",
  "ruqyahNasTitle": "Σούρα Αν-Νας",
  "ruqyahNasSubtitle": "Από τον ψιθυριστή",
  "ruqyahIkhlasTitle": "Σούρα Αλ-Ιχλάς",
  "ruqyahIkhlasSubtitle": "Ισοδυναμεί με ένα τρίτο του Κορανίου",
  "ruqyahHomeProtTitle": "Προστασία σπιτιού",
  "ruqyahHomeProtSubtitle": "Από τζιν και δαίμονες",
  "ruqyahRefSahihHadith": "Αυθεντική χαντίθ",
  "ruqyahReadThrice": "(Διαβάστε τρεις φορές πρωί και βράδυ)",
  "closeBtn": "Κλείσιμο", "noRuqyahInCategory": "Καμία ρουκγιά σε αυτή την κατηγορία",
  "morningAdhkarTitle": "Πρωινά Adhkar",
  "morningAdhkarSubtitle": "Ξεκινήστε τη μέρα μνημονεύοντας τον Αλλάχ",
  "middayDuasTitle": "Ντουά και ικεσίες",
  "middayDuasSubtitle": "Ντουά για γονείς, δοξολογία και συγχώρεση",
  "eveningQuranTitle": "Ώρα Κορανίου",
  "eveningQuranSubtitle": "Ελάτε να διαβάσετε και να αναλογιστείτε",
  "bedtimeAdhkarTitle": "Adhkar ύπνου",
  "bedtimeAdhkarSubtitle": "Θωρακιστείτε πριν τον ύπνο",
  "favorites": "Αγαπημένα", "yourSavedDuas": "Αποθηκευμένα ντουά",
  "aiSelectedDuas": "Ντουά επιλεγμένα από AI ✨",
  "youHaveSavedDuas": "Έχετε {count} αποθηκευμένα ντουά",
  "noSavedDuasYet": "Δεν έχετε αποθηκεύσει ντουά ακόμα",
  "loadingAdhkar": "Προετοιμασία adhkar...",
  "tapToSaveFavorites": "Πατήστε ❤️ για αποθήκευση αγαπημένων",
  "backToAdhkar": "Πίσω στα Adhkar", "newDuas": "Νέα Ντουά",
  "openQuran": "Ανοίξτε το Ιερό Κοράνι",
  "trackYourDailyPrayers": "Παρακολουθήστε τις καθημερινές σας προσευχές",
  "todayProgress": "Πρόοδος σήμερα", "todayPrayers": "Σημερινές προσευχές",
  "setQuranGoalTitle": "Ορίστε στόχο Κορανίου",
  "howMuchQuranDaily": "Πόσο χρόνο θέλετε να διαβάζετε Κοράνι;",
  "5minutes": "5 λεπτά", "10minutes": "10 λεπτά",
  "20minutes": "20 λεπτά", "30minutes": "30 λεπτά", "1hour": "1 ώρα",
  "dailyReminder": "Καθημερινή υπενθύμιση", "createGoal": "Δημιουργία στόχου",
  "quranGoalSaved": "Στόχος Κορανίου αποθηκεύτηκε ✅",
  "minutesDaily": "{count} λεπτά ημερησίως",
  "setDailyAdhkar": "Ορίστε καθημερινά Adhkar",
  "adhkarSettingsSaved": "Ρυθμίσεις Adhkar αποθηκεύτηκαν ✅",
  "saveSettings": "Αποθήκευση ρυθμίσεων",
  "rewardsTitle": "Ανταμοιβές", "dailyLogin": "Καθημερινή σύνδεση",
  "dailyLoginDesc": "Συνδεθείτε καθημερινά για ανταμοιβή",
  "tasbeeh100": "Τασμπίχ 100", "tasbeeh100Desc": "Ολοκληρώστε 100 τασμπίχ",
  "quranPageReward": "Σελίδα Κορανίου",
  "quranPageRewardDesc": "Διαβάστε μια σελίδα Κορανίου",
  "loginToCollect": "Συνδεθείτε για χρυσό",
  "streakDays": "Σερί ημερών", "claimBtn": "Λάβετε",
  "storeBtn": "Κατάστημα", "logTitle": "Αρχείο", "storeTitle": "Κατάστημα",
  "storePremiumItems": "Premium με χρυσό",
  "storeCatAll": "Όλα", "storeCatFrame": "Πλαίσια", "storeCatTheme": "Θέματα",
  "storeCatBadge": "Σήματα", "storeCatEffect": "Εφέ",
  "storeCatMembership": "Συνδρομές", "storeCatCharity": "Φιλανθρωπία",
  "goldLabel": "Χρυσός", "ownedLabel": "Κατοχή",
  "insufficientGold": "Ανεπαρκές", "buyBtn": "Αγορά",
  "insufficientGoldMsg": "Ανεπαρκές χρυσό υπόλοιπο",
  "purchaseFailed": "Αποτυχία αγοράς",
  "donationsTitle": "Δωρεές", "requestHelp": "Αίτηση βοήθειας",
  "importantNotice": "Σημαντική ειδοποίηση",
  "donationsDisclaimer": "Είμαστε μόνο πλατφόρμα σύνδεσης. Δεν φέρουμε ευθύνη. Προσευχηθείτε για τους γονείς μας.",
  "noRequestsNow": "Κανένα αίτημα τώρα",
  "beFirstToPost": "Γίνετε ο πρώτος",
  "anonymous": "Ανώνυμος", "amountNeeded": "Απαιτούμενο ποσό",
  "contactInfo": "Επικοινωνία", "requestPublished": "Το αίτημά σας δημοσιεύτηκε",
  "cancelBtn": "Ακύρωση", "publishBtn": "Δημοσίευση",
  "requestTitlePlaceholder": "Τίτλος αιτήματος *",
  "requestDescPlaceholder": "Περιγράψτε *",
  "contactInfoPlaceholder": "Στοιχεία επικοινωνίας *",
  "amountPlaceholder": "Ποσό (προαιρετικό)",
  "aiAssistantTitle": "Ισλαμικός βοηθός",
  "poweredByGPT": "Με τεχνολογία GPT-5.2",
  "freeRemaining": "{count} δωρεάν", "perQuestion": "5/ερώτηση",
  "bismillah": "Στο Όνομα του Αλλάχ, του Ελεήμονα, του Οικτίρμονα",
  "loginFirstMsg": "Συνδεθείτε πρώτα",
  "sampleQ1": "Ποιος είναι ο κανόνας για το Ταραουίχ;",
  "sampleQ2": "Πώς υπολογίζω τη Ζακάτ;",
  "sampleQ3": "Ποιοι είναι οι πυλώνες του Ισλάμ;",
  "sampleQ4": "Ντουά εισόδου στο τζαμί",
  "contactUsTitle": "Επικοινωνία", "emailLabel": "Email",
  "phoneWhatsapp": "Τηλ / WhatsApp", "directWhatsapp": "Απευθείας WhatsApp",
  "instantChat": "Άμεσο chat",
  "namePlaceholder": "Όνομα *", "emailPlaceholder": "Email",
  "messagePlaceholder": "Μήνυμά σας *", "sendBtn": "Αποστολή",
  "sending": "Αποστολή...",
  "messageSentSuccess": "Στάλθηκε επιτυχώς! Θα απαντήσουμε σύντομα.",
  "sendError": "Σφάλμα αποστολής",
  "ownerDeveloper": "Ιδιοκτήτης & Προγραμματιστής: Muhammad Al-Rajab",
  "marketplaceTitle": "Ισλαμική αγορά",
  "marketplaceSubtitle": "Ισλαμικά προϊόντα κοντά σας",
  "marketCatAll": "Όλα", "marketCatClothing": "Ρούχα",
  "marketCatBooks": "Βιβλία", "marketCatAccessories": "Αξεσουάρ",
  "marketCatFood": "Τρόφιμα", "marketCatPerfume": "Αρώματα",
  "marketCatGeneral": "Γενικά",
  "registerAsVendor": "Εγγραφή ως πωλητής",
  "wantToSell": "Θέλετε να πουλήσετε;",
  "registerAndPublish": "Εγγραφείτε και δημοσιεύστε μετά την έγκριση",
  "requestUnderReview": "Το αίτημά σας εξετάζεται",
  "willNotifyApproval": "Θα ειδοποιηθείτε μετά την έγκριση",
  "enterShopName": "Όνομα καταστήματος", "requestSent": "Αίτημα στάλθηκε",
  "fillNameAndPrice": "Απαιτούνται όνομα και τιμή",
  "productAdded": "Προϊόν προστέθηκε",
  "aboutUsTitle": "Σχετικά με εμάς", "hadithNarrator": "Αφηγητής",
  "installAppTitle": "Εγκατάσταση Azan & Hikaya",
  "installAppSubtitle": "Γρήγορη πρόσβαση χωρίς browser",
  "installBtn": "Εγκατάσταση",
  "athanAqsa": "Τζαμί Αλ-Άκσα (Ιερουσαλήμ)",
  "athanDefault": "Απλός ήχος", "tapToCount": "Πατήστε για μέτρηση",
  "prayerTimeNow": "Ώρα προσευχής",
  "prayerFajr": "Προσευχή Φατζρ", "prayerDhuhr": "Προσευχή Ντοχρ",
  "prayerAsr": "Προσευχή Ασρ", "prayerMaghrib": "Προσευχή Μαγκρίμπ",
  "prayerIsha": "Προσευχή Ίσα",
  "athanPlaying": "Αναπαραγωγή Αζάν...", "dismiss": "Κλείσιμο",
  "namesOfAllahTitle": "Τα Όμορφα Ονόματα του Αλλάχ",
  "namesOfAllahVerse": "Και στον Αλλάχ ανήκουν τα ωραιότερα ονόματα, επικαλεστείτε Τον μ' αυτά",
  "searchByNameOrMeaning": "Αναζήτηση ονόματος ή νοήματος...",
  "hideSearch": "Απόκρυψη αναζήτησης", "searchLabel": "Αναζήτηση",
  "nameCount": "ονόματα", "meaningLabel": "Σημασία", "favoriteName": "Αγαπημένο",
  "installInstructions": "Βήματα εγκατάστασης", "stepNumber": "Βήμα",
  "zakatTitle": "Υπολογιστής Ζακάτ",
  "zakatGold": "Χρυσός", "zakatSilver": "Ασήμι", "zakatCash": "Μετρητά",
  "zakatResult": "Ποσό Ζακάτ", "zakatCalculate": "Υπολογισμός Ζακάτ",
  "periodTrackerTitle": "Παρακολούθηση περιόδου",
  "periodStart": "Αρχή περιόδου", "periodEnd": "Τέλος περιόδου",
  "periodDays": "ημέρες", "loadingData": "Φόρτωση...",
  "selectAll": "Επιλογή όλων", "deselectAll": "Αποεπιλογή όλων",
  "sortBy": "Ταξινόμηση κατά", "filterBy": "Φίλτρο κατά",
  "thisWeek": "Αυτή η εβδομάδα", "thisMonth": "Αυτός ο μήνας",
  "gram": "γραμμάριο", "amount": "Ποσό", "enterAmount": "Εισάγετε ποσό",
  "iosStep1Prefix": "Πατήστε", "iosStep1Highlight": "Κουμπί κοινοποίησης",
  "iosStep2Prefix": "Επιλέξτε", "iosStep2Highlight": "Προσθήκη στην αρχική",
  "iosStep3Prefix": "Πατήστε", "iosStep3Highlight": "Προσθήκη",
  "chromeInstallHint": "Ανοίξτε στο Chrome → Μενού → \"Εγκατάσταση εφαρμογής\"",
  "gregorianDate": "Γρηγοριανό",
  "switchToHijri": "Ημερολόγιο Χίτζρα", "switchToGregorian": "Γρηγοριανό ημερολόγιο",
  "games": "Παιχνίδια", "initial": "Αρχικό", "medial": "Μεσαίο", "final": "Τελικό",
  "live247": "Ζωντανά 24/7",
  "nordicPrayerFix": "Προσαρμογή ωρών προσευχής υψηλών γεωγραφικών πλατών",
  "kidsSection": "Παιδική ενότητα", "noorGreeting": "Γεια! Είμαι ο Νουρ!",
  "startLearning": "Ξεκινήστε να μαθαίνετε",
  "level1Desc": "Μάθετε τα πρώτα 7 αραβικά γράμματα",
  "level1Skill1": "Αναγνώριση γραμμάτων", "level1Skill2": "Προφορά",
  "level1Skill3": "Μορφές γραφής",
  "level2Title": "Επίπεδο 2: Δομικά στοιχεία",
  "level2Desc": "Μάθετε γράμματα 8-14",
  "level2Skill1": "Σύνδεση γραμμάτων", "level2Skill2": "Ανάγνωση λέξεων",
  "level2Skill3": "Εξάσκηση ήχων",
  "level3Title": "Επίπεδο 3: Δυναμώνοντας",
  "level3Desc": "Μάθετε γράμματα 15-21",
  "level3Skill1": "Σύνθετα γράμματα", "level3Skill2": "Κατασκευή προτάσεων",
  "level3Skill3": "Ακουστικές δεξιότητες",
  "level4Title": "Επίπεδο 4: Σχεδόν!",
  "level4Desc": "Μάθετε τα τελευταία γράμματα 22-28",
  "level4Skill1": "Πλήρες αλφάβητο", "level4Skill2": "Ταχυανάγνωση",
  "level4Skill3": "Εξάσκηση γραφής",
  "level5Title": "Επίπεδο 5: Λέξεις Κορανίου",
  "level5Desc": "Μάθετε βασικό λεξιλόγιο Κορανίου",
  "level5Skill1": "Λεξιλόγιο Κορανίου", "level5Skill2": "Σημασία και πλαίσιο",
  "level5Skill3": "Απαγγελία",
  "tabGuide": "Οδηγός", "tabDuas": "Ντουά",
  # Keys that need same translations (all notification/athan/zakat-related)
  "compassHowToTitle": "Πώς χρησιμοποιείτε την πυξίδα",
  "compassStep1": "Τοποθετήστε το τηλέφωνο οριζόντια",
  "compassStep2": "Μακριά από μέταλλα και ηλεκτρονικά",
  "compassStep3": "Βαθμονόμηση: κινήστε σε σχήμα 8",
  "compassStep4": "Γυρίστε μέχρι 🕋 να εμφανιστεί και γίνει πράσινο",
  "understoodBtn": "Κατάλαβα ✓",
  "enableCompassBtn": "Πατήστε για ενεργοποίηση πυξίδας",
  "compassUnavailable": "Πυξίδα μη διαθέσιμη",
  "compassUnavailableDesc": "Η συσκευή σας δεν υποστηρίζει πυξίδα. Χρησιμοποιήστε εξωτερική πυξίδα.",
  "calibrateBtn": "Βαθμονόμηση",
  "lowAccuracyMsg": "Χαμηλή ακρίβεια - κινήστε σε ∞",
  "movePhone8Pattern": "Κινήστε σε σχήμα 8...",
  "noLocationDetected": "Τοποθεσία δεν εντοπίστηκε",
  "fromNorth": "Από βορρά", "fromEast": "Από ανατολή",
  "fromSouth": "Από νότο", "fromWest": "Από δύση",
  "dhikrRememberAllah": "Μνημονεύστε τον Αλλάχ",
  "resetCounterLabel": "Επαναφορά μετρητή",
  "chooseDhikrTitle": "Επιλέξτε Dhikr",
  "chooseFromDhikr": "Επιλέξτε από αυθεντικά Adhkar",
  "nowLabel": "Τώρα", "shareOnWhatsapp": "Κοινοποίηση μέσω WhatsApp",
  "copiedToClipboard": "Αντιγράφηκε", "confirm": "Επιβεβαίωση",
  "all": "Όλα", "new": "Νέο", "popular": "Δημοφιλές", "recent": "Πρόσφατο",
  "yesterday": "Χθες", "tomorrow": "Αύριο", "next": "Επόμενο",
  "previous": "Προηγούμενο", "complete": "Ολοκλήρωση", "incomplete": "Ημιτελές",
  "success": "Επιτυχία", "warning": "Προειδοποίηση", "info": "Πληροφορία",
  "appSubtitle": "Ώρες προσευχής • Εμπνευστικές ιστορίες • Ισλαμική ζωή",
  "minutesReading": "λεπτά ανάγνωσης", "reported": "Αναφέρθηκε",
  "reportBtn": "Αναφορά", "nextPrayerColon": "Επόμενη προσευχή:",
  "consecutiveDays": "συνεχόμενες ημέρες",
  "storyCategories": "Κατηγορίες", "storyAll": "Γενικά",
  "storyQuran": "Κοράνι", "storyHadith": "Χαντίθ",
  "storyDua": "Ντουά", "storyAdvice": "Συμβουλή",
  "writeStory": "Γράψτε την ιστορία σας", "sendComment": "Αποστολή",
  "posts": "Δημοσιεύσεις", "prayerNotifications": "Ειδοποιήσεις προσευχής",
  "athanBeforePrayer": "Πριν την προσευχή", "athanAtPrayer": "Στην ώρα προσευχής",
  "allNotifications": "Όλες οι ειδοποιήσεις", "exploreTitle": "Εξερεύνηση",
  "discoverContent": "Ανακαλύψτε ισλαμικό περιεχόμενο",
  "donationTitle": "Δωρεές", "donateNow": "Δωρίστε τώρα",
  "donationAmount": "Ποσό δωρεάς", "askQuestion": "Κάντε ερώτηση...",
  "questionsRemaining": "ερωτήσεις υπολειπόμενες", "dailyLimit": "Ημερήσιο όριο",
  "watchAdForCredits": "Δείτε διαφήμιση για πόντους",
  "installDesc": "Προσθέστε στην αρχική οθόνη",
  "installStep1": "Ανοίξτε browser", "installStep2": "Πατήστε κοινοποίηση",
  "installStep3": "Επιλέξτε 'Προσθήκη στην αρχική'",
  "pageNotFoundDesc": "Η σελίδα δεν υπάρχει",
  "deleteLabel": "Διαγραφή", "writeFirst": "Γράψτε κάτι πρώτα",
  "errorOccurred": "Παρουσιάστηκε σφάλμα",
  "imageType": "Εικόνα", "embedType": "Ενσωμάτωση",
  "quranCategory": "Κοράνι", "hadithCategory": "Χαντίθ",
  "storiesCategory": "Ιστορίες", "familyCategory": "Οικογένεια",
  "titleOptional": "Τίτλος (προαιρετικό)",
  "shareIdea": "Μοιραστείτε την ιδέα σας ✨",
  "videoUrlPlaceholder": "URL YouTube ή βίντεο",
  "chooseImage": "Επιλέξτε εικόνα", "chooseVideo": "Επιλέξτε βίντεο",
  "categoryLabel": "Κατηγορία", "publishNow": "Δημοσιεύστε τώρα",
  "contentCopied": "Αντιγράφηκε", "thePost": "Η δημοσίευση",
  "videoTab": "Βίντεο", "allLabel": "Όλα", "noVideosYet": "Κανένα βίντεο ακόμα",
  "createContent": "Δημιουργία περιεχομένου ✨",
  "recommendedUsers": "Προτεινόμενοι χρήστες",
  "videosLabel": "Βίντεο", "contentNotFound": "Περιεχόμενο δεν βρέθηκε",
  "adminDashboard": "Πίνακας διαχείρισης", "myPosts": "Δημοσιεύσεις μου",
  "contactFormTitle": "Επικοινωνία", "sendMessage": "Αποστολή μηνύματος",
  "yourName": "Όνομα", "yourEmail": "Email",
  "messageContent": "Περιεχόμενο μηνύματος", "messageSent": "Μήνυμα στάλθηκε",
  "replyLabel": "Απάντηση",
  "notifPrayerAlerts": "Ειδοποιήσεις προσευχής",
  "notifPrayerAlertsDesc": "Ειδοποίηση σε κάθε ώρα προσευχής",
  "notifPrayerReminder": "Υπενθύμιση προσευχής",
  "notifPrayerReminderDesc": "Υπενθύμιση λεπτά πριν",
  "notifBefore10Min": "10 λεπτά πριν",
  "notifPrayerTracker": "Παρακολούθηση προσευχής",
  "notifPrayerTrackerDesc": "Υπενθύμιση καταγραφής προσευχών",
  "notifQuranListen": "Ακρόαση Κορανίου",
  "notifQuranListenDesc": "Καθημερινή υπενθύμιση Κορανίου",
  "notifDhikrDaily": "Καθημερινό Dhikr",
  "notifDhikrDailyDesc": "Καθημερινή μνημόνευση Αλλάχ",
  "notifStories": "Καθημερινές ιστορίες",
  "notifStoriesDesc": "Ειδοποίηση ιστοριών",
  "notifFriday": "Ειδική Παρασκευή",
  "notifFridayDesc": "Υπενθύμιση Σούρα Αλ-Κάχφ",
  "notifSuhoor": "Υπενθύμιση Σουχούρ",
  "notifSuhoorDesc": "Μόνο κατά το Ραμαζάνι",
  "notifSuhoorSchedule": "1 ώρα πριν το Φατζρ",
  "allowNotifBrowser": "Επιτρέψτε ειδοποιήσεις στις ρυθμίσεις browser",
  "bgNotifEnabled": "Ειδοποιήσεις παρασκηνίου ✅",
  "bgNotifFailed": "Αποτυχία ειδοποιήσεων παρασκηνίου",
  "enableLocationFirst": "Ενεργοποιήστε πρώτα τοποθεσία",
  "allowNotifFirst": "Επιτρέψτε πρώτα ειδοποιήσεις",
  "testNotifSent": "Δοκιμαστική ειδοποίηση ✅",
  "testNotifFailed": "Αδυναμία ειδοποίησης",
  "playingAthan": "Αναπαραγωγή Αζάν... (5 δευτ.)",
  "playAthanFailed": "Αδυναμία αναπαραγωγής",
  "notifAndAthan": "Ειδοποιήσεις και Αζάν",
  "bgAthanNotif": "Αζάν παρασκηνίου",
  "bgAthanNotifDesc": "Ειδοποιήσεις Αζάν ακόμα και με κλειστή εφαρμογή",
  "enableNotif": "Ενεργοποίηση ειδοποιήσεων",
  "testNotif": "Δοκιμή ειδοποίησης", "testAthan": "Δοκιμή Αζάν",
  "prayersSection": "Προσευχές", "selectAthanSound": "Επιλογή ήχου Αζάν",
  "dailyGoalsSection": "Καθημερινοί στόχοι",
  "athanMakkah": "Μέκκα", "athanMadinah": "Μεδίνα",
  "athanTurkish": "Τουρκικό", "athanSimple": "Απλός ήχος",
  "theStory": "Η ιστορία", "viewsCount": "προβολές",
  "exploreLabel": "Εξερεύνηση", "cancelSearch": "Ακύρωση",
  "smartAssistant": "Έξυπνος βοηθός",
  "tryDifferent": "Δοκιμάστε διαφορετικές λέξεις ή φωνητική αναζήτηση 🎤",
  "resultsCount": "αποτελέσματα", "moreCount": "Περισσότερα", "errorShort": "Σφάλμα",
  "searchMosqueHere": "Αναζήτηση...", "noMosquesFound": "Δεν βρέθηκαν τζαμιά",
  "selectMosque": "Επιλέξτε τζαμί", "nearbyMosques": "Κοντινά τζαμιά",
  "mosque": "Τζαμί", "linkedMosque": "Συνδεδεμένο τζαμί",
  "changeMosqueBtn": "Αλλαγή τζαμιού",
  "installOnAndroid": "Εγκατάσταση σε Android",
  "installOnIOS": "Εγκατάσταση σε iOS",
  "openChrome": "Ανοίξτε Chrome", "openSafari": "Ανοίξτε Safari",
  "tapThreeDots": "Πατήστε τις τρεις τελείες ⋮",
  "tapShareBtn": "Πατήστε κοινοποίηση ⎋",
  "selectAddHome": "Επιλέξτε 'Προσθήκη στην αρχική'",
  "tapInstall": "Πατήστε 'Εγκατάσταση'", "tapAdd": "Πατήστε 'Προσθήκη'",
  "installNow": "Εγκατάσταση τώρα", "appInstalled": "Εγκαταστάθηκε ✅",
  "zakatCurrencySection": "Νόμισμα",
  "zakatCurrencySubtitle": "Επιλέξτε νόμισμα για Νισάμπ",
  "zakatSmartCalc": "Έξυπνος υπολογιστής πολλαπλών νομισμάτων",
  "zakatDetecting": "Εντοπισμός...", "zakatChooseCurrency": "Επιλέξτε νόμισμα",
  "zakatGold85g": "Χρυσός (85 γρ.)", "zakatSilver595g": "Ασήμι (595 γρ.)",
  "zakatAssetsSection": "Τα περιουσιακά σας",
  "zakatAssetsSubtitle": "Εισάγετε αξία στο επιλεγμένο νόμισμα",
  "zakatDetails": "Λεπτομέρειες", "zakatTotalAssets": "Σύνολο",
  "zakatNotRequired": "Δεν απαιτείται Ζακάτ",
  "zakatBelowNisab": "Κάτω από Νισάμπ",
  "zakatLegalNote": "Ισλαμική νομική σημείωση",
  "zakatLegalText": "Βασισμένο στο Νισάμπ ασημιού (595 γρ.). Ζακάτ 2,5%.",
  "zakatPropertyLabel": "Ακίνητα και εμπορική ιδιοκτησία",
}

def apply_translations(locale_file, translations):
    with open(locale_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    en_file = os.path.join(os.path.dirname(locale_file), 'en.json')
    with open(en_file, 'r', encoding='utf-8') as f:
        en_data = json.load(f)
    updated = 0
    for key, translation in translations.items():
        if key in data and key in en_data and data[key] == en_data[key]:
            data[key] = translation
            updated += 1
    with open(locale_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return updated

if __name__ == '__main__':
    el_updated = apply_translations('/app/frontend/src/locales/el.json', EL)
    print(f"Greek (el.json): {el_updated} keys translated")
