"""
Comprehensive translation generator for all 5 languages.
Generates proper translations for DE, RU, FR, TR locale files.
"""
import json

# Load current locale files
locales = {}
for lang in ['en', 'ar', 'de', 'ru', 'fr', 'tr']:
    with open(f'/app/frontend/src/locales/{lang}.json') as f:
        locales[lang] = json.load(f)

en = locales['en']

# =============================================
# GERMAN (DE) TRANSLATIONS
# =============================================
de_translations = {
    # App
    "appName": "Azan & Hikaya",
    "appTitle": "Azan & Hikaya",
    # Prayer names (kept as Islamic transliteration)
    "fajr": "Fajr",
    "dhuhr": "Dhuhr",
    "asr": "Asr",
    "maghrib": "Maghrib",
    "isha": "Ischa",
    "fajrLabel": "Fajr (Morgengebet)",
    # Navigation
    "qibla": "Qibla",
    "duas": "Duas",
    "duasAndDhikr": "Duas & Dhikr",
    "adhkar": "Adhkar",
    "tasbih": "Tasbih",
    "zakat": "Zakat",
    "shop": "Shop",
    # Islamic terms
    "juz": "Juz",
    "subhanAllah": "SubhanAllah",
    "alhamdulillah": "Alhamdulillah",
    "allahuAkbar": "Allahu Akbar",
    "istighfar": "Istighfar",
    "name": "Name",
    "km": "km",
    "auto": "Automatisch",
    "info": "Info",
    # Ramadan
    "ramadanCountdown": "Ramadan-Countdown",
    "ramadanMubarak": "Ramadan Mubarak! 🌙",
    "eidFitr": "Eid al-Fitr",
    "eidAdha": "Eid al-Adha",
    "iftar": "Iftar",
    "catRamadan": "Ramadan",
    # Media
    "mediaText": "Text",
    "mediaVideo": "Video",
    "mediaAudio": "Audio",
    "liveLabel": "Live",
    "pauseBtn": "Pause",
    "textOption": "Text",
    "videoOption": "Video",
    "linkOption": "Link",
    # Stories
    "trendsTab": "Trends",
    "videosTab": "Videos",
    "videosCategory": "Videos 🎬",
    "duaCategory": "Duas 🤲",
    "rizqCategory": "Versorgung 🤲",
    "storyHadith": "Hadith",
    "storyRamadan": "Ramadan",
    "storyDua": "Dua",
    "hadithCategory": "Hadith",
    "videoTab": "Video",
    "videosLabel": "Videos",
    "videos": "Videos",
    "addVideo": "Video",
    # Calendar
    "hijriCalendar2": "Hijri",
    "hijriMonth1": "Muharram",
    "hijriMonth2": "Safar",
    "hijriMonth3": "Rabi al-Awwal",
    "hijriMonth4": "Rabi ath-Thani",
    "hijriMonth9": "Ramadan",
    # Languages
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "turkish": "Türkçe",
    "urdu": "اردو",
    "indonesian": "Bahasa Indonesia",
    # Reciters
    "reciterSudais": "Abdurrahman As-Sudais",
    "reciterShuraym": "Saud Ash-Shuraim",
    "reciterAbdulbasit": "Abdul Basit Abdus Samad",
    "reciterBudair": "Salah Al-Budair",
    "reciterAhmad": "Abdulaziz Al-Ahmad",
    "reciterTablawi": "Muhammad At-Tablawi",
    "reciterYasser": "Yasser Ad-Dosari",
    "reciterNasser": "Nasser Al-Qatami",
    "reciterBanna": "Mahmoud Ali Al-Banna",
    "reciterFares": "Fares Abbad",
    "reciterGhamdi": "Saad Al-Ghamdi",
    "reciterAkhdar": "Ibrahim Al-Akhdar",
    "reciterBasitMurattal": "Abdul Basit - Murattal",
    # Athan names
    "athanQuds": "Al-Aqsa",
    "athanAbdulbasit": "Abdul Basit",
    "athanAbdulBasit": "Abdul Basit Abdul Samad",
    "athanShahat": "Shahat",
    "athanSaqqaf": "Al-Saqqaf",
    # Quick access
    "quickQibla": "Qibla",
    "quickDuas": "Duas",
    "quickZakat": "Zakat",
    # Zakat
    "nisabIn": "Nisab in",
    "nisab": "Nisab",
    "zakatNisabTitle": "Zakat Nisab",
    "zakatNisab": "Nisab",
    "zakatTitle": "Zakat-Rechner",
    "zakatGold": "Gold",
    "zakatSilver": "Silber",
    "zakatCash": "Bargeld",
    "zakatResult": "Zakat-Betrag",
    "zakatCalculate": "Zakat berechnen",
    "goldLabel": "Gold",
    # Ruqyah
    "ruqyahAyatKursi": "Ayat al-Kursi",
    "ruqyahMuawwidhat": "Al-Muawwidhat",
    "ruqyahMuawwidhatDesc": "Al-Falaq & An-Nas",
    "ruqyahAyatKursiTitle": "Ayat al-Kursi",
    "ruqyahRefFalaq": "Al-Falaq: 1-5",
    "ruqyahRefNas": "An-Nas: 1-6",
    "ruqyahRefIkhlas": "Al-Ikhlas: 1-4",
    # References
    "refBukhari": "Al-Bukhari",
    "refMuslim": "Muslim",
    "refBukhariMuslim": "Al-Bukhari & Muslim",
    "refAbuDawud": "Abu Dawud",
    "refIbnMajah": "Ibn Majah",
    # Goals
    "goalStrengthenFaithDesc": "SubhanAllah wa bihamdihi",
    "goalQuranRewardDesc": "Qul Huwa Allahu Ahad",
    "goalRepentanceDesc": "Astaghfirullah al-Azeem",
    "dailyDhikr": "SubhanAllah wa bihamdihi, SubhanAllah al-Azeem",
    # UI Elements
    "namePlaceholder": "Name *",
    "namesOfAllahTitle": "Die schönen Namen Allahs",
    "namesOfAllahVerse": "Und Allah gehören die schönsten Namen, so ruft Ihn damit an",
    "searchByNameOrMeaning": "Nach Name, Bedeutung oder Nummer suchen...",
    "hideSearch": "Suche ausblenden",
    "searchLabel": "Suche",
    "nameCount": "Name(n)",
    "meaningLabel": "Bedeutung",
    "favoriteName": "Favorit",
    "installInstructions": "Installationsschritte",
    "stepNumber": "Schritt",
    "periodTrackerTitle": "Zyklusverfolgung",
    "periodStart": "Beginn der Periode",
    "periodEnd": "Ende der Periode",
    "periodDays": "Tage",
    "loadingData": "Laden...",
    "copy": "Kopieren",
    "copied": "Kopiert",
    "selectAll": "Alle auswählen",
    "deselectAll": "Auswahl aufheben",
    "sortBy": "Sortieren nach",
    "filterBy": "Filtern nach",
    "thisWeek": "Diese Woche",
    "thisMonth": "Dieser Monat",
    "gram": "Gramm",
    "amount": "Betrag",
    "enterAmount": "Betrag eingeben",
    "iosStep1Prefix": "Tippen Sie auf die",
    "iosStep1Highlight": "Teilen-Taste",
    "iosStep2Prefix": "Wählen Sie",
    "iosStep2Highlight": "Zum Startbildschirm hinzufügen",
    "iosStep3Prefix": "Tippen Sie auf",
    "iosStep3Highlight": "Hinzufügen",
    "chromeInstallHint": "Öffnen Sie die App im Chrome-Browser, tippen Sie auf das Browsermenü → \"App installieren\"",
    "gregorianDate": "Gregorianisch",
    "switchToHijri": "Hijri-Kalender",
    "switchToGregorian": "Gregorianischer Kalender",
    # Dua subcategories
    "duaSubTawaf": "Tawaf",
    "duaSubSuhoor": "Suhoor",
    "duaSubIftar": "Iftar",
    "duaSubIstikhara": "Istikhara",
}

# German Dua translations
de_duas = {
    "duaSleep1": "In Deinem Namen, o Allah, sterbe ich und lebe ich",
    "duaSleep2": "O Allah, schütze mich vor Deiner Strafe am Tag, an dem Du Deine Diener auferweckst",
    "duaSleep3": "In Deinem Namen, mein Herr, lege ich mich nieder, und durch Dich erhebe ich mich. Wenn Du meine Seele nimmst, erbarme Dich ihrer",
    "duaSleep4": "O Allah, Du hast meine Seele erschaffen und Du nimmst sie zurück. Dir gehört ihr Tod und ihr Leben",
    "duaSleep5": "O Allah, Herr der Himmel und Herr der Erde und Herr des gewaltigen Thrones, unser Herr und Herr aller Dinge",
    "duaWudu1": "Im Namen Allahs",
    "duaWudu2": "Ich bezeuge, dass es keinen Gott gibt außer Allah allein, ohne Partner, und ich bezeuge, dass Muhammad Sein Diener und Gesandter ist",
    "duaWudu3": "O Allah, mache mich zu denen, die bereuen, und mache mich zu denen, die sich reinigen",
    "duaWudu4": "Gepriesen seist Du, o Allah, und Lob sei Dir. Ich bezeuge, dass es keinen Gott gibt außer Dir",
    "duaMosque1": "O Allah, öffne mir die Tore Deiner Barmherzigkeit",
    "duaMosque2": "Ich suche Zuflucht bei Allah dem Allmächtigen und bei Seinem edlen Angesicht und bei Seiner ewigen Herrschaft vor dem verfluchten Satan",
    "duaMosque3": "Im Namen Allahs, und Gebete und Frieden auf den Gesandten Allahs",
    "duaSalah1": "Gepriesen seist Du, o Allah, und Lob sei Dir. Gesegnet ist Dein Name, erhaben ist Deine Majestät",
    "duaSalah2": "Unser Herr, gib uns Gutes in dieser Welt und Gutes im Jenseits, und schütze uns vor der Strafe des Feuers",
    "duaSalah3": "O Allah, ich suche Zuflucht bei Dir vor der Strafe des Grabes, vor der Strafe des Höllenfeuers",
    "duaSalah4": "Mein Herr, mache mich und meine Nachkommen zu denen, die das Gebet verrichten",
    "duaHome1": "Im Namen Allahs betreten wir, im Namen Allahs verlassen wir, und auf Allah, unseren Herrn, vertrauen wir",
    "duaHome2": "O Allah, ich bitte Dich um das Gute des Eintretens und das Gute des Verlassens",
    "duaClothes1": "Alles Lob gebührt Allah, der mich mit diesem Kleidungsstück bekleidet hat",
    "duaClothes2": "O Allah, ich bitte Dich um sein Gutes und das Gute, wofür es gemacht wurde",
    "duaTravel1": "Gepriesen sei Er, Der uns dies dienstbar gemacht hat, und wir hätten es nicht allein vermocht",
    "duaTravel2": "O Allah, wir bitten Dich um Rechtschaffenheit und Frömmigkeit auf dieser Reise",
    "duaTravel3": "O Allah, ich suche Zuflucht bei Dir vor den Schwierigkeiten der Reise",
    "duaFood1": "Im Namen Allahs",
    "duaFood2": "Im Namen Allahs, am Anfang und am Ende",
    "duaFood3": "Alles Lob gebührt Allah, der uns gespeist und getränkt hat und uns zu Muslimen gemacht hat",
    "duaFood4": "Alles Lob gebührt Allah, der mich mit dieser Speise gespeist hat",
    "duaDhikr1": "Gepriesen sei Allah",
    "duaDhikr2": "Alles Lob gebührt Allah",
    "duaDhikr3": "Allah ist der Größte",
    "duaDhikr4": "Es gibt keinen Gott außer Allah allein, ohne Partner",
    "duaDhikr5": "Ich bitte Allah um Vergebung",
    "duaRevival1": "O Herr der Morgendämmerung",
    "duaRevival2": "O Lenker der Herzen, festige mein Herz in Deiner Religion",
    "duaRevival3": "O Allah, ich bitte Dich um nützliches Wissen, gute Versorgung und angenommene Taten",
    "duaRevival4": "O Allah, ich bitte Dich um Rechtleitung, Frömmigkeit, Keuschheit und Selbstgenügsamkeit",
    "duaRizq1": "O Allah, ich suche Zuflucht bei Dir vor Angst und Trauer, vor Schwäche und Faulheit",
    "duaRizq2": "O Allah, genüge mir mit dem Erlaubten gegen das Verbotene",
    "duaRizq3": "O Allah, Herr der sieben Himmel, sei mir ausreichend in allem",
    "duaKnowledge1": "O Allah, nütze mir mit dem, was Du mich gelehrt hast, lehre mich, was mir nützt, und vermehre mein Wissen",
    "duaKnowledge2": "Mein Herr, vermehre mein Wissen",
    "duaKnowledge3": "O Allah, ich bitte Dich um nützliches Wissen, gute Versorgung und angenommene Taten",
    "duaFaith1": "O Allah, ich bitte Dich um Standhaftigkeit in meinen Angelegenheiten und Entschlossenheit in der Rechtleitung",
    "duaFaith2": "O Allah, mache uns den Glauben lieb und verschönere ihn in unseren Herzen",
    "duaJudgment1": "O Allah, ich bitte Dich um das Paradies und was mich ihm näher bringt",
    "duaJudgment2": "O Allah, mache meine Abrechnung leicht",
    "duaForgiveness1": "O Allah, Du bist mein Herr, es gibt keinen Gott außer Dir. Du hast mich erschaffen und ich bin Dein Diener",
    "duaForgiveness2": "Unser Herr, wir haben uns selbst Unrecht getan, und wenn Du uns nicht vergibst und Dich unser erbarmst",
    "duaForgiveness3": "Ich bitte Allah den Allmächtigen um Vergebung, es gibt keinen Gott außer Ihm",
    "duaPraising1": "Gepriesen sei Allah und Lob sei Ihm, so oft wie die Zahl Seiner Geschöpfe",
    "duaPraising2": "Es gibt keinen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und das Lob",
    "duaFamily1": "Unser Herr, schenke uns von unseren Ehepartnern und Nachkommen Augentrost",
    "duaFamily2": "Mein Herr, mache mich dankbar für Deine Gnade, die Du mir und meinen Eltern erwiesen hast",
    "duaFamily3": "O Allah, lege Liebe zwischen unsere Herzen und versöhne uns miteinander",
    "duaHealth1": "O Allah, Herr der Menschen, entferne die Krankheit. Heile, denn Du bist der Heiler",
    "duaHealth2": "Im Namen Allahs, ich vertraue auf Allah. O Allah, ich suche Zuflucht bei Dir",
    "duaLoss1": "Allah gehört, was Er genommen hat, und Ihm gehört, was Er gegeben hat",
    "duaLoss2": "Wahrlich, Allah gehört, was Er genommen hat, und Ihm gehört, was Er gegeben hat. Alles hat seine bestimmte Zeit bei Ihm",
    "duaSadness1": "O Allah, ich bin Dein Diener, der Sohn Deines Dieners, der Sohn Deiner Dienerin. Meine Stirnlocke ist in Deiner Hand",
    "duaSadness2": "Es gibt keinen Gott außer Dir. Gepriesen seist Du, wahrlich ich gehörte zu den Ungerechten",
    "duaPatience1": "O Allah, es gibt keine Leichtigkeit außer dem, was Du leicht gemacht hast",
    "duaPatience2": "Allah genügt uns, und Er ist der beste Sachwalter",
    "duaDebt1": "O Allah, ich suche Zuflucht bei Dir vor Angst und Trauer, vor Schwäche und Faulheit",
    "duaDebt2": "O Allah, genüge mir mit dem Erlaubten gegen das Verbotene",
    "duaDeceased1": "O Allah, vergib ihnen und erbarme Dich ihrer, gewähre ihnen Wohlergehen und verzeihe ihnen",
    "duaDeceased2": "O Allah, vergib unseren Lebenden und unseren Toten, den Anwesenden und den Abwesenden",
    "duaHajj1": "Hier bin ich, o Allah, hier bin ich. Du hast keinen Partner",
    "duaHajj2": "O Allah, dies ist Dein Haus, das Du geheiligt hast",
    "duaRamadan1": "O Allah, Du bist vergebend, Du liebst die Vergebung, so vergib mir",
    "duaRamadan2": "O Allah, ich habe für Dich gefastet und mit Deiner Versorgung breche ich mein Fasten",
    "duaNature1": "O Allah, mache es zu einem nützlichen Regen",
    "duaNature2": "O Allah, um uns herum und nicht auf uns",
    "duaGuidance1": "O Allah, ich bitte Dich um Deine Führung durch Dein Wissen und Deine Kraft durch Deine Macht",
    "duaGuidance2": "O Allah, zeige mir die Wahrheit als Wahrheit und gewähre mir, ihr zu folgen",
    "duaWakeUp1": "Alles Lob gebührt Allah, der uns Leben gab, nachdem Er uns hat sterben lassen",
    "duaWakeUp2": "Es gibt keinen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und das Lob",
    "duaNightmare1": "Ich suche Zuflucht bei den vollkommenen Worten Allahs vor Seinem Zorn und Seiner Strafe",
    "duaNightmare2": "Ich suche Zuflucht bei Allah vor dem verfluchten Satan",
    "duaAfterSalah1": "Ich bitte Allah um Vergebung. O Allah, Du bist der Frieden und von Dir kommt der Frieden",
    "duaAfterSalah2": "Es gibt keinen Gott außer Allah allein, ohne Partner. Ihm gehört die Herrschaft und das Lob",
    "duaAfterSalah3": "Es gibt keinen Gott außer Allah allein. Es gibt keine Macht und keine Kraft außer bei Allah",
    "duaDhikr6": "Gepriesen sei Allah und Lob sei Ihm, gepriesen sei Allah der Allmächtige",
    "duaDhikr7": "Es gibt keine Macht und keine Kraft außer bei Allah",
    "duaDhikr8": "O Allah, sende Segen auf Muhammad und auf die Familie Muhammads",
    "duaPostPrayer1": "SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (33x), dann: La ilaha illallah...",
    "duaPostPrayer2": "Ayat al-Kursi: Allah – es gibt keinen Gott außer Ihm, dem Lebendigen, dem Beständigen...",
    "duaMenstruation1": "Alles Lob gebührt Allah unter allen Umständen",
    "duaGoodManners1": "O Allah, leite mich zu den besten Manieren, denn niemand leitet dazu außer Dir",
    "duaGoodManners2": "O Allah, ich bitte Dich um Gesundheit, Keuschheit, Vertrauenswürdigkeit und gute Manieren",
    "duaVisitSick1": "Keine Sorge, Reinigung, so Allah will",
    "duaHappy1": "Alles Lob gebührt Allah, durch dessen Gnade die guten Werke vollendet werden",
    "duaHappy2": "O Allah, Dir gebührt alles Lob, wie es der Erhabenheit Deines Angesichts gebührt",
    "duaCondolence1": "Wahrlich, Allah gehört, was Er genommen hat, und Ihm gehört, was Er gegeben hat",
    "duaGrave1": "Friede sei auf euch, Bewohner der Gräber unter den Gläubigen und Muslimen",
    "duaSai1": "Wahrlich, As-Safa und Al-Marwa gehören zu den Riten Allahs",
    "duaSai2": "Wir beginnen mit dem, womit Allah begonnen hat",
    "duaArafat1": "Es gibt keinen Gott außer Allah allein, ohne Partner",
    "duaSuhoor1": "Ich beabsichtige, morgen im Monat Ramadan zu fasten",
    "duaRain1": "Wir wurden durch die Gnade Allahs und Seine Barmherzigkeit beregnet",
}
de_translations.update(de_duas)

# =============================================
# RUSSIAN (RU) TRANSLATIONS
# =============================================
ru_translations = {
    "appName": "Азан и Хикая",
    "appTitle": "Азан и Хикая",
    "fajr": "Фаджр",
    "dhuhr": "Зухр",
    "asr": "Аср",
    "maghrib": "Магриб",
    "isha": "Иша",
    "fajrLabel": "Фаджр (утренняя молитва)",
    "qibla": "Кибла",
    "duas": "Дуа",
    "duasAndDhikr": "Дуа и Зикр",
    "adhkar": "Азкар",
    "tasbih": "Тасбих",
    "zakat": "Закят",
    "shop": "Магазин",
    "juz": "Джуз",
    "subhanAllah": "СубханАллах",
    "alhamdulillah": "АльхамдулиЛлях",
    "allahuAkbar": "Аллаху Акбар",
    "istighfar": "Истигфар",
    "name": "Имя",
    "km": "км",
    "auto": "Авто",
    "info": "Инфо",
    "ramadanCountdown": "Обратный отсчёт до Рамадана",
    "ramadanMubarak": "Рамадан Мубарак! 🌙",
    "eidFitr": "Ид аль-Фитр",
    "eidAdha": "Ид аль-Адха",
    "iftar": "Ифтар",
    "catRamadan": "Рамадан",
    "mediaText": "Текст",
    "mediaVideo": "Видео",
    "mediaAudio": "Аудио",
    "liveLabel": "Прямой эфир",
    "pauseBtn": "Пауза",
    "textOption": "Текст",
    "videoOption": "Видео",
    "linkOption": "Ссылка",
    "trendsTab": "Тренды",
    "videosTab": "Видео",
    "videosCategory": "Видео 🎬",
    "duaCategory": "Дуа 🤲",
    "rizqCategory": "Ризк 🤲",
    "storyHadith": "Хадис",
    "storyRamadan": "Рамадан",
    "storyDua": "Дуа",
    "hadithCategory": "Хадис",
    "videoTab": "Видео",
    "videosLabel": "Видео",
    "videos": "Видео",
    "addVideo": "Видео",
    "hijriCalendar2": "Хиджри",
    "hijriMonth1": "Мухаррам",
    "hijriMonth2": "Сафар",
    "hijriMonth3": "Раби аль-Авваль",
    "hijriMonth4": "Раби ас-Сани",
    "hijriMonth9": "Рамадан",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "turkish": "Türkçe",
    "urdu": "اردو",
    "indonesian": "Bahasa Indonesia",
    "reciterSudais": "Абдуррахман Ас-Судайс",
    "reciterShuraym": "Сауд Аш-Шурайм",
    "reciterAbdulbasit": "Абдул Басит Абдус Самад",
    "reciterBudair": "Салах Аль-Будайр",
    "reciterAhmad": "Абдулазиз Аль-Ахмад",
    "reciterTablawi": "Мухаммад Ат-Таблави",
    "reciterYasser": "Яссер Ад-Досари",
    "reciterNasser": "Нассер Аль-Катами",
    "reciterBanna": "Махмуд Али Аль-Банна",
    "reciterFares": "Фарес Аббад",
    "reciterGhamdi": "Саад Аль-Гамди",
    "reciterAkhdar": "Ибрахим Аль-Ахдар",
    "reciterBasitMurattal": "Абдул Басит - Муратталь",
    "athanQuds": "Аль-Акса",
    "athanAbdulbasit": "Абдул Басит",
    "athanAbdulBasit": "Абдул Басит Абдус Самад",
    "athanShahat": "Шахат",
    "athanSaqqaf": "Ас-Саккаф",
    "quickQibla": "Кибла",
    "quickDuas": "Дуа",
    "quickZakat": "Закят",
    "nisabIn": "Нисаб в",
    "nisab": "Нисаб",
    "zakatNisabTitle": "Нисаб Закята",
    "zakatNisab": "Нисаб",
    "zakatTitle": "Калькулятор Закята",
    "zakatGold": "Золото",
    "zakatSilver": "Серебро",
    "zakatCash": "Наличные",
    "zakatResult": "Сумма Закята",
    "zakatCalculate": "Рассчитать Закят",
    "goldLabel": "Золото",
    "ruqyahAyatKursi": "Аят аль-Курси",
    "ruqyahMuawwidhat": "Аль-Муаввизат",
    "ruqyahMuawwidhatDesc": "Аль-Фаляк и Ан-Нас",
    "ruqyahAyatKursiTitle": "Аят аль-Курси",
    "ruqyahRefFalaq": "Аль-Фаляк: 1-5",
    "ruqyahRefNas": "Ан-Нас: 1-6",
    "ruqyahRefIkhlas": "Аль-Ихляс: 1-4",
    "refBukhari": "Аль-Бухари",
    "refMuslim": "Муслим",
    "refBukhariMuslim": "Аль-Бухари и Муслим",
    "refAbuDawud": "Абу Дауд",
    "refIbnMajah": "Ибн Маджа",
    "goalStrengthenFaithDesc": "СубханАллах ва бихамдих",
    "goalQuranRewardDesc": "Куль хува Аллаху Ахад",
    "goalRepentanceDesc": "Астагфируллах аль-Азым",
    "dailyDhikr": "СубханАллах ва бихамдих, СубханАллах аль-Азым",
    "namePlaceholder": "Имя *",
    "namesOfAllahTitle": "Прекрасные имена Аллаха",
    "namesOfAllahVerse": "У Аллаха прекрасные имена, так взывайте к Нему ими",
    "searchByNameOrMeaning": "Поиск по имени, значению или номеру...",
    "hideSearch": "Скрыть поиск",
    "searchLabel": "Поиск",
    "nameCount": "имя(ён)",
    "meaningLabel": "Значение",
    "favoriteName": "Избранное",
    "installInstructions": "Шаги установки",
    "stepNumber": "Шаг",
    "periodTrackerTitle": "Трекер цикла",
    "periodStart": "Начало цикла",
    "periodEnd": "Конец цикла",
    "periodDays": "дней",
    "loadingData": "Загрузка...",
    "copy": "Копировать",
    "copied": "Скопировано",
    "selectAll": "Выбрать все",
    "deselectAll": "Снять выбор",
    "sortBy": "Сортировать по",
    "filterBy": "Фильтровать по",
    "thisWeek": "Эта неделя",
    "thisMonth": "Этот месяц",
    "gram": "грамм",
    "amount": "Сумма",
    "enterAmount": "Введите сумму",
    "iosStep1Prefix": "Нажмите на",
    "iosStep1Highlight": "кнопку Поделиться",
    "iosStep2Prefix": "Выберите",
    "iosStep2Highlight": "На экран «Домой»",
    "iosStep3Prefix": "Нажмите",
    "iosStep3Highlight": "Добавить",
    "chromeInstallHint": "Откройте приложение в Chrome, затем нажмите меню браузера → «Установить приложение»",
    "gregorianDate": "Григорианский",
    "switchToHijri": "Хиджри календарь",
    "switchToGregorian": "Григорианский календарь",
    "duaSubTawaf": "Таваф",
    "duaSubSuhoor": "Сухур",
    "duaSubIftar": "Ифтар",
    "duaSubIstikhara": "Истихара",
}

# Russian Dua translations
ru_duas = {
    "duaSleep1": "С именем Твоим, о Аллах, я умираю и живу",
    "duaSleep2": "О Аллах, защити меня от Твоего наказания в День, когда Ты воскресишь Своих рабов",
    "duaSleep3": "С именем Твоим, мой Господь, я ложусь и именем Твоим встаю",
    "duaSleep4": "О Аллах, Ты создал мою душу и Ты забираешь её. Тебе принадлежит её смерть и жизнь",
    "duaSleep5": "О Аллах, Господь небес и земли и Господь великого Трона, наш Господь и Господь всего сущего",
    "duaWudu1": "Во имя Аллаха",
    "duaWudu2": "Свидетельствую, что нет бога кроме Аллаха, Единого, без сотоварища",
    "duaWudu3": "О Аллах, сделай меня из кающихся и сделай меня из очищающихся",
    "duaWudu4": "Пречист Ты, о Аллах, и хвала Тебе. Свидетельствую, что нет бога кроме Тебя",
    "duaMosque1": "О Аллах, открой мне врата Твоей милости",
    "duaMosque2": "Прибегаю к Аллаху Великому и Его благородному Лику от проклятого шайтана",
    "duaMosque3": "Во имя Аллаха, и мир и благословение Посланнику Аллаха",
    "duaSalah1": "Пречист Ты, о Аллах, и хвала Тебе. Благословенно имя Твоё",
    "duaSalah2": "Господь наш, даруй нам благо в этом мире и благо в мире ином, и защити нас от мучений Огня",
    "duaSalah3": "О Аллах, я прибегаю к Тебе от мучений могилы и от мучений Огня",
    "duaSalah4": "Господь мой, сделай меня и моё потомство совершающими молитву",
    "duaHome1": "Во имя Аллаха входим, во имя Аллаха выходим, и на Аллаха уповаем",
    "duaHome2": "О Аллах, я прошу Тебя о благе входа и благе выхода",
    "duaClothes1": "Хвала Аллаху, Который одел меня в эту одежду",
    "duaClothes2": "О Аллах, я прошу Тебя о его благе и благе, для которого оно было создано",
    "duaTravel1": "Пречист Тот, Кто подчинил нам это, ведь мы сами не смогли бы это сделать",
    "duaTravel2": "О Аллах, мы просим Тебя о праведности и богобоязненности в этом путешествии",
    "duaTravel3": "О Аллах, я прибегаю к Тебе от трудностей путешествия",
    "duaFood1": "Во имя Аллаха",
    "duaFood2": "Во имя Аллаха, в начале и в конце",
    "duaFood3": "Хвала Аллаху, Который накормил нас, напоил нас и сделал нас мусульманами",
    "duaFood4": "Хвала Аллаху, Который накормил меня этой едой",
    "duaDhikr1": "Пречист Аллах",
    "duaDhikr2": "Хвала Аллаху",
    "duaDhikr3": "Аллах Велик",
    "duaDhikr4": "Нет бога кроме Аллаха, Единого, без сотоварища",
    "duaDhikr5": "Прошу Аллаха о прощении",
    "duaRevival1": "О Господь рассвета",
    "duaRevival2": "О Управляющий сердцами, укрепи моё сердце в Твоей религии",
    "duaRevival3": "О Аллах, я прошу Тебя о полезном знании, благом уделе и принятых деяниях",
    "duaRevival4": "О Аллах, я прошу Тебя о руководстве, богобоязненности, целомудрии и самодостаточности",
    "duaRizq1": "О Аллах, я прибегаю к Тебе от беспокойства и печали, от слабости и лени",
    "duaRizq2": "О Аллах, достаточь мне дозволенным от запретного",
    "duaRizq3": "О Аллах, Господь семи небес, будь мне достаточен во всём",
    "duaKnowledge1": "О Аллах, принеси мне пользу тем, чему Ты меня научил, научи меня тому, что принесёт мне пользу",
    "duaKnowledge2": "Господь мой, прибавь мне знания",
    "duaKnowledge3": "О Аллах, я прошу Тебя о полезном знании, благом уделе и принятых деяниях",
    "duaFaith1": "О Аллах, я прошу Тебя о стойкости в моих делах и решимости в руководстве",
    "duaFaith2": "О Аллах, сделай веру любимой для нас и укрась её в наших сердцах",
    "duaJudgment1": "О Аллах, я прошу Тебя о Рае и о том, что приближает к нему",
    "duaJudgment2": "О Аллах, облегчи мой расчёт",
    "duaForgiveness1": "О Аллах, Ты мой Господь, нет бога кроме Тебя. Ты создал меня и я Твой раб",
    "duaForgiveness2": "Господь наш, мы обидели самих себя, и если Ты не простишь нас и не смилуешься над нами",
    "duaForgiveness3": "Прошу прощения у Аллаха Великого, нет бога кроме Него, Живого, Самодостаточного",
    "duaPraising1": "Пречист Аллах и хвала Ему, столько раз, сколько Его творений",
    "duaPraising2": "Нет бога кроме Аллаха, Единого, без сотоварища. Ему принадлежит власть и хвала",
    "duaFamily1": "Господь наш, даруй нам от наших супругов и потомков отраду глаз",
    "duaFamily2": "Господь мой, сделай меня благодарным за Твою милость",
    "duaFamily3": "О Аллах, вложи любовь между нашими сердцами и примири нас",
    "duaHealth1": "О Аллах, Господь людей, удали болезнь. Исцели, ибо Ты Исцеляющий",
    "duaHealth2": "Во имя Аллаха, уповаю на Аллаха. О Аллах, я прибегаю к Тебе",
    "duaLoss1": "Аллаху принадлежит то, что Он забрал, и Ему принадлежит то, что Он дал",
    "duaLoss2": "Воистину, Аллаху принадлежит то, что Он забрал, и Ему принадлежит то, что Он дал",
    "duaSadness1": "О Аллах, я Твой раб, сын Твоего раба, сын Твоей рабыни. Мой чуб в Твоей руке",
    "duaSadness2": "Нет бога кроме Тебя. Пречист Ты, воистину я был из числа несправедливых",
    "duaPatience1": "О Аллах, нет лёгкости кроме той, что Ты сделал лёгкой",
    "duaPatience2": "Достаточен нам Аллах и прекрасный Он Покровитель",
    "duaDebt1": "О Аллах, я прибегаю к Тебе от беспокойства и печали, от слабости и лени",
    "duaDebt2": "О Аллах, достаточь мне дозволенным от запретного",
    "duaDeceased1": "О Аллах, прости их и помилуй их, даруй им благополучие и прости их",
    "duaDeceased2": "О Аллах, прости наших живых и наших мёртвых, присутствующих и отсутствующих",
    "duaHajj1": "Вот я перед Тобой, о Аллах, вот я перед Тобой. У Тебя нет сотоварища",
    "duaHajj2": "О Аллах, это Твой Дом, который Ты сделал священным",
    "duaRamadan1": "О Аллах, Ты Прощающий, Ты любишь прощение, так прости меня",
    "duaRamadan2": "О Аллах, я постился ради Тебя и Твоей пищей разговляюсь",
    "duaNature1": "О Аллах, сделай его благодатным дождём",
    "duaNature2": "О Аллах, вокруг нас, а не на нас",
    "duaGuidance1": "О Аллах, я прошу Тебя о руководстве через Твоё знание и о силе через Твоё могущество",
    "duaGuidance2": "О Аллах, покажи мне истину истиной и даруй мне следовать ей",
    "duaWakeUp1": "Хвала Аллаху, Который оживил нас после того, как умертвил нас",
    "duaWakeUp2": "Нет бога кроме Аллаха, Единого, без сотоварища",
    "duaNightmare1": "Прибегаю к совершенным словам Аллаха от Его гнева и наказания",
    "duaNightmare2": "Прибегаю к Аллаху от проклятого шайтана",
    "duaAfterSalah1": "Прошу Аллаха о прощении. О Аллах, Ты — Мир и от Тебя — мир",
    "duaAfterSalah2": "Нет бога кроме Аллаха, Единого, без сотоварища",
    "duaAfterSalah3": "Нет бога кроме Аллаха, Единого. Нет мощи и силы кроме как от Аллаха",
    "duaDhikr6": "Пречист Аллах и хвала Ему, Пречист Аллах Великий",
    "duaDhikr7": "Нет мощи и силы кроме как от Аллаха",
    "duaDhikr8": "О Аллах, благослови Мухаммада и семью Мухаммада",
    "duaPostPrayer1": "СубханАллах (33x), АльхамдулиЛлях (33x), Аллаху Акбар (33x), затем: Ля иляха иллаЛлах...",
    "duaPostPrayer2": "Аят аль-Курси: Аллах — нет бога кроме Него, Живого, Самодостаточного...",
    "duaMenstruation1": "Хвала Аллаху при любых обстоятельствах",
    "duaGoodManners1": "О Аллах, направь меня к лучшим нравам, ибо никто не направит к ним кроме Тебя",
    "duaGoodManners2": "О Аллах, я прошу Тебя о здоровье, целомудрии, надёжности и хороших нравах",
    "duaVisitSick1": "Не беда, очищение, если пожелает Аллах",
    "duaHappy1": "Хвала Аллаху, по милости Которого совершаются благие дела",
    "duaHappy2": "О Аллах, Тебе хвала, как подобает величию Твоего Лика",
    "duaCondolence1": "Воистину, Аллаху принадлежит то, что Он забрал, и Ему принадлежит то, что Он дал",
    "duaGrave1": "Мир вам, обитатели этих мест из верующих и мусульман",
    "duaSai1": "Воистину, Ас-Сафа и Аль-Марва — из обрядов Аллаха",
    "duaSai2": "Начнём с того, с чего начал Аллах",
    "duaArafat1": "Нет бога кроме Аллаха, Единого, без сотоварища",
    "duaSuhoor1": "Я намереваюсь поститься завтра в месяце Рамадан",
    "duaRain1": "Нам послан дождь по милости Аллаха и Его милосердию",
}
ru_translations.update(ru_duas)

# =============================================
# FRENCH (FR) TRANSLATIONS
# =============================================
fr_translations = {
    "appName": "Azan & Hikaya",
    "appTitle": "Azan & Hikaya",
    "fajr": "Fajr",
    "dhuhr": "Dhuhr",
    "asr": "Asr",
    "maghrib": "Maghrib",
    "isha": "Isha",
    "fajrLabel": "Fajr (prière de l'aube)",
    "qibla": "Qibla",
    "duas": "Duas",
    "duasAndDhikr": "Duas & Dhikr",
    "adhkar": "Adhkar",
    "tasbih": "Tasbih",
    "zakat": "Zakat",
    "shop": "Boutique",
    "juz": "Juz",
    "subhanAllah": "SubhanAllah",
    "alhamdulillah": "Alhamdulillah",
    "allahuAkbar": "Allahu Akbar",
    "istighfar": "Istighfar",
    "name": "Nom",
    "km": "km",
    "auto": "Automatique",
    "info": "Info",
    "ramadanCountdown": "Compte à rebours du Ramadan",
    "ramadanMubarak": "Ramadan Moubarak ! 🌙",
    "eidFitr": "Aïd al-Fitr",
    "eidAdha": "Aïd al-Adha",
    "iftar": "Iftar",
    "catRamadan": "Ramadan",
    "mediaText": "Texte",
    "mediaVideo": "Vidéo",
    "mediaAudio": "Audio",
    "liveLabel": "En direct",
    "pauseBtn": "Pause",
    "textOption": "Texte",
    "videoOption": "Vidéo",
    "linkOption": "Lien",
    "trendsTab": "Tendances",
    "videosTab": "Vidéos",
    "videosCategory": "Vidéos 🎬",
    "duaCategory": "Duas 🤲",
    "rizqCategory": "Rizq 🤲",
    "storyHadith": "Hadith",
    "storyRamadan": "Ramadan",
    "storyDua": "Dua",
    "hadithCategory": "Hadith",
    "videoTab": "Vidéo",
    "videosLabel": "Vidéos",
    "videos": "Vidéos",
    "addVideo": "Vidéo",
    "hijriCalendar2": "Hégirien",
    "hijriMonth1": "Mouharram",
    "hijriMonth2": "Safar",
    "hijriMonth3": "Rabi al-Awwal",
    "hijriMonth4": "Rabi ath-Thani",
    "hijriMonth9": "Ramadan",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "turkish": "Türkçe",
    "urdu": "اردو",
    "indonesian": "Bahasa Indonesia",
    "reciterSudais": "Abdurrahman As-Sudais",
    "reciterShuraym": "Saud Ash-Shuraim",
    "reciterAbdulbasit": "Abdul Basit Abdus Samad",
    "reciterBudair": "Salah Al-Budair",
    "reciterAhmad": "Abdulaziz Al-Ahmad",
    "reciterTablawi": "Muhammad At-Tablawi",
    "reciterYasser": "Yasser Ad-Dosari",
    "reciterNasser": "Nasser Al-Qatami",
    "reciterBanna": "Mahmoud Ali Al-Banna",
    "reciterFares": "Fares Abbad",
    "reciterGhamdi": "Saad Al-Ghamdi",
    "reciterAkhdar": "Ibrahim Al-Akhdar",
    "reciterBasitMurattal": "Abdul Basit - Murattal",
    "athanQuds": "Al-Aqsa",
    "athanAbdulbasit": "Abdul Basit",
    "athanAbdulBasit": "Abdul Basit Abdul Samad",
    "athanShahat": "Shahat",
    "athanSaqqaf": "Al-Saqqaf",
    "quickQibla": "Qibla",
    "quickDuas": "Duas",
    "quickZakat": "Zakat",
    "nisabIn": "Nisab en",
    "nisab": "Nisab",
    "zakatNisabTitle": "Nisab de la Zakat",
    "zakatNisab": "Nisab",
    "zakatTitle": "Calculateur de Zakat",
    "zakatGold": "Or",
    "zakatSilver": "Argent",
    "zakatCash": "Espèces",
    "zakatResult": "Montant de la Zakat",
    "zakatCalculate": "Calculer la Zakat",
    "goldLabel": "Or",
    "ruqyahAyatKursi": "Ayat al-Kursi",
    "ruqyahMuawwidhat": "Al-Muawwidhat",
    "ruqyahMuawwidhatDesc": "Al-Falaq & An-Nas",
    "ruqyahAyatKursiTitle": "Ayat al-Kursi",
    "ruqyahRefFalaq": "Al-Falaq : 1-5",
    "ruqyahRefNas": "An-Nas : 1-6",
    "ruqyahRefIkhlas": "Al-Ikhlas : 1-4",
    "refBukhari": "Al-Bukhari",
    "refMuslim": "Muslim",
    "refBukhariMuslim": "Al-Bukhari & Muslim",
    "refAbuDawud": "Abu Dawud",
    "refIbnMajah": "Ibn Majah",
    "goalStrengthenFaithDesc": "SubhanAllah wa bihamdihi",
    "goalQuranRewardDesc": "Qul Huwa Allahu Ahad",
    "goalRepentanceDesc": "Astaghfirullah al-Azeem",
    "dailyDhikr": "SubhanAllah wa bihamdihi, SubhanAllah al-Azeem",
    "namePlaceholder": "Nom *",
    "namesOfAllahTitle": "Les plus beaux noms d'Allah",
    "namesOfAllahVerse": "À Allah appartiennent les plus beaux noms, invoquez-Le par eux",
    "searchByNameOrMeaning": "Rechercher par nom, signification ou numéro...",
    "hideSearch": "Masquer la recherche",
    "searchLabel": "Recherche",
    "nameCount": "nom(s)",
    "meaningLabel": "Signification",
    "favoriteName": "Favori",
    "installInstructions": "Étapes d'installation",
    "stepNumber": "Étape",
    "periodTrackerTitle": "Suivi du cycle",
    "periodStart": "Début du cycle",
    "periodEnd": "Fin du cycle",
    "periodDays": "jours",
    "loadingData": "Chargement...",
    "copy": "Copier",
    "copied": "Copié",
    "selectAll": "Tout sélectionner",
    "deselectAll": "Tout désélectionner",
    "sortBy": "Trier par",
    "filterBy": "Filtrer par",
    "thisWeek": "Cette semaine",
    "thisMonth": "Ce mois",
    "gram": "gramme",
    "amount": "Montant",
    "enterAmount": "Entrez le montant",
    "iosStep1Prefix": "Appuyez sur le",
    "iosStep1Highlight": "bouton Partager",
    "iosStep2Prefix": "Choisissez",
    "iosStep2Highlight": "Sur l'écran d'accueil",
    "iosStep3Prefix": "Appuyez sur",
    "iosStep3Highlight": "Ajouter",
    "chromeInstallHint": "Ouvrez l'app dans Chrome, puis appuyez sur le menu → « Installer l'application »",
    "gregorianDate": "Grégorien",
    "switchToHijri": "Calendrier hégirien",
    "switchToGregorian": "Calendrier grégorien",
    "duaSubTawaf": "Tawaf",
    "duaSubSuhoor": "Suhoor",
    "duaSubIftar": "Iftar",
    "duaSubIstikhara": "Istikhara",
}

# French Duas (abbreviated for key ones)
fr_duas = {
    "duaSleep1": "En Ton nom, ô Allah, je meurs et je vis",
    "duaSleep2": "Ô Allah, protège-moi de Ton châtiment le Jour où Tu ressusciteras Tes serviteurs",
    "duaSleep3": "En Ton nom, mon Seigneur, je me couche et par Toi je me lève",
    "duaSleep4": "Ô Allah, Tu as créé mon âme et Tu la reprends. À Toi appartient sa mort et sa vie",
    "duaSleep5": "Ô Allah, Seigneur des cieux et de la terre et Seigneur du Trône immense",
    "duaWudu1": "Au nom d'Allah",
    "duaWudu2": "J'atteste qu'il n'y a de dieu qu'Allah, Seul, sans associé",
    "duaWudu3": "Ô Allah, fais-moi parmi ceux qui se repentent et parmi ceux qui se purifient",
    "duaWudu4": "Gloire à Toi, ô Allah, et louange à Toi. J'atteste qu'il n'y a de dieu que Toi",
    "duaMosque1": "Ô Allah, ouvre-moi les portes de Ta miséricorde",
    "duaMosque2": "Je cherche refuge auprès d'Allah le Tout-Puissant contre Satan le maudit",
    "duaMosque3": "Au nom d'Allah, et paix et bénédictions sur le Messager d'Allah",
    "duaSalah1": "Gloire à Toi, ô Allah, et louange à Toi. Béni soit Ton nom",
    "duaSalah2": "Notre Seigneur, accorde-nous le bien dans ce monde et le bien dans l'au-delà",
    "duaSalah3": "Ô Allah, je cherche refuge auprès de Toi contre le châtiment de la tombe",
    "duaSalah4": "Mon Seigneur, fais de moi et de ma descendance des priants assidus",
    "duaHome1": "Au nom d'Allah nous entrons, au nom d'Allah nous sortons",
    "duaFood1": "Au nom d'Allah",
    "duaFood2": "Au nom d'Allah, au début et à la fin",
    "duaFood3": "Louange à Allah qui nous a nourris, abreuvés et faits musulmans",
    "duaDhikr1": "Gloire à Allah",
    "duaDhikr2": "Louange à Allah",
    "duaDhikr3": "Allah est le Plus Grand",
    "duaDhikr4": "Il n'y a de dieu qu'Allah, Seul, sans associé",
    "duaDhikr5": "Je demande pardon à Allah",
    "duaRevival1": "Ô Seigneur de l'aube",
    "duaRevival2": "Ô Celui qui retourne les cœurs, affermis mon cœur dans Ta religion",
    "duaRevival3": "Ô Allah, je Te demande un savoir utile, une subsistance bonne et des actes acceptés",
    "duaRevival4": "Ô Allah, je Te demande la guidance, la piété, la chasteté et l'autosuffisance",
    "duaRizq1": "Ô Allah, je cherche refuge auprès de Toi contre l'anxiété et la tristesse",
    "duaRizq2": "Ô Allah, suffis-moi par le licite contre l'illicite",
    "duaRizq3": "Ô Allah, Seigneur des sept cieux, sois-moi suffisant en toute chose",
    "duaKnowledge1": "Ô Allah, fais-moi bénéficier de ce que Tu m'as enseigné",
    "duaKnowledge2": "Mon Seigneur, augmente mon savoir",
    "duaForgiveness1": "Ô Allah, Tu es mon Seigneur, il n'y a de dieu que Toi. Tu m'as créé et je suis Ton serviteur",
    "duaForgiveness2": "Notre Seigneur, nous nous sommes fait du tort à nous-mêmes",
    "duaForgiveness3": "Je demande pardon à Allah le Tout-Puissant, il n'y a de dieu que Lui",
    "duaFamily1": "Notre Seigneur, accorde-nous la joie de nos épouses et de notre descendance",
    "duaHealth1": "Ô Allah, Seigneur des hommes, enlève la maladie. Guéris, car Tu es le Guérisseur",
    "duaPatience1": "Ô Allah, il n'y a de facilité que ce que Tu as rendu facile",
    "duaPatience2": "Allah nous suffit, Il est le meilleur Garant",
    "duaHajj1": "Me voici, ô Allah, me voici. Tu n'as pas d'associé, me voici",
    "duaRamadan1": "Ô Allah, Tu es Pardonneur, Tu aimes le pardon, alors pardonne-moi",
    "duaRamadan2": "Ô Allah, j'ai jeûné pour Toi et avec Ta subsistance je romps mon jeûne",
    "duaWakeUp1": "Louange à Allah qui nous a redonné la vie après nous avoir fait mourir",
    "duaGuidance1": "Ô Allah, je Te demande Ta guidance par Ton savoir et Ta force par Ton pouvoir",
    "duaGuidance2": "Ô Allah, montre-moi la vérité comme vérité et accorde-moi de la suivre",
    "duaNightmare1": "Je cherche refuge dans les paroles parfaites d'Allah contre Sa colère",
    "duaNightmare2": "Je cherche refuge auprès d'Allah contre Satan le maudit",
    "duaAfterSalah1": "Je demande pardon à Allah. Ô Allah, Tu es la Paix et de Toi vient la paix",
    "duaDhikr6": "Gloire à Allah et louange à Lui, Gloire à Allah le Tout-Puissant",
    "duaDhikr7": "Il n'y a de puissance et de force qu'en Allah",
    "duaDhikr8": "Ô Allah, bénis Muhammad et la famille de Muhammad",
    "duaPostPrayer1": "SubhanAllah (33x), Alhamdulillah (33x), Allahu Akbar (33x), puis: La ilaha illallah...",
    "duaPostPrayer2": "Ayat al-Kursi : Allah - il n'y a de dieu que Lui, le Vivant, le Subsistant...",
    "duaMenstruation1": "Louange à Allah en toutes circonstances",
    "duaGoodManners1": "Ô Allah, guide-moi vers les meilleurs caractères, car nul ne guide vers eux sauf Toi",
    "duaVisitSick1": "Pas de mal, purification, si Allah le veut",
    "duaHappy1": "Louange à Allah, par la grâce duquel les bonnes œuvres s'accomplissent",
    "duaGrave1": "Paix sur vous, habitants de ces demeures parmi les croyants et les musulmans",
    "duaSai1": "Certes, As-Safa et Al-Marwa font partie des rites d'Allah",
    "duaSuhoor1": "J'ai l'intention de jeûner demain au mois de Ramadan",
    "duaRain1": "Nous avons reçu la pluie par la grâce d'Allah et Sa miséricorde",
}
fr_translations.update(fr_duas)

# =============================================
# TURKISH (TR) TRANSLATIONS
# =============================================
tr_translations = {
    "appName": "Ezan ve Hikaye",
    "appTitle": "Ezan ve Hikaye",
    "fajr": "İmsak",
    "dhuhr": "Öğle",
    "asr": "İkindi",
    "maghrib": "Akşam",
    "isha": "Yatsı",
    "fajrLabel": "İmsak (sabah namazı)",
    "qibla": "Kıble",
    "duas": "Dualar",
    "duasAndDhikr": "Dualar ve Zikirler",
    "adhkar": "Zikirler",
    "tasbih": "Tesbih",
    "zakat": "Zekat",
    "shop": "Mağaza",
    "juz": "Cüz",
    "subhanAllah": "SübhanAllah",
    "alhamdulillah": "Elhamdülillah",
    "allahuAkbar": "Allahu Ekber",
    "istighfar": "İstiğfar",
    "name": "İsim",
    "km": "km",
    "auto": "Otomatik",
    "info": "Bilgi",
    "ramadanCountdown": "Ramazan Geri Sayımı",
    "ramadanMubarak": "Ramazan Mübarek! 🌙",
    "eidFitr": "Ramazan Bayramı",
    "eidAdha": "Kurban Bayramı",
    "iftar": "İftar",
    "catRamadan": "Ramazan",
    "mediaText": "Metin",
    "mediaVideo": "Video",
    "mediaAudio": "Ses",
    "liveLabel": "Canlı",
    "pauseBtn": "Duraklat",
    "textOption": "Metin",
    "videoOption": "Video",
    "linkOption": "Bağlantı",
    "trendsTab": "Trendler",
    "videosTab": "Videolar",
    "videosCategory": "Videolar 🎬",
    "duaCategory": "Dualar 🤲",
    "rizqCategory": "Rızık 🤲",
    "storyHadith": "Hadis",
    "storyRamadan": "Ramazan",
    "storyDua": "Dua",
    "hadithCategory": "Hadis",
    "videoTab": "Video",
    "videosLabel": "Videolar",
    "videos": "Videolar",
    "addVideo": "Video",
    "hijriCalendar2": "Hicri",
    "hijriMonth1": "Muharrem",
    "hijriMonth2": "Safer",
    "hijriMonth3": "Rebiülevvel",
    "hijriMonth4": "Rebiülahir",
    "hijriMonth9": "Ramazan",
    "arabic": "العربية",
    "english": "English",
    "french": "Français",
    "turkish": "Türkçe",
    "urdu": "اردو",
    "indonesian": "Bahasa Indonesia",
    "reciterSudais": "Abdurrahman es-Sudeys",
    "reciterShuraym": "Suud eş-Şureym",
    "reciterAbdulbasit": "Abdulbasit Abdussamed",
    "reciterBudair": "Salah el-Budayr",
    "reciterAhmad": "Abdulaziz el-Ahmed",
    "reciterTablawi": "Muhammed et-Tablavi",
    "reciterYasser": "Yaser ed-Dosari",
    "reciterNasser": "Nasır el-Katami",
    "reciterBanna": "Mahmud Ali el-Benna",
    "reciterFares": "Faris Abbad",
    "reciterGhamdi": "Saad el-Gamdi",
    "reciterAkhdar": "İbrahim el-Ahdar",
    "reciterBasitMurattal": "Abdulbasit - Murattel",
    "athanQuds": "Kudüs",
    "athanAbdulbasit": "Abdulbasit",
    "athanAbdulBasit": "Abdulbasit Abdussamed",
    "athanShahat": "Şahat",
    "athanSaqqaf": "es-Sakkaf",
    "quickQibla": "Kıble",
    "quickDuas": "Dualar",
    "quickZakat": "Zekat",
    "nisabIn": "Nisab",
    "nisab": "Nisab",
    "zakatNisabTitle": "Zekat Nisabı",
    "zakatNisab": "Nisab",
    "zakatTitle": "Zekat Hesaplayıcı",
    "zakatGold": "Altın",
    "zakatSilver": "Gümüş",
    "zakatCash": "Nakit",
    "zakatResult": "Zekat Miktarı",
    "zakatCalculate": "Zekat Hesapla",
    "goldLabel": "Altın",
    "ruqyahAyatKursi": "Ayetel Kürsi",
    "ruqyahMuawwidhat": "Muavvizeteyn",
    "ruqyahMuawwidhatDesc": "Felak ve Nas Sureleri",
    "ruqyahAyatKursiTitle": "Ayetel Kürsi",
    "ruqyahRefFalaq": "Felak: 1-5",
    "ruqyahRefNas": "Nas: 1-6",
    "ruqyahRefIkhlas": "İhlas: 1-4",
    "refBukhari": "Buhari",
    "refMuslim": "Müslim",
    "refBukhariMuslim": "Buhari ve Müslim",
    "refAbuDawud": "Ebu Davud",
    "refIbnMajah": "İbn Mace",
    "goalStrengthenFaithDesc": "SübhanAllah ve bihamdihi",
    "goalQuranRewardDesc": "Kul hüvallahu ehad",
    "goalRepentanceDesc": "Estağfirullah el-Azim",
    "dailyDhikr": "SübhanAllah ve bihamdihi, SübhanAllah el-Azim",
    "namePlaceholder": "İsim *",
    "namesOfAllahTitle": "Allah'ın Güzel İsimleri",
    "namesOfAllahVerse": "En güzel isimler Allah'ındır, O'na onlarla dua edin",
    "searchByNameOrMeaning": "İsim, anlam veya numara ile ara...",
    "hideSearch": "Aramayı gizle",
    "searchLabel": "Ara",
    "nameCount": "isim",
    "meaningLabel": "Anlam",
    "favoriteName": "Favori",
    "installInstructions": "Kurulum Adımları",
    "stepNumber": "Adım",
    "periodTrackerTitle": "Dönem Takipçisi",
    "periodStart": "Dönem Başlangıcı",
    "periodEnd": "Dönem Sonu",
    "periodDays": "gün",
    "loadingData": "Yükleniyor...",
    "copy": "Kopyala",
    "copied": "Kopyalandı",
    "selectAll": "Tümünü Seç",
    "deselectAll": "Seçimi Kaldır",
    "sortBy": "Sırala",
    "filterBy": "Filtrele",
    "thisWeek": "Bu Hafta",
    "thisMonth": "Bu Ay",
    "gram": "gram",
    "amount": "Miktar",
    "enterAmount": "Miktarı girin",
    "iosStep1Prefix": "Paylaş",
    "iosStep1Highlight": "düğmesine basın",
    "iosStep2Prefix": "Seçin",
    "iosStep2Highlight": "Ana Ekrana Ekle",
    "iosStep3Prefix": "Basın",
    "iosStep3Highlight": "Ekle",
    "chromeInstallHint": "Chrome'da uygulamayı açın, tarayıcı menüsüne → \"Uygulamayı yükle\" ye dokunun",
    "gregorianDate": "Miladi",
    "switchToHijri": "Hicri Takvim",
    "switchToGregorian": "Miladi Takvim",
    "duaSubTawaf": "Tavaf",
    "duaSubSuhoor": "Sahur",
    "duaSubIftar": "İftar",
    "duaSubIstikhara": "İstihare",
}

# Turkish Duas
tr_duas = {
    "duaSleep1": "Allah'ım, Senin adınla ölürüm ve dirilirim",
    "duaSleep2": "Allah'ım, kullarını dirilttiğin gün azabından beni koru",
    "duaSleep3": "Rabbim, Senin adınla yanımı koydum ve Senin adınla kaldırırım",
    "duaSleep4": "Allah'ım, ruhumu Sen yarattın ve onu Sen alırsın. Ölümü ve hayatı Sana aittir",
    "duaSleep5": "Allah'ım, göklerin ve yerin Rabbi, büyük Arş'ın Rabbi, Rabbimiz ve her şeyin Rabbi",
    "duaWudu1": "Allah'ın adıyla",
    "duaWudu2": "Allah'tan başka ilah olmadığına ve Muhammed'in O'nun kulu ve elçisi olduğuna şehadet ederim",
    "duaWudu3": "Allah'ım, beni tevbe edenlerden ve temizlenenlerden eyle",
    "duaWudu4": "Sübhansın Allah'ım, Sana hamd ederim. Senden başka ilah olmadığına şehadet ederim",
    "duaMosque1": "Allah'ım, bana rahmetinin kapılarını aç",
    "duaMosque2": "Kovulmuş şeytandan yüce Allah'a sığınırım",
    "duaMosque3": "Bismillah, salat ve selam Rasulullah'a",
    "duaSalah1": "Sübhansın Allah'ım, Sana hamd olsun. İsmin mübarektir, şanın yücedir",
    "duaSalah2": "Rabbimiz, bize dünyada da iyilik ver, ahirette de iyilik ver, bizi ateş azabından koru",
    "duaSalah3": "Allah'ım, kabir azabından, cehennem azabından Sana sığınırım",
    "duaSalah4": "Rabbim, beni ve zürriyetimi namaz kılanlardan eyle",
    "duaHome1": "Allah'ın adıyla gireriz, Allah'ın adıyla çıkarız, Rabbimiz Allah'a tevekkül ederiz",
    "duaFood1": "Bismillah",
    "duaFood2": "Başında da sonunda da Bismillah",
    "duaFood3": "Bizi yediren, içiren ve Müslüman kılan Allah'a hamd olsun",
    "duaDhikr1": "SübhanAllah",
    "duaDhikr2": "Elhamdülillah",
    "duaDhikr3": "Allahu Ekber",
    "duaDhikr4": "Allah'tan başka ilah yoktur, O tektir, ortağı yoktur",
    "duaDhikr5": "Estağfirullah",
    "duaRevival1": "Ey şafağın Rabbi",
    "duaRevival2": "Ey kalpleri çeviren, kalbimi dinin üzere sabit kıl",
    "duaRevival3": "Allah'ım, faydalı ilim, helal rızık ve kabul olunan amel isterim",
    "duaRevival4": "Allah'ım, Senden hidayet, takva, iffet ve gönül zenginliği isterim",
    "duaRizq1": "Allah'ım, kaygıdan, hüzünden, acizlikten, tembellikten Sana sığınırım",
    "duaRizq2": "Allah'ım, bana haram yerine helal olanla yetecek kadar ver",
    "duaKnowledge1": "Allah'ım, bana öğrettiklerinle fayda ver, fayda verecek şeyleri öğret",
    "duaKnowledge2": "Rabbim, ilmimi artır",
    "duaForgiveness1": "Allah'ım, Sen benim Rabbimsin, Senden başka ilah yoktur. Beni Sen yarattın",
    "duaForgiveness2": "Rabbimiz, biz kendimize zulmettik. Bizi bağışlamazsan ziyana uğrayanlardan oluruz",
    "duaForgiveness3": "Yüce Allah'tan bağışlanma dilerim. O'ndan başka ilah yoktur, Hayy ve Kayyum olan",
    "duaFamily1": "Rabbimiz, eşlerimizden ve çocuklarımızdan göz aydınlığı ver",
    "duaHealth1": "Allah'ım, insanların Rabbi, hastalığı gider. Şifa ver, çünkü Şafi Sensin",
    "duaPatience1": "Allah'ım, Senin kolaylaştırdığından başka kolay olan yoktur",
    "duaPatience2": "Allah bize yeter, O ne güzel vekildir",
    "duaHajj1": "Lebbeyk Allahümme lebbeyk, ortağın yoktur, lebbeyk",
    "duaRamadan1": "Allah'ım, Sen affedicisin, affetmeyi seversin, beni affet",
    "duaRamadan2": "Allah'ım, Senin için oruç tuttum ve Senin rızkınla iftar açtım",
    "duaWakeUp1": "Bizi öldürdükten sonra dirilten Allah'a hamd olsun",
    "duaGuidance1": "Allah'ım, ilminle Senden hayır dilerim, kudretinle Senden güç isterim",
    "duaGuidance2": "Allah'ım, hakkı hak olarak göster ve ona uymayı nasip et",
    "duaNightmare1": "Allah'ın gazabından ve azabından O'nun eksiksiz kelimelerine sığınırım",
    "duaNightmare2": "Kovulmuş şeytandan Allah'a sığınırım",
    "duaAfterSalah1": "Estağfirullah. Allah'ım, Sen Selam'sın ve selamet Sendendir",
    "duaDhikr6": "SübhanAllah ve bihamdihi, SübhanAllah el-Azim",
    "duaDhikr7": "Güç ve kuvvet ancak Allah'tandır",
    "duaDhikr8": "Allah'ım, Muhammed'e ve ailesine salat eyle",
    "duaPostPrayer1": "SübhanAllah (33x), Elhamdülillah (33x), Allahu Ekber (33x), sonra: La ilahe illallah...",
    "duaPostPrayer2": "Ayetel Kürsi: Allah, O'ndan başka ilah yoktur, Hayy ve Kayyum olan...",
    "duaMenstruation1": "Her durumda Allah'a hamd olsun",
    "duaGoodManners1": "Allah'ım, beni en güzel ahlaka yönelt, çünkü ona ancak Sen yöneltirsin",
    "duaVisitSick1": "Geçmiş olsun, inşallah şifadır",
    "duaHappy1": "Nimeti ile salih ameller tamam olan Allah'a hamd olsun",
    "duaGrave1": "Selam olsun size, ey müminler ve Müslümanlar diyarının sakinleri",
    "duaSai1": "Şüphesiz Safa ve Merve Allah'ın nişanelerindendir",
    "duaSuhoor1": "Ramazan ayında yarın oruç tutmaya niyet ettim",
    "duaRain1": "Allah'ın lütuf ve rahmetiyle bize yağmur yağdırıldı",
}
tr_translations.update(tr_duas)

# =============================================
# APPLY TRANSLATIONS
# =============================================
all_translations = {
    'de': de_translations,
    'ru': ru_translations,
    'fr': fr_translations,
    'tr': tr_translations,
}

for lang, translations in all_translations.items():
    data = locales[lang]
    updated = 0
    for key, value in translations.items():
        if key in data:
            data[key] = value
            updated += 1
    with open(f'/app/frontend/src/locales/{lang}.json', 'w') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print(f'{lang}: Updated {updated} translations')

# Final stats
for lang in ['de', 'ru', 'fr', 'tr']:
    with open(f'/app/frontend/src/locales/{lang}.json') as f:
        data = json.load(f)
    same = sum(1 for k in en if k in data and data[k] == en[k])
    print(f'{lang}: {same} keys still same as English ({same*100//len(en)}%)')
