#!/usr/bin/env python3
"""Dutch (nl) translations for Azan & Hikaya app"""
import json, os

NL = {
  "calendar": "Kalender",
  "tracker": "Gebedstracker",
  "timeRemaining": "Resterende tijd",
  "today": "Vandaag",
  "hijriDate": "Hijri-datum",
  "detectLocation": "Locatie detecteren",
  "quickAccess": "Snelle toegang",
  "distanceToMakkah": "Afstand tot Mekka",
  "bookmarks": "Bladwijzers",
  "count": "Aantal",
  "total": "Totaal",
  "morningAdhkar": "Ochtend-Adhkar",
  "eveningAdhkar": "Avond-Adhkar",
  "completed": "Voltooid",
  "days": "Dagen",
  "zakatCalculator": "Zakat-calculator",
  "noResults": "Geen resultaten",
  "loginPrompt": "Log in om uw voortgang op alle apparaten op te slaan",
  "loginSignup": "Inloggen / Registreren",
  "loginWithGoogle": "Inloggen met Google",
  "name": "Naam",
  "email": "E-mail",
  "password": "Wachtwoord",
  "signup": "Registreren",
  "noAccount": "Heeft u geen account?",
  "hasAccount": "Heeft u al een account?",
  "yourIslamicApp": "Uw uitgebreide islamitische app",
  "loginSuccess": "Succesvol ingelogd",
  "signupSuccess": "Account aangemaakt! Controleer uw e-mail",
  "addedToFavorites": "Toegevoegd aan favorieten",
  "removedFromFavorites": "Verwijderd uit favorieten",
  "loginToSave": "Log in om favorieten op te slaan",
  "languageChanged": "Taal gewijzigd",
  "ayahs": "Ayat",
  "ramadanCountdown": "Ramadan aftelling",
  "daysRemaining": "Dagen resterend",
  "upcomingEvents": "Aankomende evenementen",
  "newYear": "Islamitisch nieuwjaar",
  "ashura": "Dag van Ashura",
  "israMiraj": "Isra en Miraj",
  "shaabanMid": "Mid-Sha'ban nacht",
  "ramadanStart": "Begin Ramadan",
  "hajjStart": "Begin Hajj",
  "dayArafah": "Dag van Arafah",
  "cashBalance": "Contanten en banksaldo",
  "goldValue": "Goudwaarde",
  "silverValue": "Zilverwaarde",
  "stocksInvestments": "Aandelen en investeringen",
  "debtsOwed": "Schulden aan u",
  "calculateZakat": "Bereken Zakat",
  "yourZakat": "Uw Zakat (2,5%)",
  "belowNisab": "Uw vermogen is onder de Nisab",
  "revelationMeccan": "Mekkaans",
  "revelationMedinan": "Medinaans",
  "notificationsEnabled": "Azan-meldingen ingeschakeld 🔔",
  "notificationsDisabled": "Azan-meldingen uitgeschakeld",
  "notificationsDenied": "Meldingen niet toegestaan",
  "loginToSaveBookmarks": "Log in om bladwijzers op te slaan",
  "surahAddedToFav": "Surah toegevoegd aan favorieten",
  "surahRemovedFromFav": "Surah verwijderd uit favorieten",
  "loginToSaveProgress": "Log in om uw voortgang op alle apparaten op te slaan",
  "sunday": "Zo", "monday": "Ma", "tuesday": "Di", "wednesday": "Wo",
  "thursday": "Do", "friday": "Vr", "saturday": "Za",
  "qiblaFromNorth": "vanuit het noorden", "qiblaFromEast": "vanuit het oosten",
  "qiblaFromSouth": "vanuit het zuiden", "qiblaFromWest": "vanuit het westen",
  "duasAndDhikr": "Duas en Dhikr", "daily": "Dagelijks",
  "otherDuas": "Overig", "occasional": "Gelegenheidsduas",
  "subCategories": "secties", "totalDuas": "dua",
  "duaSubBeforeSleep": "Voor het slapen", "duaSubAfterWakeUp": "Na het ontwaken",
  "duaSubNightmare": "Bij nachtmerries", "duaSubBeforeWudu": "Voor Wudu",
  "duaSubAfterWudu": "Na Wudu", "duaSubEnteringMosque": "Moskee binnengaan",
  "duaSubLeavingMosque": "Moskee verlaten", "duaSubOpeningSalah": "Gebed openen",
  "duaSubDuringSalah": "Tijdens het gebed", "duaSubAfterSalah": "Na het gebed",
  "duaSubEnteringHome": "Huis binnengaan", "duaSubLeavingHome": "Huis verlaten",
  "duaSubWearingNew": "Nieuwe kleding dragen", "duaSubRemovingClothes": "Kleding uitdoen",
  "duaSubSeeingSomeoneNew": "Iemand in nieuwe kleding zien",
  "duaSubStartTravel": "Begin van de reis", "duaSubReturnTravel": "Terugkeer van reis",
  "duaSubRidingVehicle": "In een voertuig rijden",
  "duaSubBeforeEating": "Voor het eten", "duaSubAfterEating": "Na het eten",
  "duaSubDrinking": "Bij het drinken", "duaSubGuestFood": "Als gast",
  "duaSubMorningAdhkar": "Ochtend-Adhkar", "duaSubEveningAdhkar": "Avond-Adhkar",
  "duaSubGeneralDhikr": "Algemene Dhikr", "duaSubProtectionAdhkar": "Beschermings-Adhkar",
  "duaSubSalawat": "Salawat op de Profeet", "duaSubImmediateAfter": "Direct na het gebed",
  "duaSubTasbeehAfter": "Tasbeeh na het gebed", "duaSubAskingRizq": "Vragen om voorziening",
  "duaSubSeekingKnowledge": "Kennis zoeken", "duaSubBeforeExam": "Voor examen",
  "duaSubStrengtheningFaith": "Geloof versterken",
  "duaSubProtectionHereafter": "Bescherming in het hiernamaals",
  "duaSubSeekingForgiveness": "Vergeving zoeken", "duaSubPraisingAllah": "Allah prijzen",
  "duaSubForChildren": "Voor kinderen", "duaSubForParents": "Voor ouders",
  "duaSubForSpouse": "Voor echtgeno(o)t(e)", "duaSubWhenSick": "Bij ziekte",
  "duaSubVisitingSick": "Zieken bezoeken",
  "duaSubWhenAfflicted": "Bij beproeving", "duaSubAnxietyRelief": "Angstverlichting",
  "duaSubHappiness": "Geluk", "duaSubAskingPatience": "Vragen om geduld",
  "duaSubPayingDebt": "Schuld betalen", "duaSubDhikrDuringPeriod": "Dhikr tijdens menstruatie",
  "duaSubFuneralPrayer": "Begrafenisgebed", "duaSubCondolences": "Condoleances",
  "duaSubVisitingGrave": "Graven bezoeken",
  "duaSubSaiBetween": "Sa'i tussen Safa en Marwa",
  "duaSubArafat": "Dag van Arafat",
  "duaSubWhenRaining": "Bij regen", "duaSubThunderStorm": "Onweer",
  "duaSubWhenWindy": "Bij wind", "duaSubGoodCharacter": "Goed karakter",
  "duaSubMakingDecision": "Beslissingen nemen",
  "quickQuran": "Koran", "quickDuas": "Duas", "quickStories": "Verhalen",
  "nextPrayerLabel": "Volgend gebed", "prayerTracking": "Gebedsvolging",
  "athanLabel": "Azan", "enableLocation": "Locatie inschakelen",
  "mosqueTimes": "Moskeetijden", "chooseNearbyMosque": "Kies nabijgelegen moskee",
  "moreLabel": "Meer", "liveLabel": "Live",
  "unlinkMosque": "Ontkoppelen", "mosqueUnlinked": "Moskee ontkoppeld",
  "ramadanChallenge": "Ramadan-uitdaging", "duaOfDay": "Dua van de dag",
  "readWithTranslation": "Lees met vertaling",
  "quranCompletion": "📖 Koran voltooiing",
  "startDailyRecitation": "Begin dagelijkse recitatie",
  "setYourPace": "Stel uw tempo in en ontvang dagelijkse herinneringen",
  "setQuranGoal": "Stel Koran-doel in →",
  "hijriCalendarTitle": "Hijri-kalender", "quickAccessLabel": "Snelle toegang",
  "catSleep": "Slaap", "catWudu": "Wudu", "catMosque": "Moskee",
  "catSalah": "Gebed", "catHome": "Thuis", "catClothes": "Kleding",
  "catTravel": "Reizen", "catFood": "Eten", "catDailyDhikr": "Dagelijkse Dhikr",
  "catDailyRevival": "Dagelijkse vernieuwing", "catAfterPrayer": "Na het gebed",
  "catRizq": "Voorziening", "catKnowledge": "Kennis", "catFaith": "Geloof",
  "catJudgment": "Dag des Oordeels", "catForgiveness": "Vergeving",
  "catPraising": "Allah prijzen", "catFamily": "Familie",
  "catHealth": "Gezondheid / Ziekte", "catLoss": "Verlies / Mislukking",
  "catSadness": "Verdriet / Vreugde", "catPatience": "Geduld",
  "catDebt": "Schuld", "catMenstruation": "Tijdens menstruatie",
  "catDeceased": "Overledenen", "catHajj": "Hajj / Umrah",
  "catNature": "Natuur", "catGoodManners": "Goede manieren",
  "catGuidance": "Leiding en beslissingen",
  "duasSubtitle": "Duas en Adhkar uit Koran en Sunnah",
  "searchDua": "Zoek naar een dua...", "resultCount": "resultaat",
  "noResultsFound": "Geen resultaten gevonden", "favoritesLabel": "Favorieten",
  "noFavoriteDuas": "Nog geen favoriete duas", "sectionsLabel": "Secties",
  "storiesTitle": "📖 Ware verhalen",
  "storiesSubtitle": "Deel uw verhaal en inspireer anderen",
  "yourStoryMayGuide": "Uw verhaal kan iemand leiden",
  "shareYourExperience": "Deel uw echte ervaring — tekst, video of audio.\nVerhalen worden beoordeeld voor publicatie.",
  "publishYourStory": "Publiceer nu uw verhaal",
  "loginToPublish": "Log in om uw verhaal te publiceren",
  "chooseCategory": "Kies categorie", "publishStory": "Publiceer verhaal",
  "noStoriesYet": "Nog geen verhalen", "beFirstToShare": "Wees de eerste om te delen!",
  "publishFirstStory": "Publiceer eerste verhaal",
  "catIstighfar": "Istighfar-verhalen", "catSahaba": "Metgezellenverhalen",
  "catRuqyahStory": "Ruqyah-verhalen", "catHawqala": "Hawqala-verhalen",
  "catRizqStory": "Voorzieningsverhalen",
  "mediaText": "Tekst", "mediaVideo": "Video", "mediaAudio": "Audio",
  "ruqyahSubtitle": "Islamitische genezing uit Koran en Sunnah",
  "ruqyahDisclaimer": "⚠️ Ruqyah komt uit de Heilige Koran en de Profetische Sunnah.\nDit gedeelte is voor luisteren en bescherming, geen vervanging voor medische behandeling.",
  "ruqyahCount": "ruqyah", "noRuqyahYet": "Nog geen ruqyah in dit gedeelte",
  "quranSubtitle": "De Heilige Koran",
  "noBookmarksYet": "Nog geen bladwijzers",
  "loginToSaveBookmarksQuran": "Log in om bladwijzers op te slaan",
  "removedFromBookmarks": "Verwijderd uit bladwijzers",
  "addedToBookmarks": "Toegevoegd aan bladwijzers",
  "gregorianCalendar": "Gregoriaans", "hijriCalendar2": "Hijri",
  "nextMonth": "Volgende maand", "prevMonth": "Vorige maand",
  "meaningTranslation": "Vertaling", "newStory": "Nieuw", "allStories": "Alle",
  "general": "Algemeen", "videos": "Video's", "images": "Afbeeldingen",
  "textOnly": "Tekst", "postStory": "Publiceren",
  "storyTitle": "Verhaaltitel...", "storyContent": "Schrijf uw verhaal hier...",
  "selectCategory": "Categorie:", "smartCategory": "Slimme categorie",
  "addImage": "Afbeelding", "addVideo": "Video", "uploading": "Uploaden...",
  "published": "Gepubliceerd! ✨", "writeTitle": "Schrijf titel en verhaal",
  "comments": "Reacties", "noComments": "Geen reacties",
  "addComment": "Reageer...", "storyNotFound": "Verhaal niet gevonden",
  "saved": "Opgeslagen", "unsaved": "Niet opgeslagen", "linkCopied": "Link gekopieerd",
  "noStories": "Geen verhalen", "createStory": "Maak verhaal ✨",
  "viewAll": "Bekijk alles", "morePage": "Meer", "viewProfile": "Bekijk profiel",
  "quickFeatures": "Snelle functies", "rewards": "Beloningen",
  "collectPoints": "Verzamel punten", "aiAssistant": "AI-assistent",
  "askAboutReligion": "Vraag over religie", "shop": "Winkel",
  "featuredItems": "Uitgelichte items", "marketplace": "Marktplaats",
  "islamicProducts": "Islamitische producten", "helpSupport": "Hulp en ondersteuning",
  "contactUs": "Contact", "rateApp": "Beoordeel app",
  "inviteFriend": "Nodig een vriend uit", "donations": "Donaties en hulp",
  "helpNeedy": "Help behoeftigen — Bid voor mijn ouders",
  "loggedOut": "Uitgelogd", "auto": "Auto", "reminders": "Herinneringen",
  "enabled": "Ingeschakeld", "disabled": "Uitgeschakeld",
  "notificationSettings": "Meldingsinstellingen", "fontSize": "Lettergrootte",
  "athanSound": "Azan-geluid",
  "ruqyahSection": "Ruqyah-gedeelte", "explore": "Ontdekken",
  "prayer": "Gebed", "gift": "Cadeau", "followUp": "Opvolging",
  "autoLanguage": "Auto (Apparaat)", "manualLanguage": "Handmatige selectie",
  "languageAutoDetected": "Taal automatisch gedetecteerd van uw apparaat",
  "languageManuallySet": "Taal handmatig ingesteld",
  "resetToAuto": "Reset naar automatisch",
  "acceptCookies": "Accepteren", "rejectCookies": "Weigeren",
  "manageCookies": "Cookies beheren", "necessaryCookies": "Noodzakelijke cookies",
  "analyticsCookies": "Analytische cookies", "savePreferences": "Voorkeuren opslaan",
  "welcome": "Welkom", "loginFailed": "Inloggen mislukt",
  "connectionError": "Verbindingsfout", "loggingIn": "Inloggen...",
  "fillAllFields": "Vul alle velden in",
  "passwordMinLength": "Wachtwoord moet minimaal 6 tekens zijn",
  "wrongCredentials": "Verkeerde e-mail of wachtwoord",
  "accountCreated": "Account aangemaakt",
  "accountCreateError": "Fout bij aanmaken account",
  "enterEmail": "Voer uw e-mail in", "resetLinkSent": "Herstelkoppeling verzonden",
  "forgotPassword": "Wachtwoord vergeten",
  "enterEmailToRecover": "Voer uw e-mail in om uw account te herstellen",
  "sendResetLink": "Verstuur herstelkoppeling", "backToLogin": "Terug naar inloggen",
  "companionApp": "Uw spirituele metgezel", "newAccount": "Nieuw account",
  "continueWith": "Doorgaan met", "fullName": "Volledige naam",
  "passwordHint": "Wachtwoord (min 6 tekens)", "enter": "Inloggen",
  "createAccount": "Account aanmaken", "forgotPasswordQ": "Wachtwoord vergeten?",
  "dontHaveAccount": "Heeft u geen account?", "haveAccount": "Heeft u al een account?",
  "registerNow": "Nu registreren", "loginNow": "Nu inloggen",
  "prayerTimesSource": "Gebedstijden", "prayerTimesCopied": "Gebedstijden gekopieerd",
  "mosqueTimes2": "Moskeetijden", "mosqueUnlinked2": "Moskee ontkoppeld",
  "unlinkLabel": "Ontkoppelen", "todayPrayerTimes": "Gebedstijden van vandaag",
  "nextPrayerIs": "Volgend gebed", "timeLeft": "resterend",
  "changeMosque": "Moskee wijzigen", "chooseYourMosque": "Kies uw moskee",
  "searchNearbyMosque": "Zoek naar nabijgelegen moskee",
  "now": "nu", "loginFirst": "Log eerst in",
  "story": "verhaal", "shared": "Gedeeld", "pullDown": "Trek omlaag",
  "comment": "Reactie", "uploaded": "Geüpload", "uploadFailed": "Upload mislukt",
  "aiCategorized": "AI-gecategoriseerd", "moreStories": "Meer verhalen",
  "noVideos": "Geen video's", "section": "Sectie", "storyView": "Verhaal",
  "views": "weergaven",
  "voiceNotSupported": "Uw browser ondersteunt geen spraakherkenning",
  "speakNow": "Spreek nu... zoek naar een verhaal",
  "voiceNotRecognized": "Spraak niet herkend, probeer opnieuw",
  "searchStoryOrAuthor": "Zoek naar verhaal of auteur",
  "saySomethingLike": "Zeg iets als",
  "istighfarStoryExample": "Ik wil een verhaal over istighfar",
  "mostViewed": "Meest bekeken", "storiesEveryoneReads": "Verhalen die iedereen leest",
  "showLess": "Minder tonen", "showMore": "Meer",
  "mostInteracted": "Meest interactie", "touchedHearts": "Verhalen die harten raakten",
  "noContentYet": "Nog geen inhoud",
  "publishFirstStoryInspire": "Publiceer uw verhaal en wees de eerste om te inspireren",
  "publishFirst": "Publiceer eerste verhaal", "goBack": "Ga terug",
  "noCommentsYet": "Nog geen reacties", "writeComment": "Schrijf een reactie...",
  "result": "resultaat", "welcomeUser": "Welkom",
  "loginForProfile": "Log in voor uw profiel en verhalen",
  "user": "Gebruiker", "prophets": "Profeten", "companions": "Metgezellen",
  "rizq": "Voorziening", "repentance": "Berouw", "miracles": "Wonderen",
  "editProfile": "Profiel bewerken", "help": "Hulp",
  "supportHelp": "Ondersteuning en hulp",
  "thankYouRating": "Bedankt voor uw beoordeling!",
  "aboutApp": "Over de app", "followers": "volgers", "likes": "likes",
  "follow": "Volgen", "myStories": "Mijn verhalen",
  "savedStories": "Opgeslagen", "likedStories": "Geliked",
  "noStoriesYetProfile": "Nog geen verhalen", "assistant": "Assistent",
  "rememberAllah": "Gedenk Allah en prijs Hem",
  "resetCounter": "Teller resetten?", "chooseDhikr": "Kies dhikr",
  "chooseFromAdhkar": "Kies uit authentieke adhkar",
  "howToUseCompass": "Hoe het kompas te gebruiken",
  "placePhoneFlat": "Leg de telefoon plat horizontaal",
  "onYourPalm": "op uw handpalm",
  "awayFromMetals": "Weg van metalen en elektronica",
  "headphonesLaptop": "koptelefoon, laptop",
  "calibrateCompass": "Kalibreer: beweeg telefoon in achtvorm",
  "severalTimes": "meerdere keren",
  "turnBodyUntil": "Draai uw lichaam tot het bovenaan verschijnt",
  "turnsGreen": "en groen wordt", "understood": "Begrepen",
  "tapToActivate": "Tik hier om het kompas te activeren",
  "compassNotAvailable": "Kompas niet beschikbaar",
  "compassNotSupported": "Uw apparaat ondersteunt geen digitaal kompas of u gebruikt een desktop. Gebruik de weergegeven hoek met een extern kompas.",
  "calibrate": "Kalibreren",
  "lowAccuracy": "Lage nauwkeurigheid - kalibreer door telefoon in achtvorm te bewegen",
  "locationNotDetected": "Locatie niet gedetecteerd - schakel locatiediensten in",
  "thisIsQiblaDirection": "Dit is de Qibla-richting",
  "highAccuracy": "Hoge nauwkeurigheid", "mediumAccuracy": "Gemiddelde nauwkeurigheid",
  "lowAccuracyCalibrate": "Lage nauwkeurigheid - kalibreer alstublieft",
  "realEstateCommercial": "Vastgoed en commercieel eigendom",
  "smartMultiCurrencyCalc": "Slimme multi-valuta calculator",
  "currency": "Valuta",
  "chooseCurrency": "Kies de valuta van uw land voor Nisab-berekening",
  "detecting": "Detecteren...", "chooseCurrencyBtn": "Kies valuta",
  "nisabIn": "Nisab in", "goldGrams": "Goud (85 gram)",
  "silverGrams": "Zilver (595 gram)", "approvedNisab": "Goedgekeurde Nisab",
  "yourAssets": "Uw bezittingen en spaargeld",
  "enterAssetValues": "Voer de waarde in van elk bezitstype in gekozen valuta",
  "calculationDetails": "Berekeningsdetails", "totalAssets": "Totaal bezittingen",
  "nisab": "Nisab", "zakatRate": "Zakat-tarief", "zakatDue": "Te betalen Zakat",
  "noZakatDue": "Geen Zakat verschuldigd",
  "belowNisabMsg": "Uw vermogen is onder de Nisab-drempel",
  "shariaNote": "Islamitische opmerking",
  "zakatNoteText": "Deze calculator gebruikt de zilver-Nisab (595g), de lagere drempel, ten gunste van de armen volgens de meerderheid van geleerden. Het vaste Zakat-tarief is 2,5% van totaal vermogen dat Nisab heeft bereikt en een heel jaar is gehouden.",
  "photoUploaded": "Foto geüpload", "photoUploadFailed": "Foto uploaden mislukt",
  "uploadError": "Upload fout", "nameRequired": "Naam is verplicht",
  "changesSaved": "Wijzigingen opgeslagen", "saveFailed": "Opslaan mislukt",
  "editProfileTitle": "Profiel bewerken",
  "tapCameraToChange": "Tik op camera om foto te wijzigen",
  "enterFullName": "Voer uw volledige naam in",
  "emailCannotChange": "E-mail kan niet worden gewijzigd",
  "newPasswordOptional": "Nieuw wachtwoord (optioneel)",
  "leaveEmptyNoChange": "Laat leeg als geen wijziging",
  "minSixChars": "Moet minimaal 6 tekens zijn",
  "saveChanges": "Wijzigingen opslaan",
  "islamicAssistant": "Islamitische assistent",
  "aiAssistantDesc": "Slimme assistent aangedreven door GPT-5.2 gespecialiseerd in islamitische vragen",
  "poweredBy": "Aangedreven door", "free": "Gratis",
  "question": "vraag", "questionsLeft": "resterend",
  "askMeAnything": "Stel mij een islamitische vraag",
  "taraweehRuling": "Wat is de regel voor het Taraweeh-gebed?",
  "zakatCalcQuestion": "Hoe bereken ik Zakat over vermogen?",
  "pillarsOfIslam": "Wat zijn de zuilen van de Islam?",
  "mosqueEntryDua": "Dua bij het binnengaan van de moskee",
  "watchVideosForPoints": "Bekijk video's om gratis punten te verdienen",
  "writeYourQuestion": "Schrijf uw islamitische vraag",
  "dailyCheckIn": "Dagelijkse check-in",
  "dailyCheckInDesc": "Check dagelijks in en verdien beloningen",
  "complete100Tasbeeh": "Voltooi 100 tasbeeh",
  "quranPage": "Koran-pagina", "readQuranPage": "Lees een pagina uit de Koran",
  "mustLogin": "Moet ingelogd zijn", "yourBalance": "Uw saldo",
  "dayStreak": "Dagelijkse reeks", "totalEarned": "Totaal verdiend",
  "collectRewards": "Verzamel beloningen", "collect": "Verzamelen",
  "storeSection": "Winkel", "buyWithGold": "Koop premiumitems met goud",
  "history": "Geschiedenis", "noTransactionsYet": "Nog geen transacties",
  "installApp": "App installeren", "athanNotifications": "Azan-meldingen",
  "pageNotFound": "Pagina niet gevonden", "backToHome": "Terug naar startpagina",
  "messages": "Berichten", "noMessages": "Nog geen berichten",
  "navHome": "Thuis", "navStories": "Mijn verhalen",
  "navMessages": "Berichten", "navMore": "Meer",
  "holyMosqueAlt": "De Heilige Moskee",
  "disableNotifications": "Meldingen uitschakelen",
  "enableNotificationsLabel": "Meldingen inschakelen",
  "mosqueLabel": "Moskee", "fajrLabel": "Fajr",
  "ramadanCalendarTitle": "Ramadan-kalender 1447",
  "ramadanCalendarDesc": "Dagelijkse duas • Laylat al-Qadr • Suhoor en Iftar",
  "ruqyahAyatKursi": "Ayat al-Kursi",
  "ruqyahAyatKursiDesc": "Voor bescherming en behoud",
  "ruqyahMuawwidhat": "Al-Muawwidhat",
  "ruqyahMuawwidhatDesc": "Al-Falaq en An-Nas",
  "ruqyahBaqara": "Surah Al-Baqarah",
  "ruqyahBaqaraDesc": "Verdrijft duivels",
  "ruqyahMorning": "Ochtend-Adhkar",
  "ruqyahMorningDesc": "Bescherming tegen alle kwaad",
  "closeBanner": "Sluiten", "islamicOccasion": "Islamitische gelegenheid",
  "hideDua": "Dua verbergen", "readDuaBtn": "Lees de Dua ✨",
  "hadithOfDay": "Hadith van de dag",
  "prophetSaid": "De Profeet ﷺ zei:",
  "narratorLabel": "Verteller:", "hadithShareTitle": "📖 Hadith van de dag",
  "dailyGoalsTitle": "Dagelijkse doelen", "completedLabel": "voltooid",
  "goalFasting": "Ramadan vasten", "goalFastingDesc": "Vandaag vasten",
  "goalStrengthenFaith": "Versterk uw geloof",
  "goalQuranReward": "Beloning van 1/3 Koran",
  "goalRepentance": "Voor berouw en vergeving",
  "goalListenQuran": "Luister naar de Koran",
  "goalListenQuranDesc": "Minimaal 15 minuten",
  "goalShareIslam": "Vertel iemand over Islam",
  "goalShareIslamDesc": "Verspreid het goede",
  "suggestedGoalsTitle": "Voorgestelde doelen",
  "goalAdded": "Doel toegevoegd!",
  "goalSurahMulk": "Lees Surah Al-Mulk voor het slapen",
  "goalNafilah": "Verricht Nafilah-gebed",
  "goalSadaqah": "Geef Sadaqah",
  "goalMondayFast": "Vast op maandag of donderdag",
  "goalSurahKahf": "Lees Surah Al-Kahf op vrijdag",
  "dontMissPrayer": "Mis geen enkel gebed",
  "enableNotifDesc": "Schakel meldingen in voor Azan-alerts",
  "notifSettingsBtn": "Meldingsinstellingen",
  "quranPlayerTitle": "Heilige Koran-speler",
  "quranPlayerLabel": "🎧 Koran-speler",
  "listenWhileSleep": "🎧 Luister tijdens het slapen",
  "quranPlayerDesc": "Speel elke Surah met herhaling of auto-play",
  "reciterCount": "reciteerders", "reciterLabel": "Reciteerder",
  "chooseSurah": "Kies een Surah", "searchSurah": "Zoek naar een Surah...",
  "versesCount": "verzen", "changeRepeatMode": "Wijzig herhalingsmodus",
  "nextSurah": "Volgende Surah", "prevSurah": "Vorige Surah",
  "pauseBtn": "Pauzeren", "playBtn": "Afspelen",
  "repeatCurrentSurah": "🔂 Herhaal huidige Surah",
  "repeatAllSurahs": "🔁 Auto-speel alle Surahs",
  "autoNextSurah": "➡️ Auto naar volgende Surah",
  "audioErrorReciter": "Kan audio niet afspelen — probeer andere reciteerder",
  "audioNotAvailable": "Reciteerder audio niet beschikbaar — probeer andere",
  "audioPlayError": "Kan audio niet afspelen",
  "locationErrorMsg": "Schakel locatie in om gebedstijden te tonen",
  "gdprTitle": "Advertentie toestemming",
  "gdprDesc": "Wij gebruiken advertenties om de app te ondersteunen. Volgens Europese wetgeving (AVG) hebben wij uw toestemming nodig voor gepersonaliseerde advertenties.",
  "gdprCollect": "Wat wij verzamelen:",
  "gdprCollect1": "Anoniem advertentie-ID",
  "gdprCollect2": "Type inhoud waarmee u interacteert",
  "gdprCollect3": "Basisapparaatgegevens voor betere advertenties",
  "gdprAccept": "Accepteer gepersonaliseerde advertenties",
  "gdprReject": "Alleen algemene advertenties",
  "gdprChangeNote": "U kunt uw voorkeuren altijd wijzigen in app-instellingen",
  "permLocationTitle": "Locatie",
  "permLocationSubtitle": "Om nauwkeurig gebedstijden voor uw locatie te bepalen",
  "permLocationBenefit1": "Nauwkeurige gebedstijden voor uw stad",
  "permLocationBenefit2": "Juiste Qibla-richting vanaf uw locatie",
  "permLocationBenefit3": "Vind de dichtstbijzijnde moskeeën",
  "permLocationBenefit4": "Bepaal de juiste berekeningsmethode voor uw land",
  "permNotifTitle": "Meldingen",
  "permNotifSubtitle": "Om u te waarschuwen over gebedstijden en Adhkar",
  "permNotifBenefit1": "Azan-geluid wanneer de gebedstijd ingaat",
  "permNotifBenefit2": "Ochtend- en avond-Adhkar op de juiste tijd",
  "permNotifBenefit3": "Fajr- en Qiyam-gebedherinneringen",
  "permNotifBenefit4": "Islamitische gelegenheidsmeldingen",
  "permAllowBtn": "Toestaan", "permSkipBtn": "Niet nu", "permLaterBtn": "Later",
  "permStep": "Stap", "shareStory": "Deel verhaal",
  "readTime": "min leestijd", "featuredContent": "Uitgelichte inhoud",
  "videosCount": "video's", "watchNow": "Bekijk nu",
  "verseOfDay": "Vers van de dag", "commentsTitle": "Reacties",
  "commentFailed": "Reactie verzenden mislukt", "deleted": "Verwijderd",
  "cannotDeleteComment": "Kan deze reactie niet verwijderen",
  "beFirstToComment": "Wees de eerste om te reageren 💬",
  "replyTo": "Antwoord op", "replyToPlaceholder": "Antwoord op",
  "loginToComment": "Log in om te reageren", "reply": "Antwoord",
  "deleteBtn": "Verwijderen",
  "minutesAgo": "{n}m geleden", "hoursAgo": "{n}u geleden", "daysAgo": "{n}d geleden",
  "newPost": "Nieuw bericht",
  "writeYourStory": "Deel uw verhaal of een islamitisch onderwerp...",
  "addTitle": "Voeg titel toe (optioneel)",
  "textOption": "Tekst", "imageOption": "Afbeelding", "videoOption": "Video",
  "linkOption": "Link", "publish": "Publiceren", "publishing": "Publiceren...",
  "addContent": "Inhoud toevoegen",
  "pasteVideoLink": "Plak YouTube- of videolink",
  "loginRequired": "Inloggen vereist",
  "publishSuccess": "Succesvol gepubliceerd ✨", "publishFailed": "Publiceren mislukt",
  "myStoriesTab": "Mijn verhalen", "trendsTab": "Trends", "videosTab": "Video's",
  "allCategory": "Alle", "generalCategory": "Algemeen 📋",
  "videosCategory": "Video's 🎬", "duaCategory": "Duas 🤲",
  "questionCategory": "Vraag ❓", "storyCategory": "Verhaal 📖",
  "adviceCategory": "Advies 💡", "reminderCategory": "Herinnering 🕌",
  "gratitudeCategory": "Dankbaarheid ❤️", "ruqyahCategory": "Ruqyah 🕋",
  "rizqCategory": "Voorziening 🤲",
  "noContent": "Geen inhoud, volg gebruikers en maak inhoud!",
  "loadMore": "Meer laden", "following": "Volgend", "unfollow": "Ontvolgen",
  "shares": "Delingen", "savePost": "Opslaan", "savedPost": "Opgeslagen",
  "sharePost": "Deel bericht", "deletePost": "Verwijder bericht",
  "postDeleted": "Bericht verwijderd", "loginToLike": "Log in om te liken",
  "trending": "Trending 🔥", "searchPlaceholder": "Zoek verhalen...",
  "messagesTitle": "Berichten", "notificationsTab": "Meldingen",
  "messagesTab": "Berichten", "activityTab": "Activiteit",
  "noNotifications": "Geen meldingen",
  "conversationsTitle": "Gesprekken", "noConversations": "Geen gesprekken",
  "athanSoundTitle": "Azan-geluid", "volumeLevel": "Volumeniveau",
  "testSound": "Test geluid",
  "athanSoundDesc": "Kies uw gewenste Azan-geluid",
  "notifSettingsTitle": "Meldingsinstellingen",
  "prayerReminders": "Gebedherinneringen",
  "prayerRemindersDesc": "Waarschuwing voor gebedstijd",
  "athanAlert": "Azan-geluid", "athanAlertDesc": "Speel Azan bij gebedstijd",
  "morningAdhkarDesc": "Dagelijkse ochtend-Adhkar herinnering",
  "eveningAdhkarDesc": "Dagelijkse avond-Adhkar herinnering",
  "fridayReminder": "Vrijdagherinnering",
  "fridayReminderDesc": "Herinnering om Surah Al-Kahf te lezen",
  "generalNotifs": "Algemene meldingen",
  "generalNotifsDesc": "App-nieuws en updates",
  "notifEnabled": "Ingeschakeld", "notifDisabled": "Uitgeschakeld",
  "profileTitle": "Profiel", "loginBtn": "Inloggen", "logoutBtn": "Uitloggen",
  "username": "Gebruikersnaam", "points": "Punten",
  "welcomeAppNotif": "Welkom bij Azan & Hikaya",
  "discoverStories": "Ontdek verhalen — deel uw geloofsmomenten met de Ummah",
  "eveningAdhkarReminder": "Vergeet de avond-Adhkar niet",
  "every_day": "Elke dag",
  "startConversation": "Start een gesprek met vrienden over verhalen",
  "findFriends": "Vrienden vinden", "noActivity": "Geen nieuwe activiteit",
  "activityWillAppear": "Verschijnt hier wanneer iemand op uw berichten reageert",
  "loginPromptTitle": "Inloggen",
  "loginPromptDesc": "Om meldingen en berichten van uw vrienden te ontvangen",
  "loginAction": "Inloggen",
  "remindersStopped": "Herinneringen gestopt",
  "remindersActivated": "Herinneringen geactiveerd",
  "allowNotificationsPlease": "Sta meldingen toe",
  "userDefault": "Gebruiker", "rateAppThanks": "Bedankt voor uw beoordeling!",
  "prayerTimesShareTitle": "Gebedstijden",
  "prayerTimesCopiedToast": "Gebedstijden gekopieerd",
  "mosqueTimesLabel": "Moskeetijden",
  "cancelMosqueLink": "Moskee ontkoppeld", "cancelLabel": "Annuleren",
  "remainingLabel": "Resterend",
  "searchNearbyMosqueDesc": "Zoek naar uw nabijgelegen moskee en selecteer de tijden",
  "compassHowToTitle": "Hoe het kompas te gebruiken",
  "compassStep1": "Leg de telefoon plat op uw handpalm",
  "compassStep2": "Weg van metalen en elektronica",
  "compassStep3": "Kalibreer: beweeg telefoon in achtvorm meerdere keren",
  "compassStep4": "Draai uw lichaam tot 🕋 bovenaan verschijnt en de kleur groen wordt",
  "understoodBtn": "Begrepen ✓",
  "enableCompassBtn": "Tik hier om het kompas in te schakelen",
  "compassUnavailable": "Kompas niet beschikbaar",
  "compassUnavailableDesc": "Uw apparaat ondersteunt geen digitaal kompas. Gebruik de weergegeven hoek met een extern kompas of kaartapp.",
  "calibrateBtn": "Kalibreren",
  "lowAccuracyMsg": "Kompasnauwkeurigheid is laag - beweeg telefoon in ∞-patroon",
  "movePhone8Pattern": "Beweeg uw telefoon in achtvorm...",
  "noLocationDetected": "Locatie niet gedetecteerd - schakel locatiediensten in",
  "fromNorth": "Vanuit het noorden", "fromEast": "Vanuit het oosten",
  "fromSouth": "Vanuit het zuiden", "fromWest": "Vanuit het westen",
  "dhikrRememberAllah": "Gedenk Allah en prijs Hem",
  "resetCounterLabel": "Teller resetten",
  "chooseDhikrTitle": "Kies Dhikr",
  "chooseFromDhikr": "Kies uit authentieke Adhkar",
  "nowLabel": "Nu", "shareOnWhatsapp": "Delen via WhatsApp",
  "copiedToClipboard": "Gekopieerd", "confirm": "Bevestigen",
  "all": "Alle", "new": "Nieuw", "popular": "Populair", "recent": "Recent",
  "yesterday": "Gisteren", "tomorrow": "Morgen", "next": "Volgende",
  "previous": "Vorige", "complete": "Voltooien", "incomplete": "Onvolledig",
  "success": "Succes", "warning": "Waarschuwing", "info": "Info",
  "appTitle": "Azan & Hikaya",
  "appSubtitle": "Gebedstijden • Inspirerende verhalen • Islamitisch leven",
  "minutesReading": "minuten leestijd", "reported": "Gerapporteerd",
  "reportBtn": "Rapporteren", "nextPrayerColon": "Volgend gebed:",
  "surahLabel": "Surah", "ayahLabel": "Ayah",
  "consecutiveDays": "opeenvolgende dagen",
  "storyCategories": "Categorieën", "storyAll": "Algemeen",
  "storyQuran": "Koran", "storyHadith": "Hadith",
  "storyRamadan": "Ramadan", "storyDua": "Dua", "storyAdvice": "Advies",
  "writeStory": "Schrijf uw verhaal", "sendComment": "Verzenden",
  "posts": "Berichten", "prayerNotifications": "Gebedsmeldingen",
  "athanBeforePrayer": "Voor het gebed", "athanAtPrayer": "Bij gebedstijd",
  "allNotifications": "Alle meldingen", "exploreTitle": "Ontdekken",
  "discoverContent": "Ontdek islamitische inhoud",
  "donationTitle": "Donaties", "donateNow": "Nu doneren",
  "donationAmount": "Donatiebedrag", "askQuestion": "Stel een vraag...",
  "questionsRemaining": "vragen resterend", "dailyLimit": "Dagelijkse limiet",
  "watchAdForCredits": "Bekijk een advertentie voor credits",
  "installDesc": "Voeg de app toe aan uw startscherm",
  "installStep1": "Open browser", "installStep2": "Tik op deelknop",
  "installStep3": "Selecteer 'Toevoegen aan startscherm'",
  "pageNotFoundDesc": "De pagina die u zoekt bestaat niet",
  "deleteLabel": "Verwijderen", "writeFirst": "Schrijf eerst iets",
  "errorOccurred": "Er is een fout opgetreden",
  "imageType": "Afbeelding", "embedType": "Insluit",
  "quranCategory": "Koran", "hadithCategory": "Hadith",
  "storiesCategory": "Verhalen", "familyCategory": "Familie",
  "titleOptional": "Titel (optioneel)",
  "shareIdea": "Deel uw idee met de gemeenschap... ✨",
  "videoUrlPlaceholder": "YouTube-URL of videolink",
  "chooseImage": "Kies afbeelding", "chooseVideo": "Kies video",
  "categoryLabel": "Categorie", "publishNow": "Nu publiceren",
  "contentCopied": "Inhoud gekopieerd", "thePost": "Het bericht",
  "videoTab": "Video", "allLabel": "Alle", "noVideosYet": "Nog geen video's",
  "createContent": "Maak inhoud ✨", "recommendedUsers": "Aanbevolen gebruikers",
  "videosLabel": "Video's", "contentNotFound": "Inhoud niet gevonden",
  "adminDashboard": "Admin-dashboard", "myPosts": "Mijn berichten",
  "contactFormTitle": "Contact", "sendMessage": "Stuur bericht",
  "yourName": "Uw naam", "yourEmail": "Uw e-mail",
  "messageContent": "Berichtinhoud", "messageSent": "Bericht verzonden",
  "replyLabel": "Antwoord",
  "notifPrayerAlerts": "Gebedswaarschuwingen",
  "notifPrayerAlertsDesc": "Melding bij elk gebedstijd",
  "notifPrayerReminder": "Gebedherinnering",
  "notifPrayerReminderDesc": "Herinnering minuten voor gebed",
  "notifBefore10Min": "10 min voor",
  "notifPrayerTracker": "Gebedstracker",
  "notifPrayerTrackerDesc": "Herinnering om uw gebeden te loggen",
  "notifQuranListen": "Luister naar de Koran",
  "notifQuranListenDesc": "Dagelijkse Koran-luisterherinnering",
  "notifDhikrDaily": "Dagelijkse Dhikr",
  "notifDhikrDailyDesc": "Dagelijkse herinnering aan Allah",
  "notifStories": "Dagelijkse verhalen",
  "notifStoriesDesc": "Melding voor dagelijkse verhalen",
  "notifFriday": "Speciale vrijdag",
  "notifFridayDesc": "Herinnering om Surah Al-Kahf elke vrijdag te lezen",
  "notifSuhoor": "Suhoor-herinnering",
  "notifSuhoorDesc": "Alleen tijdens Ramadan",
  "notifSuhoorSchedule": "1 uur voor Fajr",
  "notifAtEvening": "20:00", "notifAtNight": "21:00",
  "allowNotifBrowser": "Sta meldingen toe in browserinstellingen",
  "bgNotifEnabled": "Achtergrondmeldingen ingeschakeld ✅ U ontvangt ze ook als de app gesloten is",
  "bgNotifFailed": "Kan achtergrondmeldingen niet inschakelen",
  "enableLocationFirst": "Schakel eerst locatie in voor gebedstijden",
  "allowNotifFirst": "Sta eerst meldingen toe",
  "testNotifSent": "Testmelding verzonden ✅",
  "testNotifFailed": "Kan melding niet verzenden",
  "playingAthan": "Azan wordt afgespeeld... (5 seconden)",
  "playAthanFailed": "Kan audio niet afspelen",
  "notifAndAthan": "Meldingen en Azan",
  "bgAthanNotif": "Achtergrond Azan-meldingen",
  "bgAthanNotifDesc": "Schakel meldingen in om Azan-alerts te ontvangen ook als de app gesloten is",
  "enableNotif": "Meldingen inschakelen",
  "testNotif": "Test melding", "testAthan": "Test Azan",
  "prayersSection": "Gebeden", "selectAthanSound": "Selecteer Azan-geluid",
  "dailyGoalsSection": "Dagelijkse doelen",
  "athanMakkah": "Mekka", "athanMadinah": "Medina",
  "athanTurkish": "Turks", "athanUmayyad": "Umayyad",
  "athanQuds": "Al-Aqsa", "athanSimple": "Eenvoudig alarm",
  "theStory": "Het verhaal", "viewsCount": "weergaven",
  "exploreLabel": "Ontdekken", "cancelSearch": "Annuleren",
  "smartAssistant": "Slimme assistent",
  "tryDifferent": "Probeer andere woorden of gebruik spraakzoeken 🎤",
  "resultsCount": "resultaten", "moreCount": "Meer", "errorShort": "Fout",
  "searchMosqueHere": "Zoek hier...", "noMosquesFound": "Geen moskeeën gevonden",
  "selectMosque": "Selecteer moskee", "nearbyMosques": "Nabijgelegen moskeeën",
  "mosque": "Moskee", "linkedMosque": "Gekoppelde moskee",
  "changeMosqueBtn": "Wijzig moskee",
  "installOnAndroid": "Installeer op Android",
  "installOnIOS": "Installeer op iOS",
  "openChrome": "Open Chrome-browser", "openSafari": "Open Safari-browser",
  "tapThreeDots": "Tik op de drie puntjes ⋮",
  "tapShareBtn": "Tik op deelknop ⎋",
  "selectAddHome": "Selecteer 'Toevoegen aan startscherm'",
  "tapInstall": "Tik 'Installeren'", "tapAdd": "Tik 'Toevoegen'",
  "installNow": "Nu installeren", "appInstalled": "App geïnstalleerd ✅",
  "zakatCurrencySection": "Valuta",
  "zakatCurrencySubtitle": "Kies de valuta van uw land om Nisab te berekenen",
  "zakatSmartCalc": "Slimme multi-valuta calculator",
  "zakatDetecting": "Detecteren...", "zakatChooseCurrency": "Kies valuta",
  "zakatGold85g": "Goud (85 gram)", "zakatSilver595g": "Zilver (595 gram)",
  "zakatAssetsSection": "Uw bezittingen en spaargeld",
  "zakatAssetsSubtitle": "Voer de waarde in van elk bezitstype in de geselecteerde valuta",
  "zakatDetails": "Berekeningsdetails", "zakatTotalAssets": "Totaal bezittingen",
  "zakatNisab": "Nisab", "zakatNotRequired": "Geen Zakat vereist",
  "zakatBelowNisab": "Uw middelen zijn onder de Nisab",
  "zakatLegalNote": "Islamitische juridische opmerking",
  "zakatLegalText": "Deze calculator is gebaseerd op de zilver-Nisab (595 gram), de lagere drempel, ten gunste van de armen. Het vaste Zakat-tarief is 2,5%.",
  "zakatPropertyLabel": "Vastgoed en commercieel eigendom",
  "tapToMarkComplete": "Tik om als voltooid te markeren",
  "duaCategory_morning": "Ochtend-Adhkar", "duaCategory_evening": "Avond-Adhkar",
  "duaCategory_sleep": "Slaap-Adhkar", "duaCategory_prayer": "Adhkar na gebed",
  "duaCategory_food": "Eten-Adhkar", "duaCategory_travel": "Reis-Adhkar",
  "duaCategory_quran": "Koranische Duas", "duaCategory_prophetic": "Profetische Duas",
  "repetitions": "keer", "source": "Bron", "virtue": "Beloning",
  "dhikrStrengthenFaith": "Versterk uw geloof",
  "dhikrQuranReward": "Beloning van een derde van de Koran",
  "dhikrRepentance": "Voor berouw en vergeving",
  "duaTitleAyatKursi": "Ayat al-Kursi (De Troonvers)",
  "duaSubtitleProtection": "Voor bescherming en veiligheid",
  "duaTitleAnxiety": "Dua voor angst en verdriet",
  "duaSubtitleRemoveWorry": "Om zorgen te verwijderen",
  "duaTitleSayyidIstighfar": "Meester van het zoeken van vergeving",
  "duaSubtitleBestIstighfar": "De beste vorm van vergeving zoeken",
  "duaTitleRizq": "Dua voor voorziening",
  "duaSubtitleRizqBlessing": "Voor voorziening en zegeningen",
  "duaTitleEnterMosque": "Dua bij het binnengaan van de moskee",
  "duaSubtitleGoToPrayer": "Bij het gaan naar het gebed",
  "duaTitleTawakkul": "Vertrouwen op Allah",
  "duaSubtitleLeavingHome": "Bij het verlaten van huis",
  "duaTitleHealing": "Dua voor genezing",
  "duaSubtitleForSick": "Voor de zieken",
  "automatic": "Automatisch", "currentMode": "Huidige modus",
  "darkMode": "Donker", "lightMode": "Licht",
  "otherAlerts": "Overige meldingen",
  "pwaNotifTip": "Meldingen werken ook als de app gesloten is! Installeer de app als PWA en schakel meldingen in voor automatische Azan-alerts.",
  "noCommentsYetShort": "Nog geen reacties",
  "trySaying": "Probeer te zeggen",
  "ruqyahPageTitle": "Ruqyah Shariah-behandeling",
  "ruqyahPageSubtitle": "Ruqyah uit de Koran en Sunnah",
  "ruqyahCatAll": "Alle", "ruqyahCatGeneral": "Algemeen",
  "ruqyahCatEye": "Boze oog", "ruqyahCatEnvy": "Jaloezie",
  "ruqyahCatMagic": "Magie", "ruqyahCatTouch": "Djinn-aanraking",
  "ruqyahCatInsomnia": "Slapeloosheid", "ruqyahCatWhispers": "Influisteringen",
  "ruqyahCatProtection": "Bescherming",
  "ruqyahAyatKursiTitle": "Ayat al-Kursi",
  "ruqyahAyatKursiSubtitle": "Voor behoud en bescherming",
  "ruqyahFalaqTitle": "Surah Al-Falaq",
  "ruqyahFalaqSubtitle": "Tegen het kwaad van de schepping",
  "ruqyahNasTitle": "Surah An-Nas",
  "ruqyahNasSubtitle": "Tegen de influisteraar",
  "ruqyahIkhlasTitle": "Surah Al-Ikhlas",
  "ruqyahIkhlasSubtitle": "Gelijk aan een derde van de Koran",
  "ruqyahHomeProtTitle": "Huisbescherming",
  "ruqyahHomeProtSubtitle": "Tegen djinn en duivels",
  "ruqyahRefSahihHadith": "Authentieke hadith",
  "ruqyahReadThrice": "(Lees drie keer 's ochtends en 's avonds)",
  "closeBtn": "Sluiten", "noRuqyahInCategory": "Geen ruqyah in deze categorie",
  "morningAdhkarTitle": "Ochtend- en uitgaans-Adhkar",
  "morningAdhkarSubtitle": "Begin uw dag met het gedenken van Allah",
  "middayDuasTitle": "Duas en smeekbeden",
  "middayDuasSubtitle": "Dua voor ouders, lofprijzing en vergeving",
  "eveningQuranTitle": "Koran-tijd",
  "eveningQuranSubtitle": "Kom lezen en overdenken van de Koran",
  "bedtimeAdhkarTitle": "Slaap-Adhkar",
  "bedtimeAdhkarSubtitle": "Versterk uzelf voor het slapen",
  "favorites": "Favorieten", "yourSavedDuas": "Uw opgeslagen duas",
  "aiSelectedDuas": "AI-geselecteerde duas voor vandaag ✨",
  "youHaveSavedDuas": "U heeft {count} opgeslagen duas",
  "noSavedDuasYet": "U heeft nog geen duas opgeslagen",
  "loadingAdhkar": "Uw adhkar voorbereiden...",
  "tapToSaveFavorites": "Tik ❤️ om favoriete duas op te slaan",
  "backToAdhkar": "Terug naar Adhkar", "newDuas": "Nieuwe Duas",
  "openQuran": "Open de Heilige Koran",
  "trackYourDailyPrayers": "Volg uw dagelijkse gebeden",
  "todayProgress": "Voortgang van vandaag", "todayPrayers": "Gebeden van vandaag",
  "setQuranGoalTitle": "Stel Koran-doel in",
  "howMuchQuranDaily": "Hoeveel tijd wilt u dagelijks Koran lezen?",
  "5minutes": "5 minuten", "10minutes": "10 minuten",
  "20minutes": "20 minuten", "30minutes": "30 minuten", "1hour": "1 uur",
  "dailyReminder": "Dagelijkse herinnering", "createGoal": "Maak doel",
  "quranGoalSaved": "Koran-doel opgeslagen ✅",
  "minutesDaily": "{count} minuten dagelijks",
  "setDailyAdhkar": "Stel dagelijkse Adhkar in",
  "adhkarSettingsSaved": "Adhkar-instellingen opgeslagen ✅",
  "saveSettings": "Instellingen opslaan",
  "rewardsTitle": "Beloningen", "dailyLogin": "Dagelijks inloggen",
  "dailyLoginDesc": "Log dagelijks in en verdien beloning",
  "tasbeeh100": "Tasbeeh 100", "tasbeeh100Desc": "Voltooi 100 tasbeehs",
  "quranPageReward": "Koran-pagina", "quranPageRewardDesc": "Lees een pagina uit de Koran",
  "loginToCollect": "Log in om goud te verzamelen",
  "streakDays": "Dagelijkse reeks", "claimBtn": "Claimen",
  "storeBtn": "Winkel", "logTitle": "Logboek", "storeTitle": "Winkel",
  "storePremiumItems": "Krijg premiumitems met goud",
  "storeCatAll": "Alle", "storeCatFrame": "Kaders", "storeCatTheme": "Thema's",
  "storeCatBadge": "Badges", "storeCatEffect": "Effecten",
  "storeCatMembership": "Lidmaatschappen", "storeCatCharity": "Liefdadigheid",
  "goldLabel": "Goud", "ownedLabel": "In bezit",
  "insufficientGold": "Onvoldoende", "buyBtn": "Kopen",
  "insufficientGoldMsg": "Onvoldoende goudsaldo",
  "purchaseFailed": "Aankoop mislukt",
  "donationsTitle": "Donaties", "requestHelp": "Hulp vragen",
  "importantNotice": "Belangrijke mededeling",
  "donationsDisclaimer": "Wij zijn slechts een platform om mensen te verbinden. Wij dragen geen verantwoordelijkheid. Bid voor de barmhartigheid van onze ouders.",
  "noRequestsNow": "Momenteel geen verzoeken",
  "beFirstToPost": "Wees de eerste om een hulpverzoek te plaatsen",
  "anonymous": "Anoniem", "amountNeeded": "Benodigd bedrag",
  "contactInfo": "Contact", "requestPublished": "Uw verzoek is gepubliceerd",
  "cancelBtn": "Annuleren", "publishBtn": "Publiceren",
  "requestTitlePlaceholder": "Verzoektitel *",
  "requestDescPlaceholder": "Beschrijf de zaak *",
  "contactInfoPlaceholder": "Contactinfo (e-mail of telefoon) *",
  "amountPlaceholder": "Benodigd bedrag (optioneel)",
  "aiAssistantTitle": "Islamitische assistent",
  "poweredByGPT": "Aangedreven door GPT-5.2",
  "freeRemaining": "{count} gratis", "perQuestion": "5/vraag",
  "bismillah": "In de naam van Allah, de Barmhartige, de Genadevolle",
  "loginFirstMsg": "Log eerst in",
  "sampleQ1": "Wat is de regel voor het Taraweeh-gebed?",
  "sampleQ2": "Hoe bereken ik Zakat over vermogen?",
  "sampleQ3": "Wat zijn de zuilen van de Islam?",
  "sampleQ4": "Dua bij het binnengaan van de moskee",
  "contactUsTitle": "Contact", "emailLabel": "E-mail",
  "phoneWhatsapp": "Telefoon / WhatsApp", "directWhatsapp": "Direct WhatsApp",
  "instantChat": "Directe chat",
  "namePlaceholder": "Naam *", "emailPlaceholder": "E-mail",
  "messagePlaceholder": "Uw bericht *", "sendBtn": "Verzenden",
  "sending": "Verzenden...",
  "messageSentSuccess": "Uw bericht is succesvol verzonden! Wij antwoorden snel.",
  "sendError": "Fout bij verzenden",
  "ownerDeveloper": "Eigenaar en ontwikkelaar: Muhammad Al-Rajab",
  "marketplaceTitle": "Islamitische marktplaats",
  "marketplaceSubtitle": "Islamitische producten bij u in de buurt",
  "marketCatAll": "Alle", "marketCatClothing": "Kleding",
  "marketCatBooks": "Boeken", "marketCatAccessories": "Accessoires",
  "marketCatFood": "Eten", "marketCatPerfume": "Parfum",
  "marketCatGeneral": "Algemeen",
  "registerAsVendor": "Registreer als verkoper",
  "wantToSell": "Wilt u uw producten verkopen?",
  "registerAndPublish": "Registreer als verkoper en begin na goedkeuring met publiceren",
  "requestUnderReview": "Uw verzoek wordt beoordeeld",
  "willNotifyApproval": "U wordt bericht bij goedkeuring",
  "enterShopName": "Voer winkelnaam in", "requestSent": "Verzoek verzonden",
  "fillNameAndPrice": "Naam en prijs zijn vereist",
  "productAdded": "Product toegevoegd",
  "aboutUsTitle": "Over ons", "hadithNarrator": "Verteller",
  "installAppTitle": "Installeer Azan & Hikaya-app",
  "installAppSubtitle": "Snelle toegang zonder browser",
  "installBtn": "Installeren",
  "athanAqsa": "Al-Aqsa-moskee (Jeruzalem)",
  "athanDefault": "Eenvoudig alarm",
  "tapToCount": "Tik om te tellen",
  "prayerTimeNow": "Tijd voor gebed",
  "prayerFajr": "Fajr-gebed", "prayerDhuhr": "Dhuhr-gebed",
  "prayerAsr": "Asr-gebed", "prayerMaghrib": "Maghrib-gebed",
  "prayerIsha": "Isha-gebed",
  "athanPlaying": "Azan wordt afgespeeld...",
  "dismiss": "Sluiten",
  "namesOfAllahTitle": "De Mooie Namen van Allah",
  "namesOfAllahVerse": "En aan Allah behoren de mooiste namen, dus roep Hem ermee aan",
  "searchByNameOrMeaning": "Zoek op naam, betekenis of nummer...",
  "hideSearch": "Zoek verbergen", "searchLabel": "Zoeken",
  "nameCount": "naam/namen", "meaningLabel": "Betekenis",
  "favoriteName": "Favoriet",
  "installInstructions": "Installatiestappen", "stepNumber": "Stap",
  "zakatTitle": "Zakat-calculator",
  "zakatGold": "Goud", "zakatSilver": "Zilver", "zakatCash": "Contanten",
  "zakatResult": "Zakat-bedrag", "zakatCalculate": "Bereken Zakat",
  "periodTrackerTitle": "Menstruatietracker",
  "periodStart": "Periode begin", "periodEnd": "Periode einde",
  "periodDays": "dagen", "loadingData": "Laden...",
  "selectAll": "Alles selecteren", "deselectAll": "Alles deselecteren",
  "sortBy": "Sorteren op", "filterBy": "Filteren op",
  "thisWeek": "Deze week", "thisMonth": "Deze maand",
  "gram": "gram", "amount": "Bedrag", "enterAmount": "Voer bedrag in",
  "iosStep1Prefix": "Tik op", "iosStep1Highlight": "Deelknop",
  "iosStep2Prefix": "Kies", "iosStep2Highlight": "Toevoegen aan startscherm",
  "iosStep3Prefix": "Tik", "iosStep3Highlight": "Toevoegen",
  "chromeInstallHint": "Open de app in Chrome, tik op browsermenu → \"App installeren\"",
  "gregorianDate": "Gregoriaans",
  "switchToHijri": "Hijri-kalender", "switchToGregorian": "Gregoriaanse kalender",
  "games": "Spelletjes", "initial": "Initiaal", "medial": "Mediaal", "final": "Finaal",
  "live247": "Live 24/7",
  "nordicPrayerFix": "Gebedstijdaanpassing voor hoge breedtegraden actief",
  "kidsSection": "Kindersectie", "noorGreeting": "Hallo! Ik ben Noor!",
  "startLearning": "Begin te leren",
  "level1Desc": "Leer de eerste 7 Arabische letters (Alif tot Kha)",
  "level1Skill1": "Letterherkenning", "level1Skill2": "Uitspraak",
  "level1Skill3": "Schrijfvormen",
  "level2Title": "Niveau 2: Bouwstenen",
  "level2Desc": "Leer letters 8-14 (Dal tot Sad)",
  "level2Skill1": "Letterverbinding", "level2Skill2": "Woorden lezen",
  "level2Skill3": "Klankoefening",
  "level3Title": "Niveau 3: Sterker worden",
  "level3Desc": "Leer letters 15-21 (Dad tot Qaf)",
  "level3Skill1": "Complexe letters", "level3Skill2": "Zinnen bouwen",
  "level3Skill3": "Luistervaardigheden",
  "level4Title": "Niveau 4: Bijna klaar!",
  "level4Desc": "Leer de laatste letters 22-28 (Kaf tot Ya)",
  "level4Skill1": "Volledig alfabet", "level4Skill2": "Snellezen",
  "level4Skill3": "Schrijfoefening",
  "level5Title": "Niveau 5: Koranwoorden",
  "level5Desc": "Leer essentiële Koranische woordenschat en betekenissen",
  "level5Skill1": "Koran-woordenschat", "level5Skill2": "Betekenis en context",
  "level5Skill3": "Recitatie",
  "tabGuide": "Gids", "tabDuas": "Duas",
}

def apply_translations(locale_file, translations):
    with open(locale_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    en_file = os.path.join(os.path.dirname(locale_file), 'en.json')
    with open(en_file, 'r', encoding='utf-8') as f:
        en_data = json.load(f)
    updated = 0
    for key, translation in translations.items():
        if key in data and key in en_data and data[key] == en_data[key]:
            data[key] = translation
            updated += 1
    with open(locale_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    return updated

if __name__ == '__main__':
    nl_updated = apply_translations('/app/frontend/src/locales/nl.json', NL)
    print(f"Dutch (nl.json): {nl_updated} keys translated")
